### ISSUE TITLE
Add basic telemetry

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#1592]
### Important

This issue is based on this specification: https://github.com/meilisearch/specifications/blob/main/text/0034-telemetry-policies.md
All the spec is not implemented, we discuss together with @gmourier to decide what should be added for v0.22.0.

⚠️ For anything that is not clear or deeply detailed in this issue, please refer to this specification.

-----

TODO

- [ ] Number of indexes per instance
- [ ] Number of documents per index
- [ ] CPU and RAM per machine
<s>- [ ] SDK distribution (_spec is coming_)</s> will be done in a next version

-----

This impacts:
- @meilisearch/docs-team: the telemetry page should be improved
- <s>@meilisearch/integration-team: the SDKs should return the right information to MeiliSearch</s> Will be done in a next version

**Comment by curquiza** [comment]
@meilisearch/integration-team: checked with @gmourier, this will not be easy to add the SDK telemetry in v0.22.0, so the SDK telemetry addition is delayed! I removed the `impacts integrations` label then, the integration team is not concerned by this issue anymore 🙂

**Comment by guimachiavelli** [comment]
Since this issue has been delayed, is it still relevant for v0.22 docs?

**Comment by curquiza** [comment]
The SDK telemetry has been delayed only. Not the rest of the issue.
The docs-team still have to document the remaining 3 points (Number of indexes per instance, Number of documents per index, CPU and RAM per machine)

**Comment by guimachiavelli** [comment]
understood, thanks!

**Comment by curquiza** [comment]
Checked with @gmourier, finally, this will not be present in v0.22.0. We need more time to think about what we really need :)
I close this issue!
