### ISSUE TITLE
Update store rewrite and new task API

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/MeiliSearch#1780]
This tracking issue follows the development of the update store rewrite of the update store and the introduction of the new task API.

## Goals

The goals for this project are:
- re-designing the update store with the insights from #1679 
- introduce the task API
- Making all write operation asynchronous
- Preparing for HA
- Preparing for auto-batching

## Steps

Since this is a large task, I have identified multiple sub-parts to the project. The project will be merged continuously on a time frame spanning to release cycles, and will be only accessible with the feature flag `task-api`.

- [ ] Introduce a new crate in the workspace: `meilisearch-tasks`.
- [ ] Define the update API.
- [ ] Implement core functionalities (push update, pop and perform update)
- [ ] Implement listing of update, and state query
- [ ] Introduce new routes in `meilisearch-http`
- [ ] Connect the new update store to `meilisearch-http`
- [ ] Add relevant analytics according to specification
## Specifications
- https://github.com/meilisearch/specifications/blob/develop/text/0060-refashion-updates-apis.md

## Unresolved question
tbd.

**Comment by curquiza** [comment]
This issue follows this spec: [Refashion the Updat API](https://github.com/meilisearch/specifications/blob/develop/text/0060-refashion-updates-apis.md)
It impacts the @meilisearch/docs-team and the @meilisearch/integration-team
