### ISSUE TITLE
Improve the errors and test them

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#1785]
### Important

This issue is based on this specification: https://github.com/meilisearch/specifications/pull/61
The specification gathers all the information related to this feature: the motivation, the API and technical changes, the future possibilities...

⚠️ For anything that is not clear or deeply detailed in this issue, please refer to this specification.
Especially, for the @meilisearch/docs-team and the @meilisearch/integration-team, don't refer to this issue and always use the specification for your work.

--------

- [x] `errorCode`, `errorType` and `errorLink` are changed into `code`, `type`, `link`
- [x] The exhaustive list of errors present in [the spec](https://github.com/meilisearch/specifications/pull/61/files) should be well implemented. Most of them are already present, we need to check the message, the type, the code, and the link are correct according to the spec.
- [x] Add tests: each error should be tested. We might need to find a smart way to test the MeiliSearch errors. Except for 500 errors (aka internal errors) of course.

Since there are a lot of errors, this can be done in multiple PRs.

#### Invalid
- [x] bad_request
    - [x] Error Type & Code
    - [x] Error Message
- [x] index_already_exists
    - [x] Error Type & Code
    - [x] Error Message
- [x] invalid_index_uid
    - [x] Error Type & Code
    - [x] Error Message
- [x] index_primary_key_already_exists
    - [x] Error Type & Code
    - [x] Error Message
- [x] primary_key_inference_failed
    - [x] Error Type & Code
    - [x] Error Message
- [x] missing_document_id
    - [x] Error Type & Code
    - [x] Error Message
- [x] invalid_document_id
    - [x] Error Type & Code
    - [x] Error Message
- [x] document_fields_limit_reached
    - [x] Error Type & Code
    - [x] Error Message
- [x] invalid_ranking_rule
    - [x] Error Type & Code
    - [x] Error Message
        - [x] Variant: Sending an inexistent ranking rule or an invalid custom ranking rule syntax.
        - [x] Variant: Specifying a custom ranking rule on reserved fields `_geo` or `_geoDistance`
        - [x] Variant: Specifying a custom ranking rule on reserved expression `_geoPoint`
        - [x] Variant: Specifying a custom ranking rule on reserved expression `_geoRadius`
- [x] invalid_filter
    - [x] Error Type & Code
    - [x] Error Message
        - [x] Variant: Filtering on a non filterable attribute
        - [x] Variant: Using `_geoDistance` as a filter expression
        - [x] Variant: Using `_geo` or `_geoPoint` as a filter expression
        - [x] Variant: Invalid syntax for the `filter` parameter
- [x] invalid_sort
    - [x] EError Type & Code
    - [x] Error Message:
        - [x] Variant: Sorting on a non sortable attribute
        - [x] Variant: Using `_geoDistance` as a sort expression
        - [x] Variant: Using `_geo` or `_geoRadius` as a sort expression
        - [x] Variant: Invalid syntax for the `sort`parameter
        - [x] Variant: Specifying `sort` at search time while the sort ranking rule isn't set in the ranking rules settings
- [x] invalid_geo_field
    - [x] Error Type & Code
    - [x] Error Message
- [x] payload_too_large
    - [x] Error Type & Code
    - [x] Error Message
- [ ] not_found
- [x] index_not_found
    - [x] Error Type & Code
    - [x] Error Message
- [x] document_not_found
    - [x] Error & Code
    - [x] Error Message
- [x] dump_not_found
    - [x] Error Type & Code
    - [x] Error Message
- [x] task_not_found
    - [x]  Error Type & Code
    - [x]  Error Message
- [x] dump_already_processing
    - [x] Error Type & Code
    - [x] Error Message
- [x] invalid_content_type
    - [x] Error Type & Code
    - [x] Error Message
- [x] missing_content_type
    - [x] Error Type & Code
    - [x] Error Message
- [x] missing_payload
    - [x] Error Type & Code
    - [x] Error Message
- [x] malformed_payload
    - [x] Error Type & Code
    - [x] Error Message
        - [x] Variant: Syntax error
        - [x] Variant: Sending a valid but empty `[]`/`{}` payload on `POST`/`PUT` - `indexes/:indexUid/documents`.
#### internal type
- [x] internal
    - [x] Error Type & Code
    - [x] Error Message
- [x] index_creation_failed
    - [x] Error Type & Code
    - [x] Error Message
- [ ] index_not_accessible
    - [ ] Error Type & Code
    - [ ] Error Message
- [ ] unretrievable_document
    - [ ] Error Type & Code
    - [ ] Error Message
- [ ] invalid_state
    - [ ] Error Type & Code
    - [ ] Error Message
- [ ] dump_process_failed
    - [ ] Error Type & Code
    - [ ] Error Message
- [x] database_size_limit_reached
    - [x] Error Type & Code
    - [x] Error Message
- [x] no_space_left_on_device
    - [x] Error Type & Code
    - [x] Error Message
- [x] invalid_store_file
    - [x] Error Type & Code
    - [x] Error Message
#### auth type
- [x] missing_authorization_header
    - [x] Error Type & Code
    - [x] Error Message
- [x] invalid_api_key
    - [x] Error Type & Code
    - [x] Error Message

**Comment by curquiza** [comment]
Closed thanks to https://github.com/meilisearch/MeiliSearch/pull/1873 and https://github.com/meilisearch/MeiliSearch/pull/1873
