### ISSUE TITLE
Adds management of API Keys and their permissions

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#1867]
# Summary

The goal of this issue is to improve the way of handling API keys by following the related specification: https://github.com/meilisearch/specifications/pull/85
(Still a WIP)

# Implementation
## [Actions](https://github.com/meilisearch/specifications/blob/dbefc66902b4c71388020c1e3a2e5cd023c3a0d3/text/0085-api-keys-scoped-api-keys.md#actions-list-definition)
- [x] `search`  Provides access to GET and POST methods on /indexes/:authorizedIndexes/search routes.
- [x] `documents.add`   Provides access to POST and PUT on /indexes/:authorizedIndexes/documents routes.
- [x] `documents.get`  Provides access to GET methods on /indexes/:authorizedIndexes/documents/ and /indexes/:authorizedIndexes/documents/:documentId routes.
- [x] `documents.delete`    Provides access to DELETE method on indexes/:authorizedIndexes/documents/:documentId, indexes/:authorizedIndexes/documents/:documentId and POST method on indexes/:authorizedIndexes/documents/delete-batch routes.
- [x] `indexes.add`     Provides access to POST /indexes. ⚠️ The newly created index is added to the indexes array for this key and all others keys having [*] as a value for indexes.
- [x] `indexes.get`     Provides access to GET /indexes and /indexes/:authorizedIndexes. ⚠️Non-authorized indexes are ommited from the response on /indexes.
- [x] `indexes.update`  Provides access to PUT /indexes/:authorizedIndexes
- [x] `indexes.delete`  Provides access to DELETE /indexes/:authorizedIndexes
- [x] `tasks.get`   Provides access to GET /tasks and /indexes/:indexUid/tasks routes.
- [x] `settings.get`    Provides access to GET /indexes/:authorizedIndexes/settings and /indexes/:authorizedIndexes/settings/* routes.
- [x] `settings.update`     Provides access to POST /indexes/:authorizedIndexes/settings and /indexes/:authorizedIndexes/settings/* routes.
- [x] `settings.reset`  Provides access to DELETE /indexes/:authorizedIndexes/settings and /indexes/:authorizedIndexes/settings/* routes.
- [x] `stats`   Provides access to GET /stats/. ⚠️Non-authorized indexes are ommited from the response on /stats. Also add access to GET indexes/:authorizedIndexes/stats.
- [x] ` dumps`   Provides access to POST /dumps and GET /dumps/:dumpUid routes.

### [**POST** - `/keys`](https://github.com/meilisearch/specifications/blob/dbefc66902b4c71388020c1e3a2e5cd023c3a0d3/text/0085-api-keys-scoped-api-keys.md#request-definition)
- [x] test
- [x] Accessing this route without the `X-MEILI-API-KEY` header returns a [missing_authorization_header](0061-error-format-and-definitions.md#missing_authorization_header) error.
- [x] Accessing this route with a key that does not have permissions (i.e. other than the master-key) returns an [invalid_api_key](0061-error-format-and-definitions.md#invalid_api_key) error.
- [x] Omitted Content-Type header returns a [missing_content_type](0061-error-format-and-definitions.md#missing_content_type) error.
- [x] Sending an empty Content-Type returns an [invalid_content_type](0061-error-format-and-definitions.md#invalid_content_type) error.
- [x] Sending a different Content-Type than `application/json` returns an [invalid_content_type](0061-error-format-and-definitions.md#invalid_content_type) error.
- [x] Sending an empty payload returns a [missing_payload](0061-error-format-and-definitions.md#missing_payload) error.
- [x] Sending a different payload type than the Content-Type header returns a [malformed_payload](0061-error-format-and-definitions.md#malformed_payload) error.
- [x] Sending an invalid json format returns a [malformed_payload](0061-error-format-and-definitions.md#malformed_payload) error.
- [x] Omitting `actions` field from the payload returns a [missing_parameter](0061-error-format-and-definitions.md#missing_parameter) error.
- [x] Omitting `indexes` field from the payload returns a [missing_parameter](0061-error-format-and-definitions.md#missing_parameter) error.
- [x] Omitting `expiresAt` field from the payload returns a [missing_parameter](0061-error-format-and-definitions.md#missing_parameter) error.
- [x] Sending an invalid value for the `actions` field returns an [invalid_api_key_actions](0061-error-format-and-definitions.md#invalid_api_key_actions) error.
- [x] Sending an invalid value for the `indexes` field returns an [invalid_api_key_indexes](0061-error-format-and-definitions.md#invalid_api_key_indexes) error.
- [x] Sending an invalid value for the `expiresAt` field returns an [invalid_api_key_expires_at](0061-error-format-and-definitions.md#invalid_api_key_expires_at) error.
- [x] Sending an invalid value for the `description` field returns an [invalid_api_key_description](0061-error-format-and-definitions.md#invalid_api_key_description) error.

### [**GET** - `/keys/:key`](https://github.com/meilisearch/specifications/blob/dbefc66902b4c71388020c1e3a2e5cd023c3a0d3/text/0085-api-keys-scoped-api-keys.md#as-anna--i-want-to-get-details-about-an-api-key)

- [x] test
- [x] Accessing this route without the `X-MEILI-API-KEY` header returns a [missing_authorization_header](0061-error-format-and-definitions.md#missing_authorization_header) error.
- [x] Accessing this route with a key that does not have permissions (i.e. other than the master-key) returns an [invalid_api_key](0061-error-format-and-definitions.md#invalid_api_key) error.
- [x] Attempting to access an API key that does not exist returns an [api_key_not_found](0061-error-format-and-definitions.md#api_key_not_found) error.

### [**PUT** - `/keys/:key`](https://github.com/meilisearch/specifications/blob/dbefc66902b4c71388020c1e3a2e5cd023c3a0d3/text/0085-api-keys-scoped-api-keys.md#as-anna--i-want-to-update-api-key-to-change-its-restrictions)

- [x] test
- [x] Accessing this route without the `X-MEILI-API-KEY` header returns a [missing_authorization_header](0061-error-format-and-definitions.md#missing_authorization_header) error.
- [x] Accessing this route with a key that does not have permissions (i.e. other than the master-key) returns an [invalid_api_key](0061-error-format-and-definitions.md#invalid_api_key) error.
- [x] Attempting to access an API key that does not exist returns a [api_key_not_found](0061-error-format-and-definitions.md#api_key_not_found) error.
- [x] Omitted Content-Type header returns a [missing_content_type](0061-error-format-and-definitions.md#missing_content_type) error.
- [x] Sending an empty Content-Type returns an [invalid_content_type](0061-error-format-and-definitions.md#invalid_content_type) error.
- [x] Sending a different Content-Type than `application/json` returns an [invalid_content_type](0061-error-format-and-definitions.md#invalid_content_type) error.
- [x] Sending an empty payload returns a [missing_payload](0061-error-format-and-definitions.md#missing_payload) error.
- [x] Sending a different payload type than the Content-Type header returns a [malformed_payload](0061-error-format-and-definitions.md#malformed_payload) error.
- [x] Sending an invalid json format returns a [malformed_payload](0061-error-format-and-definitions.md#malformed_payload) error.
- [x] Omitting `actions` field from the payload returns a [missing_parameter](0061-error-format-and-definitions.md#missing_parameter) error.
- [x] Omitting `indexes` field from the payload returns a [missing_parameter](0061-error-format-and-definitions.md#missing_parameter) error.
- [x] Omitting `expiresAt` field from the payload returns a [missing_parameter](0061-error-format-and-definitions.md#missing_parameter) error.
- [x] Omitting `description` field while his value is different than `null` on the server-side returns a [missing_parameter](0061-error-format-and-definitions.md#missing_parameter) error.
- [x] Sending an invalid value for the `actions` field returns an [invalid_api_key_actions](0061-error-format-and-definitions.md#invalid_api_key_actions) error.
- [x] Sending an invalid value for the `indexes` field returns an [invalid_api_key_indexes](0061-error-format-and-definitions.md#invalid_api_key_indexes) error.
- [x] Sending an invalid value for the `expiresAt` field returns an [invalid_api_key_expires_at](0061-error-format-and-definitions.md#invalid_api_key_expires_at) error.
- [x] Sending an invalid value for the `description` field returns an [invalid_api_key_description](0061-error-format-and-definitions.md#invalid_api_key_description) error.

### [**GET** - `/keys`](https://github.com/meilisearch/specifications/blob/dbefc66902b4c71388020c1e3a2e5cd023c3a0d3/text/0085-api-keys-scoped-api-keys.md#as-anna--i-want-to-list-the-api-keys)

- [x] test
- [x] Accessing this route without the `X-MEILI-API-KEY` header returns a [missing_authorization_header](https://github.com/meilisearch/specifications/blob/develop/text/0061-error-format-and-definitions.md#missing_authorization_header) error.
- [x] Accessing this route with a key that does not have permissions (i.e. other than the master-key) returns an [invalid_api_key](https://github.com/meilisearch/specifications/blob/develop/text/0061-error-format-and-definitions.md#invalid_api_key) error.

### [**DELETE** - `/keys/:key`](https://github.com/meilisearch/specifications/blob/dbefc66902b4c71388020c1e3a2e5cd023c3a0d3/text/0085-api-keys-scoped-api-keys.md#as-anna--i-want-to-delete-an-api-key)

- [x] test
- [x] Accessing this route without the `X-MEILI-API-KEY` header returns a [missing_authorization_header](https://github.com/meilisearch/specifications/blob/develop/text/0061-error-format-and-definitions.md#missing_authorization_header) error.
- [x] Accessing this route with a key that does not have permissions (i.e. other than the master-key) returns an [invalid_api_key](https://github.com/meilisearch/specifications/blob/develop/text/0061-error-format-and-definitions.md#invalid_api_key) error.
- [x] Attempting to access an API key that does not exist returns a `api_key_not_found`.

### [**PATCH** - `/keys/:key`](https://github.com/meilisearch/specifications/blob/6e1af98f817e37da2515803da53599c1b5b74a67/text/0085-api-keys.md#as-anna--i-want-to-update-api-key-to-change-its-restrictions)

- [x] test
- [x] Accessing this route without the `X-MEILI-API-KEY` header returns a [missing_authorization_header](0061-error-format-and-definitions.md#missing_authorization_header) error.
- [x] Accessing this route with a key that does not have permissions (i.e. other than the master-key) returns an [invalid_api_key](0061-error-format-and-definitions.md#invalid_api_key) error.
- [x] Attempting to access an API key that does not exist returns a [api_key_not_found](0061-error-format-and-definitions.md#api_key_not_found) error.
- [x] Omitting Content-Type header returns a [missing_content_type](0061-error-format-and-definitions.md#missing_content_type) error.
- [x] Sending an empty Content-Type returns an [invalid_content_type](0061-error-format-and-definitions.md#invalid_content_type) error.
- [x] Sending a different Content-Type than `application/json` returns an [invalid_content_type](0061-error-format-and-definitions.md#invalid_content_type) error.
- [x] Sending an empty payload returns a [missing_payload](0061-error-format-and-definitions.md#missing_payload) error.
- [x] Sending a different payload type than the Content-Type header returns a [malformed_payload](0061-error-format-and-definitions.md#malformed_payload) error.
- [x] Sending an invalid json format returns a [malformed_payload](0061-error-format-and-definitions.md#malformed_payload) error.
- [x] Sending an invalid value for the `actions` field returns an [invalid_api_key_actions](0061-error-format-and-definitions.md#invalid_api_key_actions) error.
- [x] Sending an invalid value for the `indexes` field returns an [invalid_api_key_indexes](0061-error-format-and-definitions.md#invalid_api_key_indexes) error.
- [x] Sending an invalid value for the `expiresAt` field returns an [invalid_api_key_expires_at](0061-error-format-and-definitions.md#invalid_api_key_expires_at) error.
- [x] Sending an invalid value for the `description` field returns an [invalid_api_key_description](0061-error-format-and-definitions.md#invalid_api_key_description) error.

## [Using `API Key` on client-code](https://github.com/meilisearch/specifications/blob/6e1af98f817e37da2515803da53599c1b5b74a67/text/0085-api-keys.md#using-api-key-on-client-code)

- [x] Accessing any route with an `API Key` that has expired or, been deleted returns an [invalid_api_key](0061-error-format-and-definitions.md#invalid_api_key)
    - [x] /indexes/../search
    - [x] /indexes/../documents
    - [x] /indexes/../documents/..
    - [x] /indexes/../settings
    - [x] /indexes/../updates
    - [x] /indexes/../stats
    - [x] /indexes/../
    - [x] /indexes
    - [x] /keys/..
    - [x] /keys
- [x] Accessing any route with an API Key that don't have sufficient permissions to access it returns an [invalid_api_key](0061-error-format-and-definitions.md#invalid_api_key)
on routes:
    - [x] /indexes/../search
    - [x] /indexes/../documents
    - [x] /indexes/../documents/..
    - [x] /indexes/../settings
    - [x] /indexes/../updates
    - [x] /indexes/../stats
    - [x] /indexes/../
    - [x] /indexes
    - [x] /keys/..
    - [x] /keys
on actions:
    - [x] `search`
    - [x] `documents.add`
    - [x] `documents.get`
    - [x] `documents.delete`
    - [x] `indexes.add`
    - [x] `indexes.get`
    - [x] `indexes.update`
    - [x] `indexes.delete`
    - [x] `tasks.get`
    - [x] `settings.get`
    - [x] `settings.update`
    - [x] `settings.reset`
    - [x] `stats`
    - [x] ` dumps`

### Dump & snapshots

- [ ] ensure that keys are dumped and loaded correctly
- [ ] ensure that keys are snapshoted and loaded correctly

**Comment by curquiza** [comment]
@meilisearch/integration-team @meilisearch/docs-team 
This issue will impact you, more information in the spec and coming in this issue.
