### ISSUE TITLE
Improve indexation time when inserting documents

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2203]
Thanks to the @Kerollmops work on Milli's side, we succeed to improve the indexation time when inserting documents in an already existing database.

See the base PR:
- https://github.com/meilisearch/milli/pull/436

And the fixes to improve it
- https://github.com/meilisearch/milli/pull/456
- https://github.com/meilisearch/milli/pull/454

Steps:
- [x] @Kerollmops shares some metric so that we can communicate about them (before/after the improvement)
- [x] Release milli with these changes
- [x] Update the milli dependence in Meilisearch

---
Edit by @curquiza 16/03/2022

Another PR improved the indexation speed, https://github.com/meilisearch/milli/pull/467 done by @MarinPostma

**Comment by aariacarterweir** [comment]
I have meilisearch deployed on GKE and can only see it using a max of one core also.

**Comment by curquiza** [comment]
Hello @aariacarterweir 
This issue is only related to the specific improvement regarding the insertion of documents done by @Kerollmops in the different PRs.

You would be more interested in the open discussion dedicated to [indexing performance](https://github.com/meilisearch/meilisearch/discussions/2131).
The goal of this discussion is to centralize issues to help us to target the main bottlenecks.
Don't hesitate to test the potential fixes written in the post, and, if it doesn't work, write a comment explaining your issue.

We will continuously be working on the indexing time while it's not satisfying for our users.

Thanks for your interest in Meilisearch!

**Comment by Kerollmops** [comment]
Here are the benchmarks before/after my improvements on the time spend in the prefix databases. These databases and data structures are used by the engine to reduce the time spent searching for all the words (or pairs of words) that start with a given prefix. Computing those can take time and we are now using a difference between the previous and newly created prefix word FST instead.

# Do not recompute the prefix databases

In this experiment, we indexed 80m songs and then sent 10x batches of 10 documents that are not known by the engine.

## Settings

```json
{
    "searchableAttributes":
    [
        "title",
        "album",
        "artist"
    ],
    "displayedAttributes":
    [
        "id",
        "title",
        "album",
        "artist",
        "genre",
        "country",
        "released",
        "duration"
    ],
    "criteria":
    [
        "words",
        "typo",
        "proximity",
        "attribute",
        "released-timestamp:desc"
    ],
    "filterableAttributes":
    [
        "released-timestamp",
        "duration-float",
        "genre",
        "country",
        "artist"
    ]
}
```

### Before (`45f5262`)

Here are the timing of the updates in seconds from the most recent to the least recent.

```
868.89 + 875.24 + 867.27 + 887.89 + 872.97 + 880.95 + 810.81 + 806.35 + 814.53 + 800.37 + 2932.98 = 11418.25

11418.25 / 60 / 60 = 3.17
```

It takes 3 hours and 10 minutes to index with the previous version of the engine.

### After (`25d7ed8`)

Here are the timing of the updates in seconds from the most recent to the least recent.

```
104.67 + 103.29 + 103.59 + 102.12 + 103.18 + 105.11 + 103.02 + 103.37 + 102.90 + 103.39 + 3090.65 = 4125.29

4125.29 / 60 / 60 = 1.145
```

It takes 1 hour and 8 minutes to index with the previous version of the engine.

**Comment by curquiza** [comment]
@meilisearch/devrel-team so that you can follow the issue, it might interest you for your communcation (v0.27.0, not now)

**Comment by MarinPostma** [comment]
adding to this issue, https://github.com/meilisearch/milli/pull/467 should about halve the times announced by @Kerollmops ! 🏎️

**Comment by curquiza** [comment]
Milli was bumped in https://github.com/meilisearch/meilisearch/pull/2244, with [milli v0.24.0](https://github.com/meilisearch/milli/releases/tag/v0.24.0) containing the current improvements regarding the indexation speed.
I don't close this issue yet since other improvements might be done during the sprint.
Plus final metrics might be needed to be shared again :)

**Comment by curquiza** [comment]
@Kerollmops you need to provide new metrics using milli v0.26.3 🚀

**Comment by Kerollmops** [comment]
Hey @curquiza,

I have made the same benchmarks as in https://github.com/meilisearch/meilisearch/issues/2203#issuecomment-1067812318 and the engine is much faster. Note that I have done my benchmarks on v0.27.0 (https://github.com/meilisearch/milli/commit/2aae19dc52740495a3502d4cf0911ffe1f478067, the latest commit).

```
67.93 + 68.24 + 67.88 + 68.05 + 69.02 + 67.84 + 68.28 + 67.68 + 74.42 + 69.24 + 2387.98 = 3076.56
3076.56 / 60 / 60 = 0.85
```

It takes 51 minutes to index 80 million and 100 new documents now! Good job @meilisearch/core-team 🎉

**Comment by irevoire** [comment]
:fire: :fire: :fire: I don't know why it's faster but :fire:

**Comment by curquiza** [comment]
🤘🤘🤘

**Comment by curquiza** [comment]
Closing this then!
