### ISSUE TITLE
Customize the typo tolerance

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2213]
Related to this spec: https://github.com/meilisearch/specifications/pull/117
Please refer to the spec for any detail)

---

## API changes (TLDR;)

- Add a `typo` index settings resource to manage customization of typo tolerance feature at index level.
    - Expose `typo` object on `/indexes/:index_uid/settings` endpoints.
    - Add `GET/POST/DELETE` - `/indexes/:index_uid/settings/typo` endpoints.
- `typo` object definition is made of the following properties:
     - `enabled`: Whether the typo tolerance feature is enabled. (Default: `true`)
     - `disabledAttributes`: Disable the typo tolerance feature on the specified document attributes. (Default: `[]`) 
     - `disabledWords`: Disable the typo tolerance feature for a set of query terms given during a search query. (Default: `[]`)
     - `minWordSizeForTypos`:
         -  `oneTypo`: Customize the minimum size for a word to tolerate 1 typo (Default: `5`) 
         -  `twoTypos`: Customize the minimum size for a word to tolerate 2 typos (Default: `9`) 

## Tracking issue

Depending on the time, we might want to implement only some parts first in v0.27.0, and then the other part in v0.28.0
Here are the expected steps in priority order

- [x] Enable/disable the typo tolerance (`enabled`)
- [x] `minWordSizeForTypos`
      - Customize the minimum size for a word to tolerate 1 typo (`oneTypo`)
      - Customize the minimum size for a word to tolerate 2 typos (`twoTypos`)
- [x] Disable the typo tolerance feature for a set of query terms given during a search query (`disabledWords`)
- [x] Disable the typo tolerance feature on the specified document attributes (`disabledAttributes`) -> more technical

## Linked PR:
- https://github.com/meilisearch/milli/pull/469
- #2249
- https://github.com/meilisearch/milli/pull/473
- https://github.com/meilisearch/milli/pull/474
- #2258 
- #2259
- #2296

**Comment by curquiza** [comment]
Validated by @gmourier

The whole implementation of the spec might be complicated regarding the time we have (4 weeks) and the complexity of some parts of the feature (like `disableOnAttributes`).
I've updated the description of the issue to let you track the accomplished work so that you will know what will be in the next release.
Keep an eye on the issue @meilisearch/integration-team @meilisearch/docs-team

**Comment by curquiza** [comment]
Checked with @MarinPostma this morning: every feature of the spec could be implemented for the next release, even `disableOnAttributes`. We'll keep you informed if there is any issue.

**Comment by curquiza** [comment]
Closed by all the linked PRs in the issue description 🚀

**Comment by curquiza** [comment]
@meilisearch/docs-team, just to be sure: the spec mentions the telemetry addition for the typo tolerance settings. Was it clear for you?
Sorry not to have put it in the issue description before.

Related PR (for the implementation: https://github.com/meilisearch/meilisearch/pull/2355

**Comment by guimachiavelli** [comment]
Yeap, already included in [v0.27's telemetry table](https://github.com/meilisearch/documentation/pull/1590/files#diff-357e1dff5c16d3acfd494b46503abfde4a0f25cc4e69d8ac917dedc303abdfe3R166-R170) ☺️
