### ISSUE TITLE
Improve and stabilize cropping and highlighting

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2214]
Here is the spec: https://github.com/meilisearch/specifications/pull/120

More information is coming once the spec is stabilized.

### Pull requests
- #2297
- [milli#483](https://github.com/meilisearch/milli/pull/483)

### checklist
- [x] `highlightPreTag` settings (#2297)
- [x] `highlightPostTag` settings (#2297)
- [x] `cropMarker` settings (#2297)
- [x] `cropLength` count word instead of chars (#2297)
- [x] `cropLength` 0 is now considered as no `cropLength` (#2297)
- [ ] ~smart crop finding the best matches interval~ (postponed) [milli#483](https://github.com/meilisearch/milli/pull/483)

**Comment by curquiza** [comment]
Pinging @meilisearch/integration-team and @meilisearch/docs-team. The spec is still a WIP, I will let you know when we'll have some updates.

**Comment by curquiza** [comment]
@meilisearch/integration-team and @meilisearch/docs-team: the smart crop is officially delayed to v0.28.0. All the other planned features are present.

A new issue has been open to handle the smart crop planned in v0.28.0: https://github.com/meilisearch/meilisearch/issues/2299

**Comment by brunoocasali** [comment]
Thanks for the information @curquiza 🥇

**Comment by guimachiavelli** [comment]
So cropping will keep its current behaviour: find the first occurrence of a search term and crop X amount of words starting from there, correct?

**Comment by curquiza** [comment]
Yes @guimachiavelli! :) the change of behavior will be for v0.28.0
