### ISSUE TITLE
v0.27.0 ROADMAP

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2220]
The purpose of this roadmap is to let anyone know about the different steps in the Meilisearch release.

# Draft phase (weeks 1-4)

Start: 14/02/2022
End: 14/03/2022

- [ ] Planification of the next release content (features, improvements, bug fixes). Meeting with the PM & and the core manager to discuss and agree on what we are going to put in the next release.
- [ ] Presentation of the next release content to the core team. Discussions with the team that can lead to some corrections.
- [ ] Discovery phase (most of the time, not every time, depending on the feature). The PM writes specifications, and devs prototype solutions.
- [ ] At the middle/end of the Draft phase, the PM and the core manager review together and agree a firm version of the next release plan. Nothing is strongly definitive, still needs to be validated by Guillaume.
- [ ] The core manager shares the firm version of the next release plan on #ms-release (Slack). It’s for information at this stage, no team can start working since the specs are not fully available yet.
- [ ] The PM provides the firm version of the specs, which means the implementation phase can begin.
- [ ] The core manager opens issues to add them to the [Milestones](https://github.com/meilisearch/meilisearch/milestone/28)

# Implementation phase (weeks 5-8)

Start: 14/03/2022
End: 11/04/2022

- [ ] The core manager posts a summary of the release dates on #ms-releases (Slack), links the milestones, and gives an overview of the main features. This could interest other teams, especially DevRel.
- [ ] At the beginning of the Implementation Phase, sync meeting with each manager of the open-source teams about the current implemented release. It’s an opportunity to remind where we need their review regarding the specs.
- [ ] The developers of the core team implement the planned content of the release according to the specifications. The code changes are merged into the `main` branch.
- [ ] Docs team organize their preparation: identify effect of new changes on the documentation, discussion phase
- [ ] According to feedback we receive from the devs, changes may be made to feature specs
- [ ] At the end of the Implementation phase, the core manager writes the changelog for the release
- [ ] The docs team reviews the changelogs.
- [ ] At the end of the Implementation Phase, all the issues related to the Milestone are solved, meaning every implementation has been merged into `main`. If something deffers for the original plan, the core manager should inform the other teams on #ms-releases (Slack).
- [ ] At the end of the Implementation Phase, sync meeting with each manager of the open-source teams about the coming release.

# Pre-release phase (weeks 9-12)

Start: 11/04/2022
End: 09/05/2022

- [ ] The core team release the first RC (release candidate) using the prepared changelogs.
- [ ] At the beginning of the Pre-release Phase, sync meeting with each manager of the open-source teams about the coming release. It’s an opportunity to plan and identify the parts where sync will be needed between the different team during the Pre-release Phase.
- [ ] The integrations team updates the SDKs and their integrations according to the new release.
- [ ] Docs team updating the documentation to reflect the changes of the new release.
- [ ] *Optional* - In some situation, the mini-dashboard also needs an update. This update might involve the integration team to release beta version of meilisearch-js and/or instant-meilisearch.
- [ ] According to feedback and bug reports from the integrations and the docs teams, the core team modify the code and/or fix bugs as soon as possible. Other RCs are released if necessary.
- [ ] DevRel team writes a blog post “What’s new in v0.X.Y?”. The core manager, the PM and the docs team must review.

# Release phase (week 13)

Release date: 09/05/2022

- [ ] Core team release the official version and let the other teams know when the binary and the Docker images are available
- [ ] New documentation deployment by the docs team
- [ ] Release of all the updated integrations by the integration team
- [ ] DevRel take care of external communications (blog, socials, etc).

**Comment by curquiza** [comment]
Dooooooone well done to everyone @meilisearch/core-team @meilisearch/docs-team @meilisearch/integration-team and @meilisearch/product-team ❤️
