### ISSUE TITLE
Tracking issue: simplify Docker usage and Dockerfile

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2235]
We would like to simplify the current Docker usage of Meilisearch by changing the Dockerfile.

This tracking issue gathers the issues we would like to solve. It does not have to be solved in the PR, but could be.

----

## Impacting the users

@meilisearch/integration-team @meilisearch/docs-team 

Changing the Docker behavior regarding the snapshots and the dumps by mounting only 1 folder instead of 3.
Related PR: https://github.com/meilisearch/meilisearch/pull/2178

- [x] Here is the new command to make the dumps and snapshots features work out-of-the-box with Docker and a single and simple command:
```bash
docker run -it --rm -v $PWD/meili_data:/meili_data -p 7700:7700 getmeili/meilisearch:latest
```
More information: https://github.com/meilisearch/meilisearch/issues/2235#issuecomment-1094903453
- [x] The `meilisearch` binary is not in the current working directory anymore. You cannot call the binary using `./meilisearch`. The binary is now accessible using different ways: `meilisearch`, `/meilisearch`, `/bin/meilisearch`.  We recommend using `meilisearch`.
This is only useful when the users want to pass arguments (like `--master-key`)
Example:
```bash
docker run -it --rm -v $PWD/meili_data:/meili_data -p 7700:7700 getmeili/meilisearch:latest meilisearch --no-analytics
```
More information: https://github.com/meilisearch/meilisearch/issues/2235#issuecomment-1094951711
- [x] This should fix: https://github.com/meilisearch/meilisearch/issues/2166 and https://github.com/meilisearch/meilisearch/issues/2085

## Transparent for the users

Only refactoring:
- [x] Simplify the Dockerfile by using only 1 build instead of 2, see https://github.com/meilisearch/meilisearch/issues/2234

## Not fixed, removed from this tracking issue
- Remove `tini` from the Dockerfile, see https://github.com/meilisearch/meilisearch/issues/2229

**Comment by brunoocasali** [comment]
@irevoire I don't have my test containers anymore in my local env. But do you know if we can have run the old way?

`docker run -p 7700:7700 getmeili/meilisearch:v0.26.0 ./meilisearch --master-key=masterKey`

Because if we do not support them, it will be a big breaking 😬

**Comment by curquiza** [comment]
We've just tested with @irevoire and nope, you will not be able to run with `./meilisearch`, I was updating this issue :)

**Comment by irevoire** [comment]
Yeah also we removed the change you proposed because then we were not able to debug our image, see https://github.com/meilisearch/meilisearch/issues/2229#issuecomment-1094941240

**Comment by curquiza** [comment]
@meilisearch/integration-team but also @meilisearch/docs-team 
Another breaking change, more impactful for integration team.

Using docker, the `meilisearch` binary is not in the current working directory anymore. When wanting to pass arguments to Meilisearch (like `--no-analytics`), you cannot call the binary using `./meilisearch` anymore but `meilisearch`, `/meilisearch`, or `/bin/meilisearch`. We recommend using `meilisearch`.
This is a Docker good practice.

✅
```bash
docker run -it --rm -p 7700:7700 getmeili/meilisearch:latest meilisearch --no-analytics
```

❌
```bash
docker run -it --rm -p 7700:7700 getmeili/meilisearch:latest ./meilisearch --no-analytics
```

@meilisearch/docs-team you have to check you don't have any Docker command running with `./meilisearch`, otherwise, nothing to document.

**Comment by curquiza** [comment]
I've updated the issue description so that we understand directly the changes

**Comment by curquiza** [comment]
Closed by #2178 so will be present in `v0.27.0rc0`
Please, feel free to test and let us know if it works as expected

**Comment by curquiza** [comment]
Pinging @meilisearch/cloud-team as well, since they use meilisearch with docker!
