### ISSUE TITLE
v0.28.0 ROADMAP

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2293]
The purpose of this roadmap is to let anyone know about the different steps in the Meilisearch release.

# Draft phase (weeks 1-4)

Start: 2022-04-11
End: 2022-05-09

- [x] Planification of the next release content (features, improvements, bug fixes). Meeting with the PM & and the core manager to discuss and agree on what we are going to put in the next release.
- [x] Presentation of the next release content to the core team. Discussions with the team that can lead to some corrections.
- [x] The PM writes specifications and organizes working groups.
- [x] At the middle/end of the Draft phase, the PM and the core manager review together and agree a firm version of the next release plan. Nothing is strongly definitive, still needs to be validated by Guillaume.
- [x] The core manager shares the firm version of the next release plan on #ms-release (internal Slack). It’s for information at this stage, no team can start working since the specs are not fully available yet.
- [x] The PM provides the firm version of the specs, which means the implementation phase can begin.
- [x] The core manager opens issues (including an issue for the version update in the `Cargo.toml` files) to add them to the [Milestones](https://github.com/meilisearch/meilisearch/milestone/30). Issues related to bugs could also be added to the Milestones.

# Implementation phase (weeks 5-8)

Start: 2022-05-16
End: 2022-06-13

- [x] The core manager posts a summary of the release dates on #ms-releases (internal  Slack), links the milestones, and gives an overview of the main features. This could interest other teams, especially DevRel.
- [x] At the beginning of the Implementation Phase, sync meeting with each manager of the open-source teams about the current implemented release. It’s an opportunity to remind where we need their review regarding the specs.
- [x] Core team implements the planned content of the release according to the specifications. The code changes are merged into the `main` branch.
- [x] Docs team organizes their preparation: identify the effect of new changes on the documentation, discussion phase and planning.
- [x] According to the feedback we receive from the devs, changes may be made to feature specs
- [x] At the end of the Implementation Phase, the core manager writes the changelog for the release
- [x] Docs team reviews the changelogs.
- [x] Integration team opens a central issue on [integration-guides](https://github.com/meilisearch/integration-guides) gathering all the release changes that will impact the integration team and how they will handle them
- [x] Integration team opens draft branches in every repository to make the integrations up-to-date with the new version of Meilisearch.
- [x] At the end of the Implementation Phase, all the issues related to the Milestone are solved, meaning every implementation has been merged into `main`. If something differs from the original plan, the core manager should inform the other teams on #ms-releases (internal Slack).

# Pre-release phase (weeks 9-12)

Start: 2022-06-13
End: 2022-07-11

- [x] Core team release the first RC (release candidate) using the prepared changelogs.
- [x] At the beginning of the Pre-release Phase, sync meeting with each manager of the open-source teams about the coming release. It’s an opportunity to plan and identify the parts where sync will be needed between the different teams during the Pre-release Phase.
- [x] Integrations team updates the SDKs and their integrations according to the new release.
- [x] Docs team updated the documentation to reflect the changes of the new release.
- [x] The mini-dashboard also [needs an update](https://github.com/meilisearch/meilisearch/issues/2469). This update might involve the integration team to release beta version of meilisearch-js and/or instant-meilisearch.
- [x] According to feedback and bug reports from the integrations and the docs teams, the core team modify the code and fix bugs as soon as possible. Other RCs are released if necessary.
- [x]  DevRel team write a blog post “What’s new in v0.X.Y?”.
- [x] The core manager, the PM, and the docs team review the blog post.
- [x] Integration team confirms the latest RC (so at the end of the Pre-release Phase) works with their DevOps tools 

# Release phase (week 13)

Release date: 2022-07-11

- [x] Core team releases the official version and lets the other teams know when the binary and the Docker images are available on #ms-releases (internal Slack).
- [x] New documentation deployment by the docs team
- [x] Release of all the updated integrations by the integration team
- [x] DevRel team takes care of external communications (blog, socials, etc) but might want for the documentation and the assets of the release to be ready (including Docker image)
- [x] Bring changes from `stable` branch of Meilisearch into the `main` branch
- [x] Close every part relating to the release in the [product repository](https://github.com/meilisearch/product/): discussions, issues, PRs of the specs are merged...
- [x] Close the release [Milestones](https://github.com/meilisearch/meilisearch/milestone/30)

**Comment by curquiza** [comment]
Pinging @meilisearch/docs-team @meilisearch/integration-team @meilisearch/devrel-team @meilisearch/cloud-team FYI

**Comment by sanders41** [comment]
@curquiza a small suggestion unrelated to the content. When I first glanced at

```md
Start: 11/04/2022
End: 09/05/2022
````

I though start in November and end in September doesn't make sense (I know in the US we do lots of things like dates weird :smile:)

The DD-Mon-YYYY I think would be immediately apparent to everyone.

```md
Start: 11-APR-2022
End: 09-MAY-2022
```

Obviously not a big deal, just a suggestion.

**Comment by guimachiavelli** [comment]
I think @sanders41 makes a very good point. We had similar problems in the docs team because one of ours is American and used to wonky date formats.

For what it's worth, [in the docs we have started using `YYYY-MM-DD`](https://github.com/meilisearch/documentation/issues/1530) and it seems to have completely eliminated ambiguity.

**Comment by sanders41** [comment]
@guimachiavelli I agree `YYYY-MM-DD` would also solve the problem.

**Comment by sanders41** [comment]
> EDIT: for clarity, I mean wonky in an affectionate, non-judgemental, no-shade-intended way

No offense taken, you aren't wrong :smile:

**Comment by curquiza** [comment]
Thanks for your feedback @sanders41 and @guimachiavelli, I'll update this!

**Comment by curquiza** [comment]
Hello everyone
Since the Meili teams have an offsite from 2022-05-09 to 2022-05-13, the work regarding v0.28.0 cannot progress during this week. So we postpone (by 1 week) the implementation phase, the pre-release phase, and finally the final release date 😊 
Just to let you know!

**Comment by curquiza** [comment]
Closed since [v0.28.0](https://github.com/meilisearch/meilisearch/releases/tag/v0.28.0) has been fully released
