### ISSUE TITLE
Dump v5 checklist

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/meilisearch#2430]
v0.28.0 will introduces changes to the API keys and tasks API that forces us to break dump v4.

We will then create a new dump version, and use this opportunity to break everything that we want to break.

- [x] changes to api keys (#2438)
- [x] in tasks, move the index_uid inside the task content, instead of being on the task itself
- [x] rename `TaskEvent::Succeded` to `TaskEvent::Succeeded`
- [x] remove `DUMPS_GET` policy

we also need to handle the conversion from v4 to v5.

pinging @meilisearch/core-team  to add to this issue.

**Comment by ManyTheFish** [comment]
The dump's retro compatibility is not full with API keys.
All the previous keys will be re-imported with the same `actions` and `indexes` values.
But the `key` and `uid` fields will be regenerated.
This will force the end-user to update the `key` value on each connected application.

**Comment by MarinPostma** [comment]
I think all the pr that fixed this have been merged, so we can close this.
