### ISSUE TITLE
v0.29.0 ROADMAP

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2490]
The purpose of this roadmap is to let anyone know about the different steps in the Meilisearch release.

# Draft phase (weeks 1-4)

Start: 2022-06-13
End: 2022-07-11

- [x] Planification of the next release content (features, improvements, bug fixes). Meeting with the PM & and the core manager to discuss and agree on what we are going to put in the next release.
- [x] Presentation of the next release content to the core team. Discussions with the team can lead to some corrections.
- [x] The core manager shares quickly the next release plan on #ms-release (internal Slack). It’s for information at this stage, no team can start working since no PRD/specs are available.
- [x] The PM starts to work on the next feature: write PRD (Product Requirement Documents), organize working groups and product squad works... This might involve discussions with the technical teams and some prototype implementations.
- [x] At the middle/end of the Draft phase, the PM and the core manager review together and agree on a firm version of the next release plan. Nothing is strongly definitive, the main goal is to provide a list of tasks ordered by prioritization.
- [x] The core manager opens issues to add them to the [Milestones](https://github.com/meilisearch/meilisearch/milestone/32). Issues related to bugs could also be added to the Milestones.
- [x] The PM provides the firm version of the PRDs, which means the developers have enough information to make the implementation phase begin.

# Implementation phase (weeks 5-11)

Start: 2022-07-11
End: 2022-08-29

- [x] The core manager posts a summary of the release dates on #ms-releases (internal  Slack), links the milestones, and gives an overview of the main features. This could interest other teams, especially DevRel.
- [x] At the beginning of the Implementation Phase, sync meeting with each manager of the open-source teams about the current implemented release.
- [x] Core team implements the planned content of the release according to the PRD. The code changes are merged into the `main` branch. If needed, prototypes will be shared with the users. According to their feedback, we might apply changes to the related feature.
- [x] The specifications are written: they are useful to officialize the definitive "shape" of the feature. However, feedback and request for changes on the spec can still happen and lead to changes in the related feature.
- [x] Docs team organizes their preparation: identify the effect of new changes on the documentation, discussion phase and planning.
- [x] At the end of the Implementation Phase, the core manager writes the changelog for the release
- [x] Docs team reviews the changelogs.
- [x] Integration team opens a central issue on [integration-guides](https://github.com/meilisearch/integration-guides) gathering all the release changes that will impact the integration team and how they will handle them
- [x] Integration team opens draft branches in every repository to make the integrations up-to-date with the new version of Meilisearch.
- [x] At the end of the Implementation Phase, all the issues related to the Milestone are solved, meaning every implementation has been merged into `main`. If something differs from the original plan, the core manager should inform the other teams on #ms-releases (internal Slack).

# Pre-release phase (weeks 12-15)

Start: 2022-08-29
End: 2022-10-03

- [x] Core team release the first RC (release candidate) using the prepared changelogs.
- [x] At the beginning of the Pre-release Phase, sync meeting with each manager of the open-source teams about the coming release. It’s an opportunity to plan and identify the parts where sync will be needed between the different teams during the Pre-release Phase.
- [x] At the beginning of the Pre-release Phase, the core manager shares the important changes to highlight in the release blog post to the DevRel team.
- [x] At the beginning of the Pre-release Phase, the PM and core manager communicate about the RC in order to encourage people to test them.
- [x] Integrations team updates the SDKs and their integrations according to the new release.
- [x] Docs team updated the documentation to reflect the changes of the new release.
- [x] Optional - The mini-dashboard might also need an update involving the integration team to release beta version of meilisearch-js and/or instant-meilisearch.
- [x] According to feedback and bug reports from the integrations and the docs teams, the core team modify the code and fix bugs as soon as possible. Other RCs are released if necessary.
- [x]  DevRel team write a blog post “What’s new in v0.X.Y?”.
- [x] The core manager, the PM, and the docs team review the blog post.
- [ ] Integration team confirms the latest RC (so at the end of the Pre-release Phase) works with their DevOps tools 

# Release phase (week 16)

Release date: 2022-10-03

- [x] Core team releases the official version and lets the other teams know when the binary and the Docker images are available on #ms-releases (internal Slack).
- [x] New documentation deployment by the docs team
- [x] Release of all the updated integrations by the integration team
- [x] DevRel team takes care of external communications (blog, socials, etc) but might want for the documentation and the assets of the release to be ready (including Docker image)
- [x] Bring changes from `stable` branch of Meilisearch into the `main` branch
- [ ] Create a label `vX.Y.Z` (version of the release) and tag it to all the issues/PRs of the Milestones.
- [ ] Close every part relating to the release in the [product repository](https://github.com/meilisearch/product/): discussions, issues, PRs of the specs are merged...
- [ ] Close the release Milestones

**Comment by curquiza** [comment]
@meilisearch/docs-team @meilisearch/devrel-team @meilisearch/integration-team @meilisearch/core-team FYI 🤟

**Comment by curquiza** [comment]
Hell everyone, due to the summer Holiday at Meili, and according to our internal discussions, I've updated the date of this sprint
- start of the sprint: still 11th July
- end of the implementation, so beginning of the pre-release: 29th August instead of 8th August (7 weeks instead 4 weeks)
- end of the pre-release, so the official release date: 26th September instead of 5th September (still 4 weeks)

Thanks for your understanding, and have nice holidays!

**Comment by curquiza** [comment]
Sorry, some date changes again! Due to an internal seminary at Meili, we chose to increase the pre-release phase.
The ore-release phase still starts on 29th August but will end on 3rd October, meaning the official v0.30.0 release will be on the 3rd of October
I updated this issue description accordingly 😊

**Comment by curquiza** [comment]
Released done!
