### ISSUE TITLE
Ability to pass a configuration file to Meilisearch

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2558]
Discussed with @gmourier and following this information: [https://github.com/meilisearch/product/discussions/85#discussioncomment-2864656](https://github.com/meilisearch/product/discussions/85#discussioncomment-2864656)

We want Meilisearch to accept a configuration file that would be an alternative to the [command-line options](https://docs.meilisearch.com/learn/configuration/instance_options.html#command-line-options-and-flags) you can set when launching Meilisearch, for instance

```bash
meilisearch --master-key=XXX
```

# Requirements

### Format

The file format should be `TOML`.

### Priority order

Configuration file < [Env variables](https://docs.meilisearch.com/learn/configuration/instance_options.html#environment-variables) < [command-line options](https://docs.meilisearch.com/learn/configuration/instance_options.html#command-line-options-and-flags)

It means the options in the configuration file can be overwritten by the environment variable set (if they exist) and that can be themself overwritten by the command-line options (if they exist)

Example

With this config file

```bash
master_key = "thisisasuper1337masterkey@@@"
db_path = "./filepath1"
http_address = "127.0.0.1:7701"
no_anayltics = true
```

and with the following variables and command-line options:

```bash
export MEILI_DB_PATH=./filepath2
export MEILI_HTTP_ADDR=127.0.0.1:7702

meilisearch --master-key=abcd1234 --db-path=./filepath3
```

The final values kept by Meilisearch will be

- No analytics thanks to `no_analytics = true` set in the config file
- The db path is `filepath3` because `--db-path=./filepath3` has been set as command line options. `./filepath1` and `./filepath2` are ignored.
- The HTTP address is `127.0.0.1:7702` because set as an environment variable. The value in the config file (`127.0.0.1:7701`) is ignored.
- The master key is `abcd1234` set in the command-line option. The value in the config file is ignored ( `thisisasuper1337masterkey@@@` ).

### Config file content

<s>The config file will have sections gathering the same kind of variable.

Example:

```bash
master_key = "thisisasuper1337masterkey@@@"
no_analytics = true

[dump]
path = "dumps"

[snapshot]
enabled = true

[ssl]
require_auth = true
```
</s>

See [comments below](https://github.com/meilisearch/meilisearch/issues/2558#issuecomment-1239681961), sections are not something we want.

What we would rather: a default config file containing
- fake sections separated by comments
- a comment header redirecting to the documentation for more information

@meilisearch/docs-team this file could be easily downloaded 

```bash
curl https://raw.githubusercontent.com/meilisearch/meilisearch/main/config.toml > config.toml
```

### Config file command line

The default config file name is `config.toml` and will be retrieved by Meilisearch by default in the current working directory

You can pass the config file as command-line option

```bash
meilisearch --config-file-path="./config.toml"
```

So the default value of `config-file-path` is `./config.toml`.

This means by default, Meilisearch will try to read `./config.toml`.

If no `./config.toml` file is found and no `--config-file-path` option is passed, Meilisearch does not throw any error.
If `--config-file-path` is passed and is associated to an existing file (or impossible to open), Meilisearch throw an error

### Display when launching Meilisearch

```
888b     d888          d8b 888 d8b                                            888
8888b   d8888          Y8P 888 Y8P                                            888
88888b.d88888              888                                                888
888Y88888P888  .d88b.  888 888 888 .d8888b   .d88b.   8888b.  888d888 .d8888b 88888b.
888 Y888P 888 d8P  Y8b 888 888 888 88K      d8P  Y8b     "88b 888P"  d88P"    888 "88b
888  Y8P  888 88888888 888 888 888 "Y8888b. 88888888 .d888888 888    888      888  888
888   "   888 Y8b.     888 888 888      X88 Y8b.     888  888 888    Y88b.    888  888
888       888  "Y8888  888 888 888  88888P'  "Y8888  "Y888888 888     "Y8888P 888  888

Config file path:       "./config.toml"
Database path:		"./data.ms"
```

If the users do not pass any config file and no `./config.toml` exists, we must display `none` instead of `"./config.toml"`

### Errors (bonus)

We need to parse and display clear errors message for the configuration scheme. e.g. [https://docs.rs/miette/latest/miette/](https://docs.rs/miette/latest/miette/)

# Implementations

We could probably start by using [the toml crate](https://lib.rs/crates/toml) and declare a struct with a simple derive on it. We could start the job in [the options.rs file](https://github.com/meilisearch/meilisearch/blob/main/meilisearch-lib/src/options.rs) or maybe create a new one specifically for this config file.

If you have any questions regarding the feature or the implementation, please let us know about this issue! Every feedback or questions are welcome!

# TODO

- [ ] Merge the first iteration of this issue (https://github.com/meilisearch/meilisearch/pull/2745)
- [ ] Improve the default config file (assigned: @curquiza)
- [ ] Fix the following sub-issues
  - [ ] https://github.com/meilisearch/meilisearch/issues/2800
  - [ ] https://github.com/meilisearch/meilisearch/issues/2801
- [ ] Create the specification

--- 

## For Meili people

A spec will be open once we have implemented it. Some changes can still be applied, we need to see the final implementation to create the spec.
Since we let this issue (so far) to the community, we don't know yet in which release this new feature will be available (at minimum v0.29.0, not before).

Ping @meilisearch/cloud-team @meilisearch/docs-team who can be concerned by this issue.

**Comment by curquiza** [comment]
Also pinging @meilisearch/integration-team who can be interesting for their devops tools 😇

**Comment by YJDoc2** [comment]
Hey, this is a really cool project, and I would like to contribute to this is possible. As this issue is open, can I try to work on it?

As far as I understand, https://github.com/meilisearch/meilisearch/blob/main/meilisearch-http/src/lib.rs#L30 sets up the meilisearch with its options, so my thought for this is to declare a struct with all cmd line option, parse it using toml as suggested, and then in the set up function, conditionally give cmd opts or config file opts, as by the priority mentioned. I might even declare a new struct for the purpose of combining the config file ind cmd opts, which will be given to the set up function instead of giving it the clap parsed opts directly. 

The issues that I'm currently thinking of in this are :
- the requirements state that config file values must be overridden by env vars, which must be overridden by cmd options; but as far as I have found, clap handles checking env vars and setting values, so are we supposed to simply override values of config file by the opts structure values, or parse the env vars ourselves, removing it from clap and apply the priority order?
- Defining a separate struct to store the config file values and then combining with cmd values is tedious as well as harder to maintain, as we'll have to duplicate any new options in both. I'll try to see if we can somehow use clap for using the same struct to parse toml file, or at least if the toml lib can be used on same struct, so there won't be duplication. (Although, config file is itself a cmd option, so will have to watch out for that!)

What do you think about the above? Can I work on this issue, or should I check something else first?

Thanks :)

**Comment by YJDoc2** [comment]
Hey, one of the issues for using the same struct for toml and opts is there are some fields set as `skip` for serializing in `serde` . toml crate uses serde to deserialize the , so it will not be able to read those from the file, as of now. For example, the no_analytics is set to skip, so cannot be read from config file, but in the spec above that field is used.
A way to resolve this, is to change `skip` to `skip_serializing`, which will disable serializing but will still allow reading from file. (https://serde.rs/attr-skip-serializing.htm) .  One of the changes needed for that is to add default values for non-option-skip fields, which is do-able.

Another issue is that the above spec suggests that the config file should ideally group the keys in sections by type :
>The config file will have sections gathering the same kind of variable.

But as the fields in opts structs are separate, they cannot be grouped in toml. For that to be possible, the similar options must be moved into a struct which then appear as a section in the toml ;  but that will cause changes in all places where those variables are used.

Also, to get clarification, 
>So the default value of config-file-path is ./meili_config.toml.
>This means by default, Meilisearch will try to read ./config.toml.

 Should the default be `meili_config.toml` or `config.toml`?

Thanks :)

**Comment by irevoire** [comment]
> A way to resolve this, is to change skip to skip_serializing, which will disable serializing but will still allow reading from file.

Yes, that's perfect :+1: 

> For that to be possible, the similar options must be moved into a struct which then appear as a section in the toml ; but that will cause changes in all places where those variables are used.

Don't you think you can make your multiple structures but still make thing shows correctly in clap with a bunch of `flatten`?

> Should the default be meili_config.toml or config.toml?

I don't think we're going to auto-import a config file. Thus you'll need to add a cli option to import the config file, and its name can be anything :grin:

**Comment by eskombro** [comment]
Would it be too much work, and would it be interesting, to support both YAML and TOML?

YAML is the most widely used format on cloud-native applications. But TOML is indeed way easier to parse, and we don't need to handle the whitespace hell of YAML files. Just wondering if being able to handle both would make life easier for many, or if it would introduce unnecessary complexity for the development/ maintenance of the feature!

**Comment by curquiza** [comment]
Hello @eskombro 
We want to gather discussion about the product decision in the product repository. Here is the [dedicated discussion about it](https://github.com/meilisearch/product/discussions/85)

**Comment by knidarkness** [comment]
Hello guys,

I've been experimenting with the Meilisearch in several projects and really liked the experience, thus I want to contribute to this project. 

I was wondering if @YJDoc2 is still working on this feature, and if not I'd like to pick it up and use the discussion above as a foundation.

**Comment by YJDoc2** [comment]
Hey @knidarkness , if the Meilisearch team is fine with it, you can go ahead. Unfortunately, I wasn't able to do much progress on this due to some personal reasons :sweat: 
Apologies to Meilisearch team for not being able to contribute, I should have done better :sweat:

**Comment by irevoire** [comment]
Hey, @YJDoc2, that's not an issue at all, and you helped us to think more of what we wanted to do; thanks for spending time on the project! ❤️ 

And thus, @knidarkness, welcome to the team 😁

**Comment by curquiza** [comment]
Hello @YJDoc2 and @knidarkness, just to let you know we are planning to release this feature in v0.30.0. It means the core team will start the implementation of the feature on 3rd October if no one has made it before.
It also means you have until the end of September to do it if you are still motivated to contribute 😉 Thank again for your involvement!

**Comment by mlemesle** [comment]
Hello everyone !

I’d like to contribute to Meilisearch and this seems to be a good first issue ! May I ask if @knidarkness is still working on it to avoid duplicate the work ?

**Comment by curquiza** [comment]
Hello @mlemesle, as far as I know, no one has started to work on it. So we are really happy to review your future PR. Ping us on your PR once it's ready to be reviewed! 😄 

Thanks a lot for your contribution!

**Comment by mlemesle** [comment]
Hey @curquiza ! Thanks for letting me contribute, this is a great opportunity !

I got an issue though. The toml config file shown as an example is partial, all the mandatory informations needed to setup Meilisearch are not present. From the cli, this isn’t a problem because clap can default their value. However, reading the file and deserializing it directly raise an error because some fields are not provided.

How do you want to resolve this ? Should the toml be lax about its content ? Or all mandatory fields should be present ?

Thanks for the answer.
Feel free to reach out if you need more details !

**Comment by Kerollmops** [comment]
Hey @mlemesle,

We didn't think about this issue indeed. I have two ideas:
 - Why is that not possible [to use `#[serde(default = "path")]`](https://serde.rs/field-attrs.html)?
 - I am not sure it would be a good idea to force all of the fields as mandatory:
     1. We must synchronize the `Opt` struct clap values with the default config file every time we change the default values.
     2. It can be a lot of information to look at as a user that just wants to add some special settings.

**Comment by mlemesle** [comment]
Hi @Kerollmops ! Thanks for your quick answer !

I think #[serde(default = "path")] might be relevant, however it’s the path to a function, not a value, so I’ll have to find a way to do it cleanly.

I agree that forcing all fields as mandatory isn’t my favorite choice either, just wanted to run it by you to be clear about the needs !

**Comment by mlemesle** [comment]
Hey ! 

I finished setting all the default values for serde. The config file now works just fine :)

However, I'm not sure about the sections in the config file. It will imply to flatten with clap (which is fine), but we won't be able to flatten with serde because it will flatten for deserialization and serialization. So, in order to have sections, we can't flatten with serde. Doing so, this will change the json that is send to analytics and this will require further modifications.

I don't know if that's something you had in mind. Shoud the sections still be added ? 

Thanks :)

**Comment by mlemesle** [comment]
Hey ! 

PR is ready for review ! 🙂

**Comment by gmourier** [comment]
Hi @mlemesle 👋

Thanks for the contribution; this is hugely appreciated 🙏

Regarding the section, I had a quick talk with @irevoire and @Kerollmops.

As it forces us to lose the history on the analytics side because we have no way to merge properties for the moment on our side, it seems smart to me not to introduce them. 

However, I would like to have the opinion of the cloud team.

Initially, we thought of sections to facilitate the readability of the configuration file. However, thinking about it, comments in a file provided by default would fulfill this role of helping the reading.

In essence, this is what it means @meilisearch/cloud-team.

Rather than having this

```toml
[snapshots]
schedule-snapshot=true
snapshot-interval-sec=2600
```

We would have this

```toml
# Snapshots
schedule-snapshot=true
snapshot-interval-sec=2600
```

WDYT?

**Comment by gmourier** [comment]
It would be nice to introduce a config.yml containing each config with its default value for newcomers. It might help someone to get to know the configuration variables by reading the file provided as a starter. We could even insert a comment header to the documentation with a [link](https://docs.meilisearch.com/learn/configuration/instance_options.htm).

WDYT?

**Comment by curquiza** [comment]
I agree
- comments instead of sections is a good idea
- having a default config file with links to the docs is even better
I'll update the issue description

**Comment by mlemesle** [comment]
Hey @curquiza ! 
I just added a default toml file with "comment sections".
Everything is commented so it’s less prone to errors for clients, they just need to uncomment the desired key and replace the value.
I put the link to the documentation at the very top of the file and added the documentation to each key of the file.

Hope that helps !

**Comment by curquiza** [comment]
Hello @mlemesle, but also @gmourier and @irevoire 

I've discussed with the team, and we realized we had a quiproquo: we want Meilisearch to read `./config.toml` as default behavior, even if the flag `--config-file-path` is not passed

We also want the following display

```
888b     d888          d8b 888 d8b                                            888
8888b   d8888          Y8P 888 Y8P                                            888
88888b.d88888              888                                                888
888Y88888P888  .d88b.  888 888 888 .d8888b   .d88b.   8888b.  888d888 .d8888b 88888b.
888 Y888P 888 d8P  Y8b 888 888 888 88K      d8P  Y8b     "88b 888P"  d88P"    888 "88b
888  Y8P  888 88888888 888 888 888 "Y8888b. 88888888 .d888888 888    888      888  888
888   "   888 Y8b.     888 888 888      X88 Y8b.     888  888 888    Y88b.    888  888
888       888  "Y8888  888 888 888  88888P'  "Y8888  "Y888888 888     "Y8888P 888  888

Config file path:              "./config.toml"
Database path:		"./data.ms"
```

If the users do not pass any config file and no `./config.toml` exists, we must display `none` instead of `"./config.toml"

Sorry again for the confusion
If you don't have the time to update your PR, it's completely ok: we will merge your PR into a temporary branch we will continue.
I will update the issue accordingly!

**Comment by mlemesle** [comment]
Hey @curquiza !

It's ok, I'll try to do it before next week ! Thanks for allowing me to improve my contribution !

**Comment by curquiza** [comment]
Related to the following spec: https://github.com/meilisearch/specifications/pull/185
