### ISSUE TITLE
Cancelling tasks

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2749]
The goal of this issue is to reduce the users' friction with task management by allowing them to cancel a `processing` or an `enqueued` task.
Indeed, the indexing time is sometimes really long, and the users want to cancel them to prioritize the others tasks in the queue.

## TODO

- [ ] Work on [PRD](https://www.notion.so/meilisearch/Solve-workflow-blockages-when-managing-a-running-Meilisearch-instance-8b1d2351f0c24eaabe2c371156409939) (internal link only)
- [ ] Create a prototype if needed
- [ ] Create the spec
- [ ] Implement the final version in the code and merge it into `main`

⚠️ Depends on scheduler refactoring https://github.com/meilisearch/meilisearch/issues/2725

## Impacted teams

@meilisearch/docs-team @meilisearch/integration-team

**Comment by curquiza** [comment]
Spec created https://github.com/meilisearch/specifications/pull/196
and added to this issue description
