### ISSUE TITLE
Improve the tokenizer

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/MeiliSearch#275]
- [ ] support URLs and slashes (#276)
- [ ] support Turkish characters (#546)
- [ ] support Russian characters (#552)
- [ ] support Persian [Farsi] characters (#553)
- [ ] support Arabic characters (#554)
- [ ] support Lao characters (#563)

**Comment by MarinPostma** [comment]
closed in favor of #624
