### ISSUE TITLE
Index swap

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2750]
The goal of this issue is to make Meilisearch more production-ready by allowing the swap of indexes.
Indeed, this feature should remove the possible downtimes: the users will be able to index on a temporary index and then, swap the index names.

## TODO

- [x] Work on PRD
- [ ] Create a prototype if needed
- [ ] Create the spec
- [ ] Implement the final version in the code and merge it into `main`

⚠️ Depends on scheduler refactoring https://github.com/meilisearch/meilisearch/issues/2725

## Impacted teams

@meilisearch/docs-team @meilisearch/integration-team
Also pinging @meilisearch/cloud-team in case you would need it. Feel free to unsubscribe from this issue if I'm wrong.

**Comment by gmourier** [comment]
To be precise, we don't know if it will be swapping or aliasing. There's a good chance it will be swapping, but I'd rather make that clear from the name of the issue 😇

I'll have more information next week.

**Comment by aaron5670** [comment]
I'll follow this topic. I'm waiting for this functionality for long time. :)

**Comment by curquiza** [comment]
Hello @aaron5670 
Glad to know this! We are working on it right now, should be release in v0.30.0 release
- first RC at the beginning of November
- official release is at the end of November!

**Comment by curquiza** [comment]
Spec created and added to the issue description: https://github.com/meilisearch/specifications/pull/192
