### ISSUE TITLE
Delete old processed tasks

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2751]
The goal of this issue is to reduce the users' friction with disk size management by allowing them to delete the old processed tasks.
Indeed, when accumulating a huge amount of tasks, the available size of the disk can be impacted drastically.
Deleting old tasks will allow the users to save some space again.

Related product discussion: https://github.com/meilisearch/product/discussions/517
Related spec: WIP

## TODO

- [ ] Work on PRD
- [ ] Create a prototype if needed
- [ ] Create the spec
- [ ] Implement the final version in the code and merge it into `main`

⚠️ Depends on scheduler refactoring https://github.com/meilisearch/meilisearch/issues/2725

## Impacted teams

@meilisearch/docs-team @meilisearch/integration-team 
Also @meilisearch/cloud-team, if I'm correct, you had issues with this!

**Comment by curquiza** [comment]
Fresh new spec, added to the issue description as well: https://github.com/meilisearch/specifications/pull/198/files
