### ISSUE TITLE
Stabilize the CLI

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2752]
The goal of this issue is to stabilize the CLI in order to provide a stable v1.

## TODO

- [ ] Follow related discussions and make final decision about them, see [central discussion](https://github.com/meilisearch/product/discussions/536)
- [ ] Solve each sub issues below

⚠️ Depends on scheduler refactoring https://github.com/meilisearch/meilisearch/issues/2725

## Changes

By order of prioritization
- [x] https://github.com/meilisearch/meilisearch/issues/3132
- [x] https://github.com/meilisearch/meilisearch/issues/3231

Only if we have the time, not a priority:
- [x] https://github.com/meilisearch/meilisearch/issues/3131

## Impacted teams

@meilisearch/docs-team @meilisearch/integration-team 
@meilisearch/cloud-team

**Comment by curquiza** [comment]
#3131 has been un-prioritized, see https://github.com/meilisearch/product/discussions/566#discussioncomment-4401077

**Comment by dureuill** [comment]
I had enough time to take a stab at #3131, see #3281

**Comment by dureuill** [comment]
Should we close this one?

**Comment by curquiza** [comment]
Yes indeed, closed since all the isses have been done 🎉
