### ISSUE TITLE
Improve language support by upgrading Charabia

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2769]
Following the following changes in the Meilisearch tokenizer ([charabia](https://github.com/meilisearch/charabia)), we need to ensure the latest version of Charabia is included in Meilisearch v0.30.0
- https://github.com/meilisearch/charabia/pull/126
- Improve the language support by integrating milli v0.38.0

# TODO

- [x] Implement changes in [Charabia](https://github.com/meilisearch/charabia/)
- [x] Release a Charabia version containing these changes
- [x] Bump this new Charabia version in [Milli](https://github.com/meilisearch/milli/) and merge it into `main`
- [X] Release a Milli version containing the new Charabia bump
- [X] Bump this new Milli version in Meilisearch and merge it into `main`

**Comment by curquiza** [comment]
Discussed with @ManyTheFish 
Not something we will have the time to integrate into v0.30.0 due to the huge works on the sprint + Hacktoberfest.

New charabia version will be done in v1!

**Comment by curquiza** [comment]
Closed by https://github.com/meilisearch/meilisearch/pull/3269
Already released in [v1.0.0-rc.0](https://github.com/meilisearch/meilisearch/releases/tag/v1.0.0-rc.0), will be released officially in v1.0.0
