### ISSUE TITLE
Create `too_many_open files` errors

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2785]
When Meilisearch opens too many FDs, you get the following error

```json
{
    "message": "An internal error has occurred. `Too many open files`.",
    "code": "internal",
    "type": "internal",
    "link": "https://docs.meilisearch.com/errors#internal"
}
```

We want to replace
- the code (not type) `internal` by `too_many_open_files`
- the link `#internal` by #too_many_open_files

## TODO

- [ ] Implement changes in [Milli](https://github.com/meilisearch/milli/)
- [ ] Release a Milli version containing these changes
- [ ] Bump this new Milli version in Meilisearch and merge it into `main`
- [ ] Update the [associated specification](https://github.com/meilisearch/specifications/blob/main/text/0061-error-format-and-definitions.md)

## Impacted teams

Pinging every teams that might use this, @meilisearch/docs-team (a [related issue](https://github.com/meilisearch/documentation/issues/1874)) and @meilisearch/integration-team 
Also @meilisearch/cloud-team I don't know if you would be impacted by this change

**Comment by semi-infiknight** [comment]
please assign me this issue

**Comment by curquiza** [comment]
Hello @semi-infiknight 

Thanks for your interest in this project 🔥 

FYI, we prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the volunteer contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](https://github.com/meilisearch/meilisearch-dotnet/blob/main/CONTRIBUTING.md).   

We are looking forward to reviewing your PR 😊

**Comment by Rutam21** [comment]
@curquiza Can you help me with finding the place where this change needs to be done? Thanks.

**Comment by irevoire** [comment]
Hey @Rutam21,

I think you'll need to add a variant in the [`Code`](https://github.com/meilisearch/meilisearch/blob/main/meilisearch-types/src/error.rs#L116-L173) to represent the error.
And then in the [`MilliError`](https://github.com/meilisearch/meilisearch/blob/main/meilisearch-lib/src/error.rs#L18-L55) enum you should look for every variant that can output a `TooManyOpenFiles` error and map it to the code you created before :+1:

**Comment by curquiza** [comment]
Moving this to v1 milestones, we will not have the time to fix it for v0.30.0

**Comment by brunoocasali** [comment]
@curquiza This is not a breaking change anymore based on the decision here https://github.com/meilisearch/engine-team/pull/38 right?

**Comment by curquiza** [comment]
It is still breaking because before people used the `internal` code to get this error, now they have to use `too_many_open_files`

The https://github.com/meilisearch/engine-team/pull/38 PR is about warning people using strong languages that would expect a specific and exhaustive list of types (here all the `code`). Indeed, if we add a new one in a new context (so not breaking) they will have their code broken because this new type is not expected. They have to include an `unknown` type in the exhaustive list they are expected to retrieve.

**Comment by brunoocasali** [comment]
Ah, ok, so it is because it is an "update/change", not a "creation", correct?

Because the issue name gave me the sensation that something new would be introduced, but yeah, carefully reading the content + your message made me get it :)

**Comment by curquiza** [comment]
Exactly. There is a nuance. In error handler, creation can also be a modification 😊
