### ISSUE TITLE
Delete documents by query parameters (with `filter`)

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2787]
Related to this product issue: https://github.com/meilisearch/product/issues/283

## Goals

Delete some documents based on a `filter` query string

## How it works?

When calling `DELETE /indexes/:uid/documents` the user should be able to pass a query parameter `filter`. The syntax of `filter` is exactly the same as we can use on the search side (with `POST/GET /indexes/:uid/search`), see the [associated docs](https://docs.meilisearch.com/learn/advanced/filtering_and_faceted_search.html#using-filters)

⚠️ for this first iteration, the fields used in `filter` should be set in `filterableAttributes`. This is something we might want to improve in another issue.

For example

```bash
curl \
  -X DELETE 'http://localhost:7700/indexes/movies/documents?filter=genre%3D%22horror%22
``` 

Which is the equivalent to `filter: "genre = horror"`

All the documents with `"genre": "horror"` will be deleted

#### About the deletion `tasks`

When calling the [`/tasks` endpoint](https://docs.meilisearch.com/reference/api/tasks.html#get-tasks), the user gets information about the deletion task processed by filtering.

We need to see the following information (an example with `books` index)

```json
{
            "uid": 1,
            "indexUid": "books",
            "status": "succeeded",
            "type": "documentDeletion",
            "details": {
                "deletedDocuments": 6,
                "receivedDocumentIds": 8,
                "filter": "genre = horror"
            },
            "duration": "PT0.008096800S",
            "enqueuedAt": "2022-09-22T15:11:07.7647005Z",
            "startedAt": "2022-09-22T15:11:07.770342Z",
            "finishedAt": "2022-09-22T15:11:07.7784388Z"
}
```
- `filter` fields has been added and contain the filter string
- `receivedDocumentIds` is the number of documents that matched the `filter` query when the request was applied
⚠️ If the following issue is solved (https://github.com/meilisearch/meilisearch/issues/2799), it means `receivedDocumentIds` has been renamed `matchedDocuments`

Both of these fields should not be present if no filter were given

#### Errors

- When sending an invalid syntax, the error sent should be the same we have when calling the `/search` route
- If the filter does not match any document, no documents are deleted, but no error are thrown. The request still returns the task information, and when getting the task information using the `/tasks` route, you will have the following details:
```
...
"details": {
     "deletedDocuments": 0,
     "receivedDocumentIds": 0,
     ...
 }
...
``` 

## TODO

- [ ] Implement this in Meilisearch: only this step is available for external contributions
- [ ] Release a prototype
- [ ] Correct the prototype following user's feedback
- [ ] Merge the final version on `main`
- [ ] Create a new spec about the feature

## Related teams

Pinging @meilisearch/integration-team and @meilisearch/docs-team FYI

----

Feel free to ask any questions to implement this issue. The core team is available to guide you through this contribution, even if it's your first one.
We recommend referring to the [CONTRIBUTING.md guidelines](https://github.com/meilisearch/meilisearch/blob/main/CONTRIBUTING.md), especially if it's your first contribution to this repository.
Thanks in advance for your involvement ❤️

**Comment by amab8901** [comment]
I think this issue is interesting, I'll try fixing it!

**Comment by curquiza** [comment]
Hello @amab8901,
thanks for your involvement, looking forward to reviewing your PR ❤️

**Comment by amab8901** [comment]
I noticed that `filter` query string works only for POST request currently, and not GET request. When you search, you don't use GET request. You only use POST request, and you're deciding what you want to create in the search results list. GET can only give you the entire database rather than selected parts of it, as of this writing.

**Comment by curquiza** [comment]
@amab8901 FYI even if you have found how to do it, it's currently possible with Meilisearch to do a search with `GET` and thus, having `filter` as query parameter (in the URL)

**Comment by amab8901** [comment]
I managed to reproduce the error in my Client API, and also managed to narrow down the relevant code to a handful of files in a single folder. This is my first open-source contribution so please excuse me if it takes a while to get it done.

**Comment by curquiza** [comment]
So cool you make your first contribution with us then! 😄 
Feel free to ask any question you need

**Comment by curquiza** [comment]
For everyone watching this issue, I've updated the issue to return the `filter` string in the task body!

**Comment by amab8901** [comment]
`meilisearch/meilisearch-http/tests/documents` seems to be the place where I should be editing, but I'm not really sure since this belongs to the `tests` folder rather than `src` folder. Can you confirm?

**Comment by amab8901** [comment]
`let (response, code) = index.get_document(0, None).await;`

I need to put `Option<GetDocumentOptions>` instead of `None` above. I'm trying to figure out how to put those options in there.

**Comment by ManyTheFish** [comment]
Hello @amab8901,
While trying to make suggestions about the implementation of the feature, we figured out that this would impact a lot of parts in the code, including:
- the HTTP server
- the task scheduler, which is currently completely rewritten by the core team that will imply painful merge conflicts
- the dumps, which is a "protected" part where we avoid external contributions

Moreover, speaking with the product manager, we are not satisfied with the proposed API design and we will probably change it.

We made a mistake by classifying it as a `good first issue` and as a `contribution accepted`, for now, we prefer closing this issue to refine it later.

We are sorry for this. 🙏

Thanks a lot for the time you spent on this issue, I hope to see you on another one! 😊

> poke @curquiza, @Kerollmops, and @gmourier

**Comment by amab8901** [comment]
no worries! If you're going to implement this kind of change though, I think you should first have a ticket that instruct people to add a test for the filtering of GET requests. I couldn't find any tests for filtering GET requests, and i'm surprised at this. I think you should add this and I really don't know how it's supposed to look like because I couldn't find any examples of filter option actually being tested/used in the code.

**Comment by curquiza** [comment]
Thanks @ManyTheFish, for the answer

And @amab8901, sorry for the confusion, indeed we were too optimistic.

**Comment by amab8901** [comment]
@curquiza I still think that there needs to be a test for the filtering feature on the GET document requests, so I'm working on figuring it out until I got it solved. I finally overcame the primary obstacle I had where I struggled to instantiate a struct. I finally figured out how to do it. Wow. Unbelievable.

**Comment by curquiza** [comment]
Just to be sure there is no lack of communication and no confusion: this is not a feature we want to develop now, so we won't accept any PR for this. We need to discuss it with the product team deeper. However, we don't give up on it, it's just we don't know yet HOW we want to provide the feature. So I don't recommend working on this issue because we don't expect what I described in the description for the API anymore 😊
