### ISSUE TITLE
Phrase search containing stop words never retrieve any documents

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2905]
Following: https://github.com/meilisearch/meilisearch/issues/2821

If an index has `stop_words` set in the settings, then, any Phrase search containing at least one stop word will return an empty response.

More information on this issue about how to fix it: https://github.com/meilisearch/milli/issues/661

## TODO

- [x] Implement changes in [Milli](https://github.com/meilisearch/milli/) -> Open to external contributors! Create a PR in the Milli repo fixing https://github.com/meilisearch/milli/issues/661
- [x] Release a Milli version containing these changes
- [ ] Bump this new Milli version in Meilisearch and merge it into `main`

----

Feel free to ask any questions to implement this issue. The core team is available to guide you through this contribution, even if it's your first one.
We recommend referring to the [CONTRIBUTING.md guidelines](https://github.com/meilisearch/meilisearch/blob/main/CONTRIBUTING.md), especially if it's your first contribution to this repository.
Thanks in advance for your involvement ❤️

**Comment by curquiza** [comment]
Closed by #3036
