### ISSUE TITLE
Allow wildcard (`*`) at the end of the index names when creating tenant tokens

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2908]
Following this product discussion: https://github.com/meilisearch/product/discussions/491#discussioncomment-3048342
Related to this spec: https://github.com/meilisearch/specifications/pull/189

## Goal

Allow using the wildcard `*` at the end of the index name (in `searchRules` field) when creating tenant tokens.

## How does it work?

To create a tenant token, you need to provide a `searchRules` field containing one or several index names.

```json
{
    "searchRules": {
        "medical_records": {
            "filter": "user_id = 1"
        },
        "medical_records_staging": {
            "filter": "user_id = 1"
        },     
    }
}
```

Also, the `*` is already allowing as following, meaning "all the indexes":

```json
{
    "searchRules": {
        "*": {
            "filter": "user_id = 1"
        }
    }
}
```

But the users need an intermediate usage of the `*` character: allowing to use the `*` character at the end of the index name.

Instead of passing:

```json
{
    "searchRules": {
        "medical_records": {
            "filter": "user_id = 1"
        },
        "medical_records_staging": {
            "filter": "user_id = 1"
        },     
    }
}
```

The users could pass:

```json
{
    "searchRules": {
        "medical_records*": {
            "filter": "user_id = 1"
        }
}
``` 

And this tenant will be available for all indexes matching `medical_records*`, so `medical_records` and `medical_records_staging` will match, but not `medical_record` (without `s`)

#### Errors

- if no indexes are matched, no error are thrown during the tenant token creation. However this token will be useless until a matching index is created

## Todo

- [ ] Implementation the changes by opening a PR in this repository -> open to external contributions. You can be inspired by [this PR](https://github.com/meilisearch/meilisearch/pull/2869)
- [X] Update the spec regarding this -> https://github.com/meilisearch/specifications/pull/189

## Impacted teams

Pinging @meilisearch/docs-team, but also @meilisearch/integration-team (I'm not sure for you)

**Comment by romilpunetha** [comment]
I'll try this.

**Comment by curquiza** [comment]
Hello @romilpunetha 

Thanks for your interest in this project 🔥 You are definitely more than welcome to open a PR for this!

FYI, we prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the volunteer contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](../blob/main/CONTRIBUTING.md).   

We are looking forward to reviewing your PR 😊

**Comment by romilpunetha** [comment]
I guess this will be solved by #2869 

https://github.com/meilisearch/meilisearch/pull/2869/files#diff-dcc74b1a4a3a3379bc76e7ce3fbbdd8f5092cec5cedc2bbeeb69ee769a24cd30R183

**Comment by curquiza** [comment]
@ManyTheFish can you confirm?

**Comment by curquiza** [comment]
Thanks @ManyTheFish, I've added it to the PR then

**Comment by curquiza** [comment]
@Kerollmops for this issue, what we need to do to finish it
- [ ] Merge this PR into a temp branch I've just created: `temp-wildcard`
- [ ] Continue the work by ensuring this issue is fixed
- [ ] Make @ManyTheFish as reviewer

**Comment by curquiza** [comment]
Hello everyone following this issue 👋 

We have just released the first RC (release candidate) of Meilisearch containing this new implementation!
You can test it by using
-  the [release assets](https://github.com/meilisearch/meilisearch/releases)
- the [Meilisearch Docker image](https://hub.docker.com/repository/docker/getmeili/meilisearch/general)
```bash
docker run -it --rm -p 7700:7700 -v $(pwd)/meili_data:/meili_data getmeili/meilisearch:v1.1.0-rc.0
```

You are more than welcome to communicate any feedback about this new implementation in [this discussion](https://github.com/meilisearch/product/discussions/491).
If you encountered any bugs, please report them [here](https://github.com/meilisearch/meilisearch/issues/new?assignees=&labels=&template=bug_report.md&title=).
Thanks in advance for your help and your involvement in Meilisearch ❤️ 

🎉 Official and stable release containing this change will be available on 3rd April 2023

⚠️ RC (release candidates) are not recommended for productionhttps://github.com/meilisearch/product/discussions/491
