### ISSUE TITLE
When importing a dump. Forward the date to milli.

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#2983]
When importing a dump we recreate all the milli indexes.
Since milli v0.35 it’s possible to specify a creation and last update date when opening a milli index.

---
# TODO

- [x] Implement changes in [Milli](https://github.com/meilisearch/milli/)
- [x] Release a Milli version containing these changes
- [x] Bump this new Milli version in Meilisearch and merge it into `main`

**Comment by waveywaves** [comment]
I would like to get assigned on this issue

**Comment by Kerollmops** [comment]
Hello @waveywaves, 

Thanks for your interest in this project 🔥 You are definitely more than welcome to open a PR for this!

For your information, we prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the volunteer contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](../blob/main/CONTRIBUTING.md).

**Comment by waveywaves** [comment]
@Kerollmops I understand :) Can you point me to documentation which would be helpful for me to get started on this issue ?

**Comment by irevoire** [comment]
Hey @waveywaves sorry for the delay I missed your message.
You can start looking at this code: https://github.com/meilisearch/meilisearch/blob/main/meilisearch-http/src/lib.rs#L267
The metadata contains the date. Thus you’ll need to update the `create_raw_index` method to add the possibility of specifying the date-time.
And then call the `new_with_datetime` or something function from milli instead of the simple `Index::new`.

**Comment by irevoire** [comment]
Hey @amab8901, since you've almost finished your PR on the geosearch, I was thinking that maybe you would be looking for something else to do.

This issue should be a good starter for a new contributor as well if you're looking for something else to do.
Then I'm afraid I don't have anything else fun to do :thinking: 
But if you want, I could ask the team on Monday :+1:

**Comment by amab8901** [comment]
> Hey @amab8901, since you've almost finished your PR on the geosearch, I was thinking that maybe you would be looking for something else to do.
> 
> This issue should be a good starter for a new contributor as well if you're looking for something else to do. Then I'm afraid I don't have anything else fun to do thinking But if you want, I could ask the team on Monday +1

thanks! I'll have a look at it after I finished my first PR on geosearch

**Comment by amab8901** [comment]
> `new_with_datetime` - is this an existing function, or do you want me to create a new function?

**Comment by irevoire** [comment]
Hey, this is an existing function, but it's on milli's side.

You can find it here; https://github.com/meilisearch/milli/blob/main/milli/src/index.rs#L143
And I was wrong about the name; it's called `new_with_creation_dates` instead of `new_with_datetime`.

**Comment by amab8901** [comment]
So here's what I need to do:
1. Look at this code (https://github.com/meilisearch/meilisearch/blob/main/meilisearch-http/src/lib.rs#L267)
2. Identify the date in the metadata
3. Update `create_raw_index` method to add the possibility to specify date-time
4. Call the `new_with_creation_dates` method (https://github.com/meilisearch/milli/blob/main/milli/src/index.rs#L143) instead of the simple `Index::new`

**Comment by irevoire** [comment]
Yes exactly!

**Comment by amab8901** [comment]
When you say that `Index::new` should be replaced, are you referring to this one? https://github.com/meilisearch/meilisearch/blob/2ed601760359abfac1f280de86a615ad572917c1/index-scheduler/src/lib.rs#L353-L407

**Comment by amab8901** [comment]
oh! So [this](https://github.com/meilisearch/milli/blob/main/milli/src/index.rs#L203-L206) is the one you're referring to as `Index::new`

**Comment by amab8901** [comment]
ok, so something is calling [this](https://github.com/meilisearch/milli/blob/main/milli/src/index.rs#L203), but it's supposed to call [this](https://github.com/meilisearch/milli/blob/main/milli/src/index.rs#L143) one instead. That's how I understood it.

**Comment by amab8901** [comment]
[This](https://github.com/meilisearch/meilisearch/blob/main/meilisearch-http/src/lib.rs#L280) one calls `create_raw_index`.

**Comment by irevoire** [comment]
Hey, `create_raw_index` currently calls `create_index`, which then calls `create_or_open_index`, which _finally_ calls `Index::new()`.

**Comment by amab8901** [comment]
for some reason, all the links we mentioned above lead to 404 "No page found" :thinking: Why is that the case?

**Comment by amab8901** [comment]
Just taking notes here:
[`create_index(...)`](https://github.com/meilisearch/meilisearch/blob/660be071b5fd5823fbd5d8095fd0600169889354/index-scheduler/src/index_mapper.rs#L77) calls [`create_or_open_index(...)`](https://github.com/meilisearch/meilisearch/blob/660be071b5fd5823fbd5d8095fd0600169889354/index-scheduler/src/index_mapper.rs#L69)

**Comment by amab8901** [comment]
ok I made some solid progress and it compiles. I look forward to your feedback before I do anything further.
