### ISSUE TITLE
Missing IN / NOT IN operator in the invalid_filter error message

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#3004]
**Describe the bug**
When sending an invalid filter, an error message explains all the filter operators but `IN` and `NOT IN` are missing.

```rust
{
  "message": "Was expecting an operation `=`, `!=`, `>=`, `>`, `<=`, `<`, `TO`, `EXISTS`, `NOT EXISTS`, or `_geoRadius` at `hemlo good doggo`.\n1:17 hemlo good doggo",
  "code": "invalid_filter",
  "type": "invalid_request",
  "link": "https://docs.meilisearch.com/errors#invalid_filter"
}
```

**Expected behavior**
`IN` and `NOT IN` should be listed.

This should be resolved on milli's side.

## TODO

- [x] Implement changes in [Milli](https://github.com/meilisearch/milli/) (only this step is available for external contribution) -> https://github.com/meilisearch/milli/pull/676
- [ ] Release a Milli version containing these changes
- [ ] Bump this new Milli version in Meilisearch and merge it into `main`

**Comment by Pranav-yadav** [comment]
@irevoire I can work on this :)

Could you point out which file/ lines of code need to be changed?

**Comment by irevoire** [comment]
Hey @Pranav-yadav, basically from what I see you need to update these two messages:

https://github.com/meilisearch/milli/blob/main/filter-parser/src/error.rs#L143-L148

**Comment by Pranav-yadav** [comment]
Got it. Thanks!

**Comment by Pranav-yadav** [comment]
@irevoire this PR https://github.com/meilisearch/milli/pull/676 should fix this issue :) Thanks.

**Comment by Pranav-yadav** [comment]
@curquiza should I try to complete the remaining tasks of these issue or is it just for tracking at your side?

**Comment by curquiza** [comment]
Hello @Pranav-yadav 

This is for tracking only on our side, only the first step is available for contribution! I'll make it more clear on the issue 😊 
thanks for asking!

**Comment by curquiza** [comment]
Closed by #3036
