### ISSUE TITLE
Search performance issues

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#3111]
(Issue description edited by @loiclec )

Some search queries are problematic because they use too much RAM or CPU time. Furthermore, we currently don't have any way to limit the number of simultaneous search queries being executed or to limit the time they are allowed to take. This can affect the stability of a Meilisearch instance. For v1, we'd like to resolve such issues in order to:

1. most importantly: prevent Meilisearch from exceeding its allocated memory budget (and therefore getting shut down unexpectedly)
2. ensure that search queries take a reasonable amount of time to execute

This is a meta-issue listing the potential areas of improvements. Note that there already exists an internal-only document about these issues [here](https://www.notion.so/meilisearch/v1-Search-crashes-performance-c9dcdf25472d49119275f3c206e22c40).

- [ ] https://github.com/meilisearch/meilisearch/issues/3126
- [x] https://github.com/meilisearch/meilisearch/issues/3115
- [x] https://github.com/meilisearch/meilisearch/issues/3116
- [x] https://github.com/meilisearch/meilisearch/issues/3118
- [ ] https://github.com/meilisearch/meilisearch/issues/3124
- [ ] https://github.com/meilisearch/meilisearch/issues/3123
- [x] https://github.com/meilisearch/meilisearch/issues/3125
- [ ] https://github.com/meilisearch/meilisearch/issues/3222

Current related issues
- https://github.com/meilisearch/meilisearch/issues/2966 (expected to be partly solved through a combination of the proposed changes)
- https://github.com/meilisearch/product/discussions/553 (expected to be only partly solved through a combination of the proposed changes)
- Crash of the "landing page" search bar observed on meilisearch.com a while ago (expected to be solved through the `MatchingWords` issue)
- https://github.com/meilisearch/meilisearch/issues/2202 (not expected to be solved unless the query tree is refactored)

**Comment by loiclec** [comment]
An update on the progress so far:

First, there is the issue of rate-limiting + search request timeout. This is probably the most important issue if we want to make meilisearch reliable under pressure and avoid being shut down due to excessive memory consumption:  https://github.com/meilisearch/meilisearch/issues/3126 . Note the last comment by kero, which gives a way forward to tackle the issue. However, this is not something that I am going to work on. Maybe @dureuill or @irevoire will have time to think about it/implement something?

Then:

1. We’ve removed a huge source of RAM consumption with a change in the data structure used by the search result highlighting logic: https://github.com/meilisearch/milli/pull/708 This change also protects meilisearch against certain malicious search queries that could consume gigabytes of memory.

2. Then, a few other PRs have been opened to address some worst-case scenarios leading to excessively long search times (measured in seconds or even minutes if unlucky):
* https://github.com/meilisearch/milli/pull/709 reduces the time of some queries with many (8-10) common words from multiple seconds to milliseconds
* https://github.com/meilisearch/milli/pull/732 changes the way we interpret multi-word synonyms (they are now treated as phrases: nyc -> "New York City" instead of loose words nyc -> New York City ) which protects meilisearch against queries containing many of these synonyms.
* https://github.com/meilisearch/milli/pull/733 avoids iterating over all the words starting with a certain prefix (which could be hundreds/thousands of words) inside the implementation of the proximity ranking rule. This change slightly degrades search results in some rare cases.

3. I have also started improving the search benchmarks such that (1) we can more reliably detect improvements/regressions in some search algorithms and (2) we benchmark more complex search queries that take a long time to execute. This is the draft PR: https://github.com/meilisearch/milli/pull/742 It will allow us to describe the impact of the search performance improvements more accurately.

There are a few other perf optimisations to be written, which I’ll try to implement this week and the next:
* https://github.com/meilisearch/meilisearch/issues/3222  affects the behaviour of the attribute  ranking rule and will also have a positive impact on the relevancy and the disk size of the index
* https://github.com/meilisearch/meilisearch/issues/3124 should be an easy win but the impact on performance is a bit of a mystery to me
* https://github.com/meilisearch/meilisearch/issues/3123 avoids precisely sorting documents when a search offset is given
That’s it for now :)

**Comment by curquiza** [comment]
Issue move to Milestones v1.1 since not everything has been done (it was expected, some issues require huge implementation and refactoring)
This issue (https://github.com/meilisearch/meilisearch/issues/2754) needs to be completed to ensure the good making of this current one. See [this comment](https://github.com/meilisearch/meilisearch/issues/2754#issuecomment-1386708536)

**Comment by loiclec** [comment]
Closing this issue in favour of https://github.com/meilisearch/meilisearch/issues/3547 , which supersedes it.
