### ISSUE TITLE
Add a new task when importing a dump

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#3162]
Related discussion: https://github.com/meilisearch/product/discussions/529
Related specification: WIP

We plan to add a new task to the task queue of Meilisearch when importing a dump. This will allow the users to check the `GET /tasks` route and be able to know when the dump import is over.

## TODO

- [ ] For implementation, check with the product squad to get how it should be implemented
- [ ] Merge the changes into `main`
- [ ] Update the specification

## Impacted teams
@meilisearch/docs-team @meilisearch/integration-team @meilisearch/cloud-team

**Comment by amab8901** [comment]
how can I reach the product squad?

**Comment by curquiza** [comment]
Hello @amab8901 

Product squads are internal and temporary product teams at Meili working on a specific user frustration in order to provide a solution.
You can reach them by discussing the product repository (see the discussion I linked in the issue). If you have a specific need or frustration and no discussion exists yet in the product repo, please open a [new one](https://github.com/meilisearch/product/discussions) 😊 

Also, to give more context, the `TODO` steps are information for the person solving the issue. Only internal Meili people are encouraged to do it.
Issues that are allowed to be solved by the community are issues labeled as `good first issue` and `contribution accepted` issues.

**Comment by curquiza** [comment]
Hello everyone here. This issue is not breaking (sorry for the `breaking change` tag I put previously, I was wrong) and regarding the time we have for the v1 sprint, we chose to decrease the priority of the issue. It will probably not be solved for v1, but later 😊

**Comment by brunoocasali** [comment]
@curquiza should we remove this issue from the milestone?

**Comment by curquiza** [comment]
I cannot 100% guarantee we will not have the time to do it, it will depend, that why I have not removed it yet.
However, for you, integration team, I don't recommend focusing on it first -> don't add it to your central issue, I will let you know if we succeeded in doing it, but to be honest I have doubt.

**Comment by curquiza** [comment]
Impossible to do it during the v1 sprint to prioritize other improvements.
