### ISSUE TITLE
Thread 'batch-operation' panicked at 'called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by gbuckingham89** [meilisearch/meilisearch#3165]
**Describe the bug**
We add documents to our index using the add / replace documents endpoint via the PHP SDK (`$index->addDocuments($documents)`).

We're sometimes seeing an error when indexing documents. We can queue a task OK, but it fails as follows:

- Error code: `internal`
- Error type: `internal` 
- Error message: `An unexpected crash occurred when processing the task`

Looking in the output, we're seeing the following error;

```
Nov 29 16:57:10 ctrlcloud-test-worker meilisearch[76928]: thread 'batch-operation' panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/.cargo/git/checkouts/milli-00376cd5db949a15/57c9f03/milli/src/update/facet/incremental.rs:136:46
```

This doesn't happen all the time. I've spent a few hours trying to identify a pattern, but can't seem to find one;

- Sometimes the error appears when adding documents for the first time to a new index
- Sometimes the error appears when re-indexing documents
- Sometimes after restarting `meilisearch` and re-running the indexing it completes successfully - and sometimes it doesn't
- Sometimes the error appears when performing searches at the same time as indexing - and sometimes it doesn't
- Sometimes the error appears when the searchable & filterable attributes are already defined in the index settings - and sometimes it doesn't

A few quick stats about our index that may or may not be helpful;

- When complete, we should have just over 171,000 documents 
- When complete, the stats endpoint returns a database size of 3.08GB
- Whilst they share many, not all documents have all attributes
- There are 179 filterable attributes
- There are 177 searchable attributes

We're currently running Meilisearch in AWS on a `t3.medium` instance, running `Ubuntu 22.04.1 LTS`.

I also run Meilisearch locally on a Macbook Pro (M1 Apple Silicon) but haven't been seen the issue there.

We didn't see this issue on previous versions (most recently `v0.29.2`) - but our dataset changes frequently (we usually re-index several times a day).

**To Reproduce**

Hard to reliably reproduce - see above.

**Expected behavior**
Be able to index documents without error.

**Meilisearch version:** v0.30.0

---

## TODO

- [x] Implement changes in [Milli](https://github.com/meilisearch/milli/) -> https://github.com/meilisearch/milli/pull/712
- [x] Release a Milli version containing these changes
- [ ] Bump this new Milli version in Meilisearch and merge it into `main`

**Comment by bergo** [comment]
Same behavior. Update documents, get the same error every time after it was raised for the first time.

Backtrace, meilisearch on ubuntu 22.04: 

`thread 'batch-operation' panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/.cargo/git/checkouts/milli-00376cd5db949a15/57c9f03/milli/src/update/facet/incremental.rs:136:46
stack backtrace:
   0:     0x561b3b380630 - std::backtrace_rs::backtrace::libunwind::trace::h32eb3e08e874dd27
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x561b3b380630 - std::backtrace_rs::backtrace::trace_unsynchronized::haa3f451d27bc11a5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x561b3b380630 - std::sys_common::backtrace::_print_fmt::h5b94a01bb4289bb5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x561b3b380630 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb070b7fa7e3175df
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x561b3b3a584e - core::fmt::write::hd5207aebbb9a86e9
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/fmt/mod.rs:1202:17
   5:     0x561b3b37a495 - std::io::Write::write_fmt::h3bd699bbd129ab8a
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/io/mod.rs:1679:15
   6:     0x561b3b381ce3 - std::sys_common::backtrace::_print::h7a21be552fdf58da
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x561b3b381ce3 - std::sys_common::backtrace::print::ha85c41fe4dd80b13
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x561b3b381ce3 - std::panicking::default_hook::{{closure}}::h04cca40023d0eeca
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:295:22
   9:     0x561b3b3819cf - std::panicking::default_hook::haa3ca8c310ed5402
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:314:9
  10:     0x561b3b38238a - std::panicking::rust_panic_with_hook::h7b190ce1a948faac
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:698:17
  11:     0x561b3b382241 - std::panicking::begin_panic_handler::{{closure}}::hbafbfdc3e1b97f68
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:586:13
  12:     0x561b3b380adc - std::sys_common::backtrace::__rust_end_short_backtrace::hda93e5fef243b4c0
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x561b3b381fa2 - rust_begin_unwind
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
  14:     0x561b3a7e8763 - core::panicking::panic_fmt::h8d17ca1073d9a733
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
  15:     0x561b3a7e862d - core::panicking::panic::hf0565452d0d0936c
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
  16:     0x561b3afa6a45 - milli::update::facet::incremental::FacetsUpdateIncrementalInner::find_insertion_key_value::h5998f09af512010c
  17:     0x561b3afa6c1a - milli::update::facet::incremental::FacetsUpdateIncrementalInner::insert_in_level::hb430fcda4ca0fbef
  18:     0x561b3afa6baf - milli::update::facet::incremental::FacetsUpdateIncrementalInner::insert_in_level::hb430fcda4ca0fbef
  19:     0x561b3afa6baf - milli::update::facet::incremental::FacetsUpdateIncrementalInner::insert_in_level::hb430fcda4ca0fbef
  20:     0x561b3afa6baf - milli::update::facet::incremental::FacetsUpdateIncrementalInner::insert_in_level::hb430fcda4ca0fbef
  21:     0x561b3afa8973 - milli::update::facet::incremental::FacetsUpdateIncrementalInner::insert::he4387bdd220708dc
  22:     0x561b3afac56a - milli::update::facet::FacetsUpdate::execute::h0e2ed3519a272b06
  23:     0x561b3afbfb79 - milli::update::index_documents::typed_chunk::write_typed_chunk_into_index::h506f32e58fa4c0c1
  24:     0x561b3ad3eed8 - milli::update::index_documents::IndexDocuments<FP,FA>::execute::hd968744b1a7ca29f
  25:     0x561b3ad9f4db - index_scheduler::batch::<impl index_scheduler::IndexScheduler>::apply_index_operation::h3b4f123234badfe8
  26:     0x561b3ad9674b - index_scheduler::batch::<impl index_scheduler::IndexScheduler>::process_batch::h39b3eea89051395f
  27:     0x561b3acf9c81 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8a73d304b98048f0
  28:     0x561b3acfcfb9 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h9e0fd82c8b02b68d
  29:     0x561b3b386ba3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h49f797984e2121bf
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
  30:     0x561b3b386ba3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hfa4f3d0ee6440e0b
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
  31:     0x561b3b386ba3 - std::sys::unix::thread::Thread::new::thread_start::h62ca48b42d48a8fc
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys/unix/thread.rs:108:17
  32:     0x7ff8b8c1fb43 - <unknown>
  33:     0x7ff8b8cb1a00 - <unknown>
  34:                0x0 - <unknown>`

**Comment by gbuckingham89** [comment]
I see there is now a fix pending in meilisearch/milli#712 - but just to confirm what @bergo said above - our latest test is behaving in the same way - once the error appears, all future indexing attempts fail with the same error.

**Comment by curquiza** [comment]
Hello everyone, sorry for the late update
We are working on this issue right now, and we will release v0.30.1 containing this fix as soon as possible 😊

**Comment by curquiza** [comment]
Fixed by #3202, will be released in v0.30.1 today!
