### ISSUE TITLE
Versioning policy guide for v1

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#3191]
This issue is only for traceability regarding an internal process of the @meilisearch/engine-team. Nothing to implement on the code base side, only to let you know and be transparent.

Since Meilisearch plans to release v1 in February 2023, we need to define and clarify what the engine team considers as a breaking change to handle their version of Meilisearch in a consistent way.

## Steps

- [X] Discussion with the engine team
- [X] Write [the guide](https://www.notion.so/meilisearch/Versioning-policy-0a1bdb012a274a5d8116b9cbd2031c77) on Notion, for a first draft (internal link only)
- [X] Make it reviewed by the Meili people, not only the engine team
- [x] Put the guide on GitHub, in the [engine-team repo](https://github.com/meilisearch/engine-team) -> https://github.com/meilisearch/engine-team/pull/36
- [ ] Define with the docs if some information should be put on the docs, and how
- [ ] If yes, write the guide on the docs side

**Comment by curquiza** [comment]
Closed in favor of https://github.com/meilisearch/documentation/issues/2113, since the job is now on the docs side
