### ISSUE TITLE
New process for experimental features after v1 (API-breaking features)

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#3192]
This issue is only for traceability regarding an internal process of the @meilisearch/engine-team. Nothing to implement on the code base side (except maybe some CIs and automation), this issue is only to let you know and be transparent.

Since Meilisearch plans to release v1 in February 2023, Meilisearch will not be able to break their API to each release, but only for each major release, which is planned to be exceptional.
It means we need to provide features to the users where we cannot guarantee the API will not change: we want to provide "unstable" features regarding the API.
The purpose is to make the feature test by the maximum number of users before making a final decision about how the API should be for the related feature. This way, the feature will pass from the "beta" state to "stable".

## Steps

- [x] Discuss with product teams (open-source and cloud) about the needs they have regarding the beta features.
- [x] Define what could be done technically (not regarding git) with the engine team
- [x] Define how we handle this process regarding git
- [x] Write the first guide draft on Notion
- [x] Check with other teams (@meilisearch/integration-team, @meilisearch/docs-team and @meilisearch/cloud-team) if the process is valid and can be integrated into their own scope. Beta feature process is not only about doing it on the engine side.
- [x] Ensure everyone reviews it
- [x] Put the guide on GitHub, in the [engine-team repo](https://github.com/meilisearch/engine-team) -> https://github.com/meilisearch/engine-team/pull/44
- [x] All the teams (including engine team) integrate the new process into their own scope according to what we defined

## Impacted teams

Pinging @meilisearch/integration-team, @meilisearch/docs-team and @meilisearch/cloud-team since you are really concerned by this issue. Be sure I will come to you when necessary.

**Comment by curquiza** [comment]
The work is moving forward regarding this but will not be ready for v1.0.0.
No experimental features are planned for v1, this issue can be reported to the next sprints

**Comment by curquiza** [comment]
The [draft work](https://www.notion.so/meilisearch/Experimental-features-085a53ac263744aba78f07b238dc67bf) (internal link) done by the engine team has been communicated to the other teams for a review

**Comment by curquiza** [comment]
We will provide our first experimental feature in v1.1 with the `metrics` route: https://github.com/meilisearch/meilisearch/issues/3523

**Comment by curquiza** [comment]
I can close this issue since
- ths guide is now available: https://github.com/meilisearch/engine-team/blob/main/resources/experimental-feature.md
- we are doing our first experimental feature in v1.1. Here is the [product discussion](https://github.com/meilisearch/product/discussions/625) about it
