### ISSUE TITLE
New process for deprecated features after v1

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#3193]
This issue is only for traceability regarding an internal process of the @meilisearch/engine-team. Nothing to implement on the code base side, only to let you know and be transparent.

Since Meilisearch plans to release v1 in February 2023, Meilisearch will not be able to break their API to each release, but only for each major release, which is planned to be exceptional.
It means we need to help the users do their migration between each major of Meilisearch. A good practice is to provide a deprecated feature process to the users, i.e. a "warning" to let them know the feature they are using will disappear in a future version.

## Steps

- [ ] Find some good external practices, and based on this, suggest some first rules on a draft
- [ ] Define what could be done technically (not regarding git) with the engine team
- [ ] Define how we handle this process regarding git (if needed)
- [ ] Check with other teams (@meilisearch/integration-team, @meilisearch/docs-team and @meilisearch/cloud-team) if the process is valid and can be integrated into their own scope. Deprecated feature process is not only about doing it on the engine side.
- [ ] Write the first guide draft on Notion
- [ ] Ensure everyone reviews it
- [ ] Put the guide on GitHub, in the [engine-team repo](https://github.com/meilisearch/engine-team)
- [ ] All the teams (including engine team) integrate the new process into their own scope according to what we defined

## Impacted teams

Pinging @meilisearch/integration-team, @meilisearch/docs-team and @meilisearch/cloud-team since you are really concerned by this issue. Be sure I will come to you when necessary.

**Comment by curquiza** [comment]
No absolute need for v1.0 release, the work will continue to the next sprint
