### ISSUE TITLE
Exhaustive search with page/hitsPerPage functionality shows different counts on each page

### ISSUE THREAD

**Issue by mmachatschek** [meilisearch/meilisearch#3200]
**Describe the bug**
I wasn't able to test v0.30 until now but for me, using `page` and `hitsPerPage` do not show an exhaustive number of hits.

using different values of page and hits per page show different numbers on the `totalHits`.

Check this (the index data is not changing while testing):

(page: 0, hitsPerPage 10, results: 2539)
![image](https://user-images.githubusercontent.com/10237069/205693917-077e0e5a-e054-4314-a3b0-0973379be287.png)

(page: 1, hitsPerPage 10, results: 2531)
![image](https://user-images.githubusercontent.com/10237069/205694198-7688101e-5cbe-44dc-968c-adfa41a06c3b.png)

(page 1, hitsPerPage 20, results: 2510)
![image](https://user-images.githubusercontent.com/10237069/205694418-71760222-0d69-4896-9f08-468631891606.png)

(page 2, hitsPerPage 10, results: 2510)
![image](https://user-images.githubusercontent.com/10237069/205694564-545d03d9-d3c8-464b-bc13-f9a2716959cc.png)

(page 2, hits per Page 20, results: 2479)
![image](https://user-images.githubusercontent.com/10237069/205694734-ab73d71d-6394-4871-887a-de703717cdf1.png)

**To Reproduce**
I have a dataset which I can share privately (e.g. via discord) where you can reproduce this as shown in the screenshots

**Expected behavior**
The `totalHits` count should not change

**Meilisearch version:** v0.30.0

**Additional context**
The index uses the distinctAttribute feature

This is a copy of my comment on https://github.com/meilisearch/product/discussions/335#discussioncomment-4315189

----

## TODO
- [x] Implement changes in [Milli](https://github.com/meilisearch/milli/) -> https://github.com/meilisearch/milli/pull/729
- [x] Release a Milli version containing these changes
- [x] Bump this new Milli version in Meilisearch and merge it into `release-v0.30.2`

**Comment by curquiza** [comment]
Hello @mmachatschek 

Thanks for the report, @ManyTheFish, can you take a look at it?

**Comment by freescout-helpdesk** [comment]
Same issue here.

**Comment by freescout-helpdesk** [comment]
Few more observations which may be helpful (the index uses the `distinctAttribute` feature):

1) The closer the requested page to the end the more accurate is the `totalHits` value.

2) Same thing happens with `estimatedTotalHits` when `limit` & `offset` are used.

**Comment by curquiza** [comment]
Hello everyone, @ManyTheFish has succeeded to reproduce the bug and is working on it! 😊

**Comment by curquiza** [comment]
Fixed by #3217, will be released today in v0.30.2

**Comment by freescout-helpdesk** [comment]
Awesome. Thanks for the quick fix.

It works fine when "q" is specified. But if "q" is an empty string the issue still persists.

**Comment by curquiza** [comment]
Thanks for the feedback @freescout-helpdesk 
@ManyTheFish can you take a look at it again? 😊

**Comment by mmachatschek** [comment]
unfortunately for me the issue wasn't solved with the update :/ 

here you can see the difference from the first to the last page (500 results off)

(tested this with the index that has a distinct attribute set, the exhaustive count of the non distinct indexes are correct)

(page 0, hitsPerPage 10, totalHits 2582)
<img width="342" alt="image" src="https://user-images.githubusercontent.com/10237069/206839683-3fddb2b4-b506-45d6-b57a-0ea74a28b06b.png">

(page 1, hitsPerPage 10, totalHits 2579)
<img width="374" alt="image" src="https://user-images.githubusercontent.com/10237069/206839887-4b27f57d-146f-42c7-b20d-cbd7a7c8fd19.png">


(page 207, hitsPerPage 10, totalHits 2070)
<img width="405" alt="image" src="https://user-images.githubusercontent.com/10237069/206839830-394e85d3-4064-47bf-85ee-ec225f8a8870.png">


actually it got worse, based on @freescout-helpdesk I tried to do searches with a query to verify his finding but for my index, meilisearch even stoped to count totalPages and counting the hits. (check screenshots) 

This issue arises for all indexes

with a query (get results, no pages count, not totalhits count)
<img width="489" alt="image" src="https://user-images.githubusercontent.com/10237069/206839483-59fb3e4d-4dba-4650-9149-d08744a86271.png">

**Comment by curquiza** [comment]
Closed by #3248 
Will be released in v0.30.3 by the end of the week

**Comment by mmachatschek** [comment]
Hi @curquiza 

sorry to disturb everyone here :smiling_face_with_tear: but for me on the latest docker tag v0.30.3, the error persists. I still don't have an exhaustive count on my searches (only if I do NOT specify a search term)

(with query term, correct calculation of totalHits)
![image](https://user-images.githubusercontent.com/10237069/207655126-e2957953-a470-488d-b45a-27f78e62654d.png)

(no query term, wrong calculation of totalHits)
![image](https://user-images.githubusercontent.com/10237069/207655287-7e080b75-430a-424a-9ec2-8868bd95e790.png)

(no query term, should be last page, real last page would have been 2283 with 22823 total pages)
![image](https://user-images.githubusercontent.com/10237069/207655712-96662b34-e536-4341-91ba-e0dee65ced65.png)

**Comment by curquiza** [comment]
Don't be sorry @mmachatschek, we are.
We will work on this tomorrow

**Comment by ManyTheFish** [comment]
Hello @mmachatschek, I am really sorry for this set of bugs about finite pagination.
I think the next patch would be the last, however, in order to avoid reproducing the same mistake again and again, I put below the branch of Meilisearch containing the fix allowing anyone to double or even triple-check the changes:
https://github.com/meilisearch/meilisearch/tree/test-fix-on-finite-pagination

If you have Rust, you can pull the repository, checkout on the branch, and run Meilisearch with any dump using:
```bach
$ cargo run --release -- --import-dump=path/to/dump.dump
```

Again, sorry for the loss of time and thank you for your patience. 🙏

**Comment by mmachatschek** [comment]
@ManyTheFish no need to say sorry!

The `test-fix-on-finite-pagination` branch works locally 👍 I can confirm the bug is fixed for me 🎉 

![image](https://user-images.githubusercontent.com/10237069/207796255-84d52ce1-e9ed-476b-b695-36bd2091a00b.png)

![image](https://user-images.githubusercontent.com/10237069/207796362-762cb73a-47b0-406e-8274-b18a3c029f41.png)

**Comment by curquiza** [comment]
Fixed by #3258 and will definitely be integrated to meilisearch when we will release v0.30.4 today
Sorry again for the inconvenience!

**Comment by freescout-helpdesk** [comment]
We can confirm - it works fine now. Thanks.
