### ISSUE TITLE
totalHits/estimatedTotalHits are not calculated if query is used

### ISSUE THREAD

**Issue by mmachatschek** [meilisearch/meilisearch#3228]
**Describe the bug**
On meilisearch v0.30.2 the calculation of `totalHits` and `estimatedTotalHits` outputs a value of `0` if a query is being used.

The bug is reproducible with both the new pagination params and the existing offset/limit

**To Reproduce**
1. Search for some query `a`
2. See results in response `hits`
3. estimatedTotalHits/totalHits returns `0`

**Expected behavior**
Number of documents matched (either estimated or exhaustive)

**Screenshots**
<img width="364" alt="image" src="https://user-images.githubusercontent.com/10237069/206840879-aebe79b1-1321-4fcc-a406-681070bba3d0.png">

<img width="440" alt="image" src="https://user-images.githubusercontent.com/10237069/206840845-49317104-8e0d-4cab-ad15-5deea7ad97dc.png">

**Meilisearch version:** v0.30.2

---

# TODO
- [x] Implement changes in [Milli](https://github.com/meilisearch/milli/) -> meilisearch/milli#737
- [ ] Release a Milli version containing these changes
- [ ] Bump this new Milli version in Meilisearch and merge it into `release-v0.30.3`

**Comment by curquiza** [comment]
Hello @mmachatschek 
Sorry for this, we will create a new release as soon as possible.

@ManyTheFish can you check this?

**Comment by curquiza** [comment]
Closed by https://github.com/meilisearch/meilisearch/pull/3248
Will be released in v0.30.3 by the end of the week
