### ISSUE TITLE
Change the primary key inference

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#3233]
PRD (internal link): https://www.notion.so/meilisearch/Robustify-Primary-Key-Inference-fb2fbbdf91f84453bfbc0318d05cc6b0
Product discussion: https://github.com/meilisearch/product/discussions/206

The current Meilisearch primary key inference is sometimes confusing for our users. We want to keep Meilisearch inferring the primary key, but change the behavior to make it consistent and follow the JSON specification as well.

## TODO
- [ ] Define the final solution with the product squad
- [ ] Implement changes in [Milli](https://github.com/meilisearch/milli/)
- [ ] Release a Milli version containing these changes
- [ ] Bump this new Milli version in Meilisearch and merge it into `main`
- [ ] Update the specification

## Impacted teams

@meilisearch/integration-team @meilisearch/docs-team

**Comment by curquiza** [comment]
Closed by #3269
