### ISSUE TITLE
Reject master keys with a size lower than 16 bytes

### ISSUE THREAD

**Issue by dureuill** [meilisearch/meilisearch#3272]
Product discussion: https://github.com/meilisearch/product/discussions/538

Reject master keys that are shorter than 16 bytes, as they can be guessed very easily.

## TODO
- [ ] Define the final solution in the product discussion
- [ ] Implement the restriction in Meilisearch
- [ ] Update the specification

## Impacted teams

@meilisearch/integration-team @meilisearch/docs-team
