### ISSUE TITLE
Last API bugs for the v1.0.0

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#3352]
# Hard bugs that must be fixed for v1.0.0

- [x] #3371
- [x] #3385
- [x] #3384
- [x] #3354
- [x] #3368
- [x] #3369
- [x] #3374
- [x] #3005
- [x] #3003
- [x] #3414
- [x] #3201

# Confusing things that _should_ be fixed v1.0.0 but are not breaking or bugs
- [x] #3390
- [x] #3391
- [x] #3394
- [x] #3381
- [x] #3392

# Improvements that can be implemented after v1.0.0
- [x] #3400
- [ ] If I try to filter on `_geo(x, y, z)` we should trigger the special reserved keywords error 
- [ ] If I try to filter on `_geoDistance(x, y, z)` we should trigger the special reserved keywords error 
- [ ] If I try to sort on `_geoRadius(x, y)` we should trigger the special reserved keywords error 
- [ ] If I try to sort on `_geo(x, y)` we should trigger the special reserved keywords error 
- [ ] If I try to sort on `_geoDistance(x, y)` we should trigger the special reserved keywords error
