### ISSUE TITLE
Return stats for numerical facets like `min`, `max`

### ISSUE THREAD

**Issue by dureuill** [meilisearch/meilisearch#3426]
Related product discussion: https://github.com/meilisearch/product/discussions/117
Related specification: WIP
Also related to: https://github.com/meilisearch/instant-meilisearch/issues/926

### TODO

- [ ] For implementation, check with the product squad to get how it should be implemented
    - A prototype PR with only `min` and `max` is available: #3423. Do we need `avg` and `sum`?
- [ ] Merge the changes into main
- [ ] Update the specification

### Impacted teams

@meilisearch/integration-team: usable for https://github.com/meilisearch/instant-meilisearch/issues/926
@meilisearch/docs-team

**Comment by dureuill** [comment]
Removing avg from the title as it won't make the first iteration planned for v1.

**Comment by curquiza** [comment]
Hello everyone following this issue 👋 

We have just released the first RC (release candidate) of Meilisearch containing this new implementation!
You can test it by using
-  the [release assets](https://github.com/meilisearch/meilisearch/releases)
- the [Meilisearch Docker image](https://hub.docker.com/repository/docker/getmeili/meilisearch/general)
```bash
docker run -it --rm -p 7700:7700 -v $(pwd)/meili_data:/meili_data getmeili/meilisearch:v1.1.0-rc.0
```

You are more than welcome to communicate any feedback about this new implementation in [this discussion](https://github.com/meilisearch/product/discussions/117).
If you encountered any bugs, please report them [here](https://github.com/meilisearch/meilisearch/issues/new?assignees=&labels=&template=bug_report.md&title=).
Thanks in advance for your help and your involvement in Meilisearch ❤️ 

🎉 Official and stable release containing this change will be available on 3rd April 2023

⚠️ RC (release candidates) are not recommended for production
