### ISSUE TITLE
Perform multiple searches in a single query

### ISSUE THREAD

**Issue by dureuill** [meilisearch/meilisearch#3427]
Related product discussion: https://github.com/meilisearch/product/discussions/489
Related specification: WIP

### TODO

- [ ] For implementation, check with the product squad to get how it should be implemented
    - A prototype PR is available: #3417
- [ ] Merge the changes into main
- [ ] Update the specification

### Impacted teams

- @meilisearch/integration-team
- @meilisearch/docs-team: new endpoint to document.

**Comment by dureuill** [comment]
Remaining identified topics to address (in the open PR or in a subsequent PR):

- Tests tenant tokens with multi search. As the PR is doing the same check as the regular search, I expect it will offer the same protection, but this needs explicit tests in the code.
- Handle error cases on the index name. Currently the case were the index name does not exist is correctly handled, but we possibly want special handling when:
  - The passed name is an illegal index name
  - There is not `indexUid` in one query.
- Should we tell which query is responsible for the error when we return an error?

**Comment by dureuill** [comment]
Opened the specification PR: https://github.com/meilisearch/specifications/pull/225

The issue description is up to date

**Comment by curquiza** [comment]
Hello everyone following this issue 👋 

We have just released the first RC (release candidate) of Meilisearch containing this new implementation!
You can test it by using
-  the [release assets](https://github.com/meilisearch/meilisearch/releases)
- the [Meilisearch Docker image](https://hub.docker.com/repository/docker/getmeili/meilisearch/general)
```bash
docker run -it --rm -p 7700:7700 -v $(pwd)/meili_data:/meili_data getmeili/meilisearch:v1.1.0-rc.0
```

You are more than welcome to communicate any feedback about this new implementation in [this discussion](https://github.com/meilisearch/product/discussions/489).
If you encountered any bugs, please report them [here](https://github.com/meilisearch/meilisearch/issues/new?assignees=&labels=&template=bug_report.md&title=).
Thanks in advance for your help and your involvement in Meilisearch ❤️ 

🎉 Official and stable release containing this change will be available on 3rd April 2023

⚠️ RC (release candidates) are not recommended for production
