### ISSUE TITLE
Use ubuntu instead of alpine in Docker image

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#3504]
Discussed with @dureuill 

Currently, in our [Dockerfile](https://github.com/meilisearch/meilisearch/blob/main/Dockerfile), we use the alpine image as a base.

We spotted multi potential issues we could have in the future, and here is why we would rather use the ubuntu/debian image:
- Meilisearch is a program doing a lot of system calls and then highly depends on the platform where it runs: we don't run any integration tests with Alpine, and even if it's a Linux distribution, we definitely better know the Ubuntu and Debian usages than Alpine
- a lot of users use our docker image, especially @meilisearch/cloud-team. Perfectly knowing the edge cases of the docker use case is more and more mandatory. Engine team would be more confident with a debian or ubuntu image, since it's what we test every day.
- Alpine uses a musl glic binary, and of course, Meilisearch uses glic a lot -> this musl version of the glibc can bring latency (not verified yet) but also edge cases we cannot identify now.

For all these reasons, we would rather use an ubuntu or debian image to build our own Meilisearch image at top of it

## TODO

- [ ] Test with Debian or Ubuntu instead of Alpine
  - [ ] Is the size of the image still correct?
  - [ ] Give a prototype to the cloud team, and wait for their approval -> is it working as previously?
- [ ] Implement the changes

## Impacted team

@meilisearch/cloud-team

**Comment by curquiza** [comment]
Some update: we will not use ubuntu because there is not official [rust docker image](https://hub.docker.com/_/rust) with ubuntu

**Comment by curquiza** [comment]
The current prototype you can use to test the new image is

```bash
docker run -it --rm -p 7700:7700 -v $(pwd)/meili_data:/meili_data getmeili/meilisearch:prototype-debian-docker-image-0
```

Please let me know here if anyone has any issue with it 🙏

**Comment by mmachatschek** [comment]
@curquiza I support this change, but it may happen that users are extending the docker image in their own dockerfile. So this may lead to a breaking change.

e.g.

```Dockerfile
FROM getmeili/meilisearch:1.0.0

RUN ...do some stuff \
         && apk run some alpine specific command
```

A workaround would be to build for debian and alpine and tag the images accordingly

```
# docker tag
getmeili/meilisearch:1.0.0 === getmeili/meilisearch:1.0.0-alpine
```

```
# docker tag
getmeili/meilisearch:1.0.0-debian <= new debian image
```

**Comment by curquiza** [comment]
Hum you are right that's true, it can be breaking for the users...
And I'm not really happy with having two dockerfile + tagging every Meilisearch image in double.

**Comment by curquiza** [comment]
@dureuill what do you think?

**Comment by dureuill** [comment]
We're moving away from alpine because of its use of musl as libc, which is thought to potentially affect performance, and could cause issues specific to this libc implementation.

This change is made to be consistent with what we're testing day to day. With regards to these motivations I don't think it makes sense to make this change if we're going to keep supporting both docker variants.

As a result I think the solutions that make sense currently are **either**:

1. commit to make musl supported instead of glibc. Don't provide a debian image, *or*
2. make the breaking change by switching to the debian image and stop providing the musl image, with a note in the changelogs of v1.x about the breakage.

To help us decide it would be good to have some measure of how many people and CIs would be impacted by that change. Is extending the Meilisearch docker image common? What are the typical use-cases?

**Comment by curquiza** [comment]
> Is extending the Meilisearch docker image common?

I guess it can concern a lot of people since it's quite common in the Docker world to create an image based on another one. It's all the "power" of Docker. But I don't know how many people are concerned for Meilisearch specifically. I know the cloud team is doing it for example and would have to change their Dockerfile because of this change

**Comment by curquiza** [comment]
However, in Semver, changing a dependency is not considered as breaking, I don't know if [the rule](https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api) is exactly related to our situation
We added a rule about this in [our versioning policy](https://github.com/meilisearch/engine-team/blob/main/resources/versioning-policy.md#-some-precisions)

**Comment by mmachatschek** [comment]
@dureuill 

to be clear here, I totally support this change.

We were also running alpine images with a node application that uses prisma (it's written in rust under the hood). Alpine slowed down our application a lot and switching to the debian based images gave us a lot of performance back. there are some GH issues and blog posts that confirm this.

These articles made me switch to the debian image because the main reason (small image size) was irrelevent when we switched to the debian-slim versions

- https://pythonspeed.com/articles/alpine-docker-python/
- https://snyk.io/blog/choosing-the-best-node-js-docker-image/#:~:text=Is%20node%3Aalpine%20the,Python%20Docker%20images.

> Is extending the Meilisearch docker image common? What are the typical use-cases?

when the meilisearch batch feature was opt in, we created a meilisearch dockerfile that just changed the command and added the cli flag to activate it. But there was no alpine specific code involved. This could have been solved via a docker-compose command config too (without needing to add a dockerfile)

Those results look like most people don't use any alpine specifc commands in their dockerfile
https://github.com/search?l=Dockerfile&q=getmeili%2Fmeilisearch&type=Code

These were the only usages that I could find that apply some alpine specific commands (and where the dockerfile uses the latest tag)

- https://github.com/darkjinnee/web-stack/blob/main/docker/services/meilisearch/Dockerfile
- https://github.com/darkjinnee/larapack-9x/blob/main/docker/services/meilisearch/Dockerfile
- https://github.com/edouardb/meilisearch-on-koyeb/blob/main/Dockerfile

> 2. make the breaking change by switching to the debian image and stop providing the musl image, with a note in the changelogs of v1.x about the breakage.

preferred +1

**Comment by dureuill** [comment]
@mmachatschek thank you so much this is a great answer ❤️ 

I thought we linked articles on musl performance somewhere but couldn't find them back after a cursory search, so thank you for contributing some of them.

> These were the only usages that I could find that apply some alpine specific commands (and where the dockerfile uses the latest tag)

Thank you for the search! Since this appears to be a manageable number of cases, I guess we could even send advance notice to these repositories before making the change.

**Comment by curquiza** [comment]
Thanks a lot @mmachatschek for your help here

I talked with @dureuill and because of the change, we would rather not release it before measuring it: we want to ensure this change has a real impact on performance to deserve a breaking change on one of our tools. Even if the breaking change is not in the search engine directly, the docker image is still a widely used tool.
I've updated the issue description. I ping @meilisearch/cloud-team about the change.
