### ISSUE TITLE
Customize text separator

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#3610]
Related product team resources: [roadmap card](https://www.notion.so/meilisearch/ef7d86c80ef44c549e2361c70a367723?v=d11906bcef8b4b77815f84b801931c00&p=36d7f85c7eee465e950f92427e791738&pm=s)  (_internal only_)
Related spec: https://github.com/meilisearch/specifications/pull/254
Related product discussions:
- https://github.com/meilisearch/product/discussions/468
- https://github.com/meilisearch/product/discussions/160
- https://github.com/meilisearch/product/discussions/260
- https://github.com/meilisearch/product/discussions/381
- https://github.com/meilisearch/product/discussions/95

## Motivation

Adapts Meilisearch to specific term nomenclature and thus cover more use cases by adding customization to the engine.

Make Meilisearch more **customizable** and **adaptable** to different types of data set content and, therefore, different use cases by letting them configure the separators to be indexed.

More information present in the [product internal document](https://www.notion.so/meilisearch/ef7d86c80ef44c549e2361c70a367723?v=d11906bcef8b4b77815f84b801931c00&p=36d7f85c7eee465e950f92427e791738&pm=s).

## Usage

Refer to the final spec to know the detail of the usage.

## TODO

- [x] Implement changes in [Charabia](https://github.com/meilisearch/charabia/)
- [x] Release a Charabia version containing these changes
- [x] Bump this new Charabia version in Meilisearch and merge it into `main`
- [x] Add the new setting in Meilisearch to customize text separator (ensure that Meilisearch runs a reindexing)
- [x] Update the spec
- [x] ensure #3689 is fixed

## Impacted teams

@meilisearch/docs-team and @meilisearch/integration-team

**Comment by curquiza** [comment]
Discussed with the team today, we cannot make it for v1.2, moving to v1.3

**Comment by c0bra** [comment]
Very much looking forward to this feature.

**Comment by gillian-meilisearch** [comment]
An update on this as we near the 1.3 release. We have decided to split this feature between version 1.3.0 and 1.4.0. The initial implementation will not have settings on the Meilisearch side, rather, the background changes that enable those settings will be implemented. We expect the full feature including settings will be part of an upcoming release. As a result, only some of the linked issues are expected to be resolved with v1.3.0.

Those issues are:

- [Searching for words without . doesn't match any string in the index. #151](https://github.com/meilisearch/product/discussions/151)
- [Try to search in string with 'aaaa.aaaa' text #3778](https://github.com/meilisearch/meilisearch/discussions/3778)
- [Phrase search doesn't return all document that matches the query #3815](https://github.com/meilisearch/meilisearch/issues/3815)


The initial batch of work is being handled here for reference: [Update charabia v0.8.0 #3866](https://github.com/meilisearch/meilisearch/pull/3866 )

**Comment by gillian-meilisearch** [comment]
A further update here we are currently aiming to get a prototype of the settings out in advance of v.1.4.0 so we can gather feedback.
Moving the milestone out to 1.4 as that's what we're targeting for full feature release at this point.

**Comment by curquiza** [comment]
Hello everyone 👋

We have just released the first RC (release candidate) of Meilisearch containing this new feature!

You can test it by using:

- The [release assets](https://github.com/meilisearch/meilisearch/releases)
- The [Meilisearch Docker image](https://hub.docker.com/repository/docker/getmeili/meilisearch/general)

```
docker run -it --rm -p 7700:7700 -v $(pwd)/meili_data:/meili_data getmeili/meilisearch:v1.4.0-rc.0

```

You are welcome to leave your feedback in this discussion.

If you encounter any bugs, please report them [here](https://github.com/meilisearch/meilisearch/issues/new?assignees=&labels=&template=bug_report.md&title=).
Thanks in advance for your help and your involvement in Meilisearch ❤️

🎉 Official and stable release containing this change will be available on September 25th, 2023

⚠️ RC (release candidates) are not recommended for production
