### ISSUE TITLE
`IS EMPTY` filter operator

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#3614]
Related product team resources: [roadmap card]() (_internal only_)

Related product discussions:
- https://github.com/meilisearch/product/discussions/603
- https://github.com/meilisearch/product/discussions/539 

Related spec: https://github.com/meilisearch/specifications/pull/232

## Motivation

Add granular capacity to manage the document base.

## Usage

Filter documents where the field is empty: `""`, `[]`, `{}`.

During the search:

```json
{
  "filter": "tags IS EMPTY"
}
```

Refer to the final spec to know the details and the final decisions about the usage.

## TODO

- [X] Release a prototype, see [this comment](https://github.com/meilisearch/product/discussions/539#discussioncomment-5332300)
- [ ] If prototype validated, merge changes into `main`
- [ ] Update the spec

## Impacted teams

@meilisearch/docs-team 
Maybe @meilisearch/integration-team?

**Comment by bidoubiwa** [comment]
Is there a filter for missing fields? Might be useless but just wondering out of curiosity

**Comment by curquiza** [comment]
Hello everyone following this issue 👋 

We have just released the first RC (release candidate) of Meilisearch containing this new implementation!
You can test this feature by using:
-  the [release assets](https://github.com/meilisearch/meilisearch/releases)
- or the [Meilisearch Docker image](https://hub.docker.com/repository/docker/getmeili/meilisearch/general)
```bash
docker run -it --rm -p 7700:7700 -v $(pwd)/meili_data:/meili_data getmeili/meilisearch:v1.2.0-rc.0
```

You are more than welcome to communicate any feedback about this new implementation.
If you encountered any bugs, please report them [here](https://github.com/meilisearch/meilisearch/issues/new?assignees=&labels=&template=bug_report.md&title=).

Thanks in advance for your help and your involvement in Meilisearch ❤️ 

🎉 Official and stable release containing this change will be available on 5th June 2023

⚠️ RC (release candidates) are not recommended for production
