### ISSUE TITLE
`IS NULL` filter operator

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#3615]
Related product team resources: [roadmap card](https://www.notion.so/meilisearch/ef7d86c80ef44c549e2361c70a367723?v=d11906bcef8b4b77815f84b801931c00&p=5492ee53dadb4fc8a1efa74e7661771f&pm=s) (_internal only_) 

Related product discussions:
- https://github.com/meilisearch/product/discussions/89
- https://github.com/meilisearch/product/discussions/603
- https://github.com/meilisearch/product/discussions/539
- https://github.com/meilisearch/product/discussions/325

Related spec: WIP

## Motivation

Give more granularity in document management and search.

## Usage

Filter documents where the fields are `null`.

During the search:

```json
{
  "filter": "tags IS NULL"
}
```

Refer to the final spec to know the details and the final decisions about the usage.

## TODO

- [X] Release a prototype -> see [this comment](https://github.com/meilisearch/product/discussions/539#discussioncomment-5332300)
- [ ] If prototype validated, merge changes into `main`
- [ ] Update the spec

## Impacted teams

@meilisearch/docs-team 
Maybe @meilisearch/integration-team

**Comment by curquiza** [comment]
Hello everyone following this issue 👋 

We have just released the first RC (release candidate) of Meilisearch containing this new implementation!
You can test this feature by using:
-  the [release assets](https://github.com/meilisearch/meilisearch/releases)
- or the [Meilisearch Docker image](https://hub.docker.com/repository/docker/getmeili/meilisearch/general)
```bash
docker run -it --rm -p 7700:7700 -v $(pwd)/meili_data:/meili_data getmeili/meilisearch:v1.2.0-rc.0
```

You are more than welcome to communicate any feedback about this new implementation.
If you encountered any bugs, please report them [here](https://github.com/meilisearch/meilisearch/issues/new?assignees=&labels=&template=bug_report.md&title=).

Thanks in advance for your help and your involvement in Meilisearch ❤️ 

🎉 Official and stable release containing this change will be available on 5th June 2023

⚠️ RC (release candidates) are not recommended for production
