### ISSUE TITLE
Circumvent reaching the task DB size limit

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#3622]
Related product team resources: [roadmap card](https://www.notion.so/meilisearch/ef7d86c80ef44c549e2361c70a367723?v=d11906bcef8b4b77815f84b801931c00&p=4b0a96687ea64674be7c9f5b186ceb13&pm=s) (_internal only_)
Related product discussion: None
Related spec: WIP

## Motivation

When Meilisearch reaches the maximum size for the task DB (the hard-coded value of 10GB), Meilisearch cannot accept any new tasks, including tasks deletion. It's even impossible to flush the task history.
In this situation, the users are stuck and cannot do anything.
We need to provide a way to by pass this issue.

## Usage

No solution has been decided yet, needs to be discussed with @macraig and @gmourier.

Refer to the final spec to know the details and the final decisions about the usage.

## TODO

- [x] Fix https://github.com/meilisearch/meilisearch/issues/3644
- [ ] Merge changes into `main`
- [ ] Update the spec
- [ ] Make the @meilisearch/cloud-team test the RC

## Impacted teams

@meilisearch/docs-team -> the new behavior should be described, at least, as an engine limitation.
@meilisearch/cloud-team

**Comment by curquiza** [comment]
This issue (https://github.com/meilisearch/meilisearch/issues/3644) should be fixed as well as part of this current issue solving.

**Comment by curquiza** [comment]
Hello everyone following this issue 👋 

We have just released the first RC (release candidate) of Meilisearch containing this new implementation!
You can this feature it by using
-  the [release assets](https://github.com/meilisearch/meilisearch/releases)
- or the [Meilisearch Docker image](https://hub.docker.com/repository/docker/getmeili/meilisearch/general)
```bash
docker run -it --rm -p 7700:7700 -v $(pwd)/meili_data:/meili_data getmeili/meilisearch:v1.2.0-rc.0
```

You are more than welcome to communicate any feedback about this new implementation in this current issue.
If you encountered any bugs, please report them [here](https://github.com/meilisearch/meilisearch/issues/new?assignees=&labels=&template=bug_report.md&title=).

Thanks in advance for your help and your involvement in Meilisearch ❤️ 

🎉 Official and stable release containing this change will be available on 3rd April 2023

⚠️ RC (release candidates) are not recommended for production
