### ISSUE TITLE
Improve the metrics

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#3790]
Related product discussion: https://github.com/meilisearch/product/discussions/625
Related spec: https://github.com/meilisearch/specifications/pull/242

## Breaking change

As you can see in the linked discussion, this PR is breaking but only for the `metrics` route, which is part of the experimental metrics feature.
So that can be merged without creating a v2 of meilisearch.

## Motivation

Make the metrics easier to use and provide info on the task queue.

## TODO

- [x] Merge changes into main https://github.com/meilisearch/meilisearch/pull/3789
- [x] Update the product discussion with the new API and a screenshot of the dashboard -> tracked here
- [ ] Make a tweet on the subject to raise awareness

**Comment by curquiza** [comment]
Which points? @irevoire

**Comment by irevoire** [comment]
These one:
- Update the product discussion with the new API and a screenshot of the dashboard
- Make a tweet on the subject to raise awareness

**Comment by gillian-meilisearch** [comment]
The PRs are closed but there are some remaining tasks noted there so re-opening to make sure we remember. :)

**Comment by curquiza** [comment]
Closing this issue since everything that has to be done on engineering side has been done
