### ISSUE TITLE
Experimental Feature: Vector Store

### ISSUE THREAD

**Issue by gillian-meilisearch** [meilisearch/meilisearch#3798]
Related product team resources: [roadmap card](https://www.notion.so/meilisearch/Vector-search-c79cef36cd454b198fbee5809dd4bbbb?pvs=4) (_internal only_) and [PRD](https://www.notion.so/meilisearch/Vector-Search-cd5b8d6ce94944618914ab8d958aceb0) (_internal only_)
Related product discussion: https://github.com/meilisearch/product/discussions/621
Related spec: https://github.com/meilisearch/specifications/pull/248

## Motivation

Meilisearch aims to grow its market share and establish itself in a fast-paced market by using AI to address search needs.

## Usage

The proposed solution consists of two API endpoints for storing and retrieving dense vectors in the first iteration. 

Refer to the final spec to know the details and the final decisions about the usage.

## TODO

- [x] Release a prototype
- [x] If prototype validated, merge changes into `main`
- [ ] Update the spec

## Impacted teams

@meilisearch/docs-team @meilisearch/integration-team

**Comment by Kerollmops** [comment]
## Follow Up

This is the follow up work we need to do to improve the vector store feature of Meilisearch.

 - [ ] Implement our own HNSW on top of LMDB to avoid having to deserialize it entirely at every search request.
 - [x] Delete the documents and vectors from the HNSW-related data structures.
     - [x] Do it the slow and ugly way (we need to be able to iterate over all the values).
     - [ ] Do it the efficient way (Wait for a new method or implement it myself).
 - [x] Store the HNSW on possibly multiple LMDB values.
   - [ ] Measure it and make it faster if needed
   - [ ] Export the `ReadableSlices` type into a small external crate
 - [ ] Remove the `_vectors` field from the default searchable attributes (as we do with `_geo`?).
 - [ ] Correctly compute the candidates by remembering the documents having a valid `_vectors` field.
 - [ ] Return the right errors:
     - [ ] Return an error when the query vector is not the same length as the vectors in the HNSW.
     - [ ] We must return the user document id that triggered the vector dimension issue.
     - [ ] Fix the error codes when using the search route.
 - [ ] ~~Introduce some settings:~~
    We currently ensure that the vector length is consistent over the whole set of documents and return an error for when a vector dimension doesn't follow the current number of dimensions.
     - [ ] The length of the vector the user will provide.
     - [ ] The distance function (we only support dot as of now).
 - [ ] Introduce other distance functions
    - [ ] Euclidean
    - [x] Dot Product
    - [ ] Cosine
    - [ ] Make them SIMD optimized
    - [ ] Give credit to qdrant
 - [ ] Add more tests

**Comment by gillian-meilisearch** [comment]
Hello everyone 👋 

We have just released the first RC (release candidate) of Meilisearch containing this change!
You can test it by using
-  the [release assets](https://github.com/meilisearch/meilisearch/releases)
- the [Meilisearch Docker image](https://hub.docker.com/repository/docker/getmeili/meilisearch/general)

```bash
docker run -it --rm -p 7700:7700 -v $(pwd)/meili_data:/meili_data getmeili/meilisearch:v1.3.0-rc.0
```

If you encounter any bugs, please report them [here](https://github.com/meilisearch/meilisearch/issues/new?assignees=&labels=&template=bug_report.md&title=).
Thanks in advance for your help and your involvement in Meilisearch ❤️ 

🎉 The official and stable release containing this change will be available on July 31st, 2023

⚠️ RC (release candidates) are not recommended for production
