### ISSUE TITLE
Metrics: expose two new indexing stats

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#3843]
Related product discussion: https://github.com/meilisearch/product/discussions/625#discussioncomment-6160845
Related spec: WIP

## Motivation

It would be nice to have some additional prometheus metrics that already exist in /stats endpoint:

    lastUpdate exposed as a gauge with seconds since last update, or unix timestamp to detect if something is not "feeding meilisearch with new data" so we can define alert rules to prevent stale data.
    isIndexing exposed as 0/1 would be helpful to correlate slower http_response_time_seconds_bucket with indexing

## Usage

To help work on this issue, we recently pushed a basic prometheus scraper + grafana dashboard that you can use (and that you should update with the new counters) in the `assets` directory of the repository.

## TODO

- [ ] Merge the PR into main
- [ ] Update the spec
- [ ] Update the product discussion

**Comment by gentcys** [comment]
@irevoire 
I'd like to work on this issue.
Could you assign it to me?

**Comment by curquiza** [comment]
Hello @gentcys

Thanks for your interest in this project 🔥 You are definitely more than welcome to open a PR for this!

For your information, we prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the volunteer contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](../blob/main/CONTRIBUTING.md).   

We are looking forward to reviewing your PR 😊

**Comment by gentcys** [comment]
Hi @curquiza 
I created a PR to fix this issue.
Would you like to take a review on it?
https://github.com/meilisearch/meilisearch/pull/3851

**Comment by curquiza** [comment]
Thank you very much, @Kerollmops will take a look at it as soon as possible

**Comment by gillian-meilisearch** [comment]
The linked PR has been merged and is included in [v1.3-rc-1](https://github.com/meilisearch/meilisearch/releases/tag/v1.3.0-rc.1) 🎉 Thanks again @gentcys ❤️ 

For anyone interested you can test it by using
-  the [release assets](https://github.com/meilisearch/meilisearch/releases/tag/v1.3.0-rc.1)
- the [Meilisearch Docker image](https://hub.docker.com/repository/docker/getmeili/meilisearch/general)

```bash
docker run -it --rm -p 7700:7700 -v $(pwd)/meili_data:/meili_data getmeili/meilisearch:v1.3.0-rc.1
```

If you encounter any bugs, please report them [here](https://github.com/meilisearch/meilisearch/issues/new?assignees=&labels=&template=bug_report.md&title=).

Thanks in advance for your help and your involvement in Meilisearch ❤️ 

🎉 The official and stable release containing this change will be available on July 31st, 2023

⚠️ RC (release candidates) are not recommended for production

**Comment by gillian-meilisearch** [comment]
I'm leaving this issue open for now as there is a small spec change still to be done by us before closing.

**Comment by gentcys** [comment]
@curquiza 
what can I do for that spec?

**Comment by curquiza** [comment]
Hello @gentcys
thank you very much but I think it will be easier for the meilisearch team to do it 😊 
Let me know @gillian-meilisearch if I'm wrong
