### ISSUE TITLE
Support for enabling some experimental features at runtime

### ISSUE THREAD

**Issue by dureuill** [meilisearch/meilisearch#3857]
Related product team resources: [PRD](https://www.notion.so/meilisearch/Runtime-API-to-toggle-Experimental-Feature-a9e4053bbc6f42539983b782cd9b2a3b) (_internal only_)
Related product discussion: None
Related spec: WIP

## Motivation

Currently, experimental features in the engine must be enabled from the CLI or via environment variables.

The problem is that it requires restarting Meilisearch, so:

- It induces downtime.
- Hard for the Cloud team to activate the exp feature for their users.

## Usage

Add new route `GET/POST/PATCH/DELETE /experimental-features` to switch on or off some of the experimental features in a manner persistent between instance restarts

### Example

<details>
<summary>Using the feature to enable `scoreDetails`</summary>

```json
❯ curl \
  -X POST 'http://localhost:7700/indexes/index-word-count-10-count/search' \
  -H 'Content-Type: application/json' \
  --data-binary '{ "q": "Batman", "limit": 1, "showRankingScoreDetails": true, "attributesToRetrieve": ["title"]}' | jsonxf

{
  "message": "Computing score details requires enabling the `score details` experimental feature. See https://github.com/meilisearch/product/discussions/674",
  "code": "feature_not_enabled",
  "type": "invalid_request",
  "link": "https://docs.meilisearch.com/errors#feature_not_enabled"
}
```

```json
❯ curl \
  -X PATCH 'http://localhost:7700/experimental-features/' \
  -H 'Content-Type: application/json'  \
--data-binary '{
    "scoreDetails": true
  }'
{"scoreDetails":true,"vectorSearch":false}
```

```json
❯ curl \
  -X POST 'http://localhost:7700/indexes/index-word-count-10-count/search' \
  -H 'Content-Type: application/json' \
  --data-binary '{ "q": "Batman", "limit": 1, "showRankingScoreDetails": true, "attributesToRetrieve": ["title"]}' | jsonxf
{
  "hits": [
    {
      "title": "Batman",
      "_rankingScoreDetails": {
        "words": {
          "order": 0,
          "matchingWords": 1,
          "maxMatchingWords": 1,
          "score": 1.0
        },
        "typo": {
          "order": 1,
          "typoCount": 0,
          "maxTypoCount": 1,
          "score": 1.0
        },
        "proximity": {
          "order": 2,
          "score": 1.0
        },
        "attribute": {
          "order": 3,
          "attribute_ranking_order_score": 1.0,
          "query_word_distance_score": 1.0,
          "score": 1.0
        },
        "exactness": {
          "order": 4,
          "matchType": "exactMatch",
          "score": 1.0
        }
      }
    }
  ],
  "query": "Batman",
  "processingTimeMs": 3,
  "limit": 1,
  "offset": 0,
  "estimatedTotalHits": 46
}
```

</details>

Refer to the final spec to know the details and the final decisions about the usage.

## TODO

- [ ] Merge initial PR into `main`
- [ ] Update the spec
- [ ] Add more automated tests (refer to the [TODOs in this PR for details](https://github.com/meilisearch/meilisearch/pull/3850#issue-1770410865))

## Impacted teams

- @meilisearch/cloud-team: for using in the cloud
- @meilisearch/integration-team: to possibly add support to some SDKs for this endpoint?
- @meilisearch/docs-team: to document the endpoint
