### ISSUE TITLE
Make the experimental route `/metrics` activable via HTTP too

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#4086]
We would like to make the experimental “Prometheus metrics” feature accessible via the HTTP API, as it is for the [score details](https://github.com/meilisearch/product/discussions/674) and [vector search](https://github.com/meilisearch/product/discussions/677) experimental features.

More info regarding this exp feature: https://github.com/meilisearch/product/discussions/625

### Activate the feature:

The experimental feature to activate the route `/metrics` is currently activable using a flag `--experimental-enable-metrics`

```jsx
curl \
  -X PATCH 'http://localhost:7700/experimental-features/' \
  -H 'Content-Type: application/json'  \
--data-binary '{
    "metrics": true
  }'
```

### Getting the information about the feature

```jsx
curl -X GET 'http://localhost:7700/experimental-features/'

{
    "scoreDetails": false,
    "vectorStore": false,
    "metrics": true
}
```

## TODO

- [ ]  Make it available via HTTP as described above
- [ ]  The users can still launch Meilisearch using the `--experimental-enable-metrics` flag.
- [ ]  If the flag `--experimental-enable-metrics` is activated, a call to the `GET /experimental-features` route right after the launch will show `"metrics": true` even if the user has not called the `PATCH /experimental-features` route yet.
- [ ]  Even if the `--experimental-enable-metrics` flag is present at launch, calling the `PATCH /experimental-features` route with `"metrics": false` disables the experimental feature.
- [ ]  Update the spec

## Impacted teams
@meilisearch/cloud-team @meilisearch/docs-team

**Comment by aneesh9909** [comment]
Hello! I would like to pick up this issue but it's my first time touching this codebase so I wanted to confirm if I've understood this correctly.

My understanding of this issue is that the `metrics` experimental feature needs to be added to the [RuntimeTogglableFeatures](https://github.com/meilisearch/meilisearch/blob/86b314626dc846b68972b62a2ec3188be09ff035/meilisearch/src/routes/features.rs#L42C1-L42C1)

**Comment by curquiza** [comment]
Hello @aneesh9909 

For your information, we prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the volunteer contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](../blob/main/CONTRIBUTING.md).   

We are looking forward to reviewing your PR 😊

> My understanding of this issue is that the `metrics` experimental feature needs to be added to the [RuntimeTogglableFeatures](https://github.com/meilisearch/meilisearch/blob/86b314626dc846b68972b62a2ec3188be09ff035/meilisearch/src/routes/features.rs#L42C1-L42C1)

Yes!

Don't forget to add tests so that we ensure everything is working.

The codebase is really big and is not recommended for first time contributor in Rust. If you already have done Rust before it should be ok. Otherwise, I would recommend contributing to smaller projects like Yes!
