### ISSUE TITLE
Bump charabia: add Khmer language support

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#4164]
## Motivation

Adress more language support on Meilisearch: new version of Charabia (v0.8.5) will introduce Khmer support.

It was demanded by the community and implemented by the community

## TODO

- [ ] Create a new version of Charabia (v0.8.5)
- [ ] Bump charabia version in Meilisearch
- [ ] merge into `release-v1.5.0`

## Impacted teams

@meilisearch/docs-team for this page maybe: https://www.meilisearch.com/docs/learn/what_is_meilisearch/language#improving-our-language-support

**Comment by curquiza** [comment]
Closed by #2605
