### ISSUE TITLE
[EXP] Vector search v2

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#4188]
Related product team resources: [PRD](https://www.notion.so/meilisearch/Vector-Search-cd5b8d6ce94944618914ab8d958aceb0) (_internal only_)
Related product discussion: https://github.com/orgs/meilisearch/discussions/677

## Motivation

After the first iteration of vector search released in v1.3.0, we now want to provide more facilities for the users to apply segmented search

## Usage

Refer to https://meilisearch.notion.site/v1-6-Hybrid-Search-Embedders-ea42c82f90cc4bc0be1eeb917c1118c8 (public)

## TODO

Remaining work with priorities

### P1: RC0

- [x] Rebase: integrate changes from main (heed new version) so that the PR is mergeable
- [x] Backend: integrate arroy as vector store for more acceptable performance of search and indexing
- [x] Bug: Differential indexing on template change: currently just changing the prompt does not cause reindexing, as it normally should
- [ ] Relevancy: Apply distribution changes https://math.stackexchange.com/questions/2894681/how-to-transform-shift-the-mean-and-standard-deviation-of-a-normal-distribution to the scores of models to bring them back to a gaussian centered around 0 with about 0.2 of standard deviation
  - Apply fitting values to default models
- [x] API, relevancy: In a hybrid search, apply a semantic ratio to scores coming from semantic search, and apply the complementary to scores coming from keyword search
- [x] CI: remove openSSL dep (hf hub)
- [x] embed in all search routes
- [x] compute dimension for manual vectors (what to do when only removing vectors???)
- [x] API: Remove unimplemented control for the user when a document cannot fill the template.
  - [x] Check if `| default` works as expected => it doesn't
  - [x] Remove "fallback" and "strategy"
- [x] API: Rename prompt to template
- [x] API: Remove weightSource, by checking the presence of each file on the model and choosing them in some predefined order
- [x] API: Implement the Hybrid search API that we designed
  - [x] remove `VectorQuery`
  - [x] no string in vector
  - [x] hybrid when there is hybrid only, embedding from query
- [x] check model casing for openai, fix if needed
- [x] API, consistency: Add the setting routes for embedders and subobjects

### P2: Later

- [x] Bug: Currently templates that refer to nested fields in document are erroneously rejected
- [x] API: actual support of multiple embedders
  - [x] `_vectors` is an object
  - [x] ~~`vector` is an object,~~ or `hybrid.embedder` exists
  - [x] the default embedder has key "default" when there are multiple embedders
  - [x] take the unique embedder as default when there's only one
- [ ] Security: better openai api key handling
  - [x] don't save in setting when we got it from the environment
  - [ ] if saved, don't display in setting by default (display masked)
- [ ] Error handling, add docid and embedder name to:
  - [ ] prompt errors
  - [ ] embedding errors
- [ ] Download model in a subdir of the data.ms
- [ ] Support again `_vectors` as an array (of array) to facilitate user migration 
- [ ] if 2 embedders, one should be named “default”  or error
- [ ] Test very long vector use case
- [ ] Expand tests in `meilisearch/tests/search/hybrid.rs`

### P3: less important

- [x] Consider simplifying hybrid search implementation: as we take the max of both scores, the sub score in one list cannot be greater than the main score of the other list. As a result, we can just ignore sub scores, simplifying both implementation and runtime.
- [x] Error handling: we are ignoring the case where we have too many vectors or too many embedders (>256 in both cases)
- [ ] Consistency: Make sure the behavior of the highlighter is consistent in hybrid search
- [ ] Consistency: Make sure the score details have a consistent behavior in hybrid search
  - Behavior is not so bad, we'll get the best score details for each document
  - [ ] But we need to apply the semantic ratio to the `_rankingScore`.
- [ ] Consistency, accuracy: Save a bitmap of documents with vectors to better compute "number of candidates" (but a bit vain in presence of autoembedders that will embed all documents)

- [x] Land #4226 in `main`
- [x] Release in rc-0
- [ ] Update the [associated product discussion](https://github.com/orgs/meilisearch/discussions/677)

## Impacted teams

@meilisearch/docs-team

**Comment by dureuill** [comment]
Sprint progress report

Vector search v2 is progressing on three fronts:

1. Generating the embeddings for documents and queries. #4213 
2. Hybrid search #4226 
3. Scaling the vector store https://github.com/meilisearch/arroy

# TODO

1. Generating the embeddings for documents and queries
  - [ ] Decide on how to make the models available
  - [ ] Implement worker solution
  - [ ] Implement API token
  - [ ] Better batching of vectors
  - [ ] Better error handling
  - [ ] Add settings to control embedding
  - [ ] Remove added dependency on openssl so CI passes again
  - [ ] Implement mixed strategy
  - [ ] Reimplement indexing after diff-indexing
  - [ ] Be sensitive to changes to source fields
2. Hybrid search
  - [ ] Design API
  - [ ] Implement API
  - [ ] Add settings to control weights and spread
3. arroy
  - [x] implement arroy
  - [ ] Update heed in Meilisearch
  - [ ] integrate arroy

**Comment by dureuill** [comment]
Remaining work with priorities

## P1: required to work

- [ ] Rebase: integrate changes from main (heed new version) so that the PR is mergeable
- [ ] Backend: integrate arroy as vector store for more acceptable performance of search and indexing
- [ ] Bug: Differential indexing on template change: currently just changing the prompt does not cause reindexing, as it normally should
- [ ] Relevancy: Apply distribution changes https://math.stackexchange.com/questions/2894681/how-to-transform-shift-the-mean-and-standard-deviation-of-a-normal-distribution to the scores of models to bring them back to a gaussian centered around 0 with about 0.2 of standard deviation
  - Apply fitting values to default models
- [ ] API, relevancy: In a hybrid search, apply a semantic ratio to scores coming from semantic search, and apply the complementary to scores coming from keyword search
- [ ] CI: remove openSSL dep (hf hub)

## P2: API stuff, important behavior

- [ ] API: Give control to the user about what happens when a document cannot fill the template.
- [ ] Bug: Currently templates that refer to nested fields in document are erroneously rejected
- [ ] API: Rename prompt to template
- [ ] API: Remove weightSource, by checking the presence of each file on the model and choosing them in some predefined order
- [ ] API: Implement the Hybrid search API that we designed
- [ ] API: actual support of multiple embedders
  - `_vectors` is an object
  - `vector` is an object, or `hybrid.embedder` exists
  - add "default" field to embedders
- [ ] Security: better openai api key handling
  - don't save in setting when we got it from the environment
  - if saved, don't display in setting by default (display masked)
- [ ] API, consistency: Add the setting routes for embedders and subobjects

## P3: less important

- [ ] Consistency: Make sure the behavior of the highlighter is consistent in hybrid search
- [ ] Consistency: Make sure the score details have a consistent behavior in hybrid search
- [ ] Consistency, accuracy: Save a bitmap of documents with vectors to better compute "number of candidates" (but a bit vain in presence of autoembedders that will embed all documents)

**Comment by dureuill** [comment]
Work landed on v1.6, there are some follow-ups, find them in https://github.com/meilisearch/meilisearch/issues/3875
