### ISSUE TITLE
Remove schema & rewrite the settings endpoint

### ISSUE THREAD

**Issue by qdequele** [meilisearch/MeiliSearch#419]
All settings update will be as type update or keep. 
The deletion route will not remove all fields but reset them.

[!] The `identifier` will be removed from settings and added on the index object as `primaryKey`

### Settings
- GET `/indexes/:uid/settings`: displays ALL settings.
- POST `/indexes/:uid/settings`: replaces ALL settings.
- DELETE `/indexes/:uid/settings` : reset ALL settings. This route is dangerous.

### Settings > Ranking rules
- GET `/indexes/:uid/settings/ranking-rules`: get all ranking rules
- POST `/indexes/:uid/settings/ranking-rules`: replaces all ranking rules
- DELETE `/indexes/:uid/settings/ranking-rules`: reset all ranking rules

The new custom ranking rules have always the possibility of being ascending and descending. But the format has changed from `attribute:asc`/`attribute:dsc` to `asc(attribute)`/`dsc(attribute)`.

### Settings >  Distinct attribute
- GET `/indexes/:uid/settings/distinct-attribute`: get the distinct field
- POST `/indexes/:uid/settings/distinct-attribute`: replaces the distinct field (it is a string)
- DELETE `/indexes/:uid/settings/distinct-attribute`: reset the distinct field

### Settings > Searchable attributes 
- GET `/indexes/:uid/settings/searchable-attributes`
- POST `/indexes/:uid/settings/searchable-attributes`
- DELETE `/indexes/:uid/settings/searchable-attributes`

### Settings > Displayed attributes
- GET `/indexes/:uid/settings/displayed-attributes`
- POST `/indexes/:uid/settings/displayed-attributes`
- DELETE `/indexes/:uid/settings/displayed-attributes`

### Settings > Accept new fields
- GET `/indexes/:uid/settings/accept-new-fields`
- POST `/indexes/:uid/settings/accept-new-fields`

`accept-new-fields` determines what MeiliSearch should do with new fields found during document addition.

### Settings > Synonyms
- GET `/indexes/:uid/settings/synonyms`
- POST `/indexes/:uid/settings/synonyms`
- DELETE `/indexes/:uid/settings/synonyms`

### Settings > Stop words
- GET `/indexes/:uid/settings/stop-words`
- POST `/indexes/:uid/settings/stop-words`
- DELETE `/indexes/:uid/settings/stop-words`

## Sub issues

- [x] #371 
- [x] #414 
- [x] #417 Rewrite stop words endpoint
- [x] #418 Rewrite synonyms endpoint
- [x] #422 Remove the schema
- [x] #430 Change the way to write custom ranking rules
- [x] #470 Remove identifier from settings
- [x] #473 Reset value of searchable and displayed attributes 
- [x] #474 Change the name of ranking distinct setting 
- [x] #475 Change the name of index new fields 
- [x] #476 Show default ranking rules if user reset them 
- [x] #477 Display default value when getting the settings
- [x] #480 Rename criterions on settings route 
- [x] #483 About criteria names casing 
- [x] #490 Change wording of custom ranking rules `dsc` -> `desc` 
- [x] #498 Update to infer identifier 
- [x] #499 Routes stop-words 
- [x] #501 Impossible to add settings when there is no identifier 
- [x] #502 Remove the route to get identifier on settings 
- [x] #503 Replace index-new-field route to accept-new-fields 
- [x] #504 Default values of synonyms and stop-words 
- [x] #505 Settings of an index created with an identififer 
- [x] #506 acceptNewFields of index created with no identifier 
- [x] #513 Review the internal schema to allow to create schema without identifier 
- [x] #514 Rename identifier into primaryKey 
- [x] #516 Global settings update 
- [x] #517 Error message when impossible to infer the primary-key 
- [x] #518 AcceptNewFields does not take into account the primary-key 
- [x] #519 Adding primary-key when adding documents does not work
- [x] #521 asc/desc on string field

**Comment by bidoubiwa** [comment]
@qdequele  I need precisions on the body of all POST routes.

**Comment by qdequele** [comment]
I finally simplify it by removing middle level.

`/indexes/:index/settings` > GET POST DELETE
`/indexes/:index/settings/ranking-rules` > GET POST DELETE
`/indexes/:index/settings/ranking-distinct` > GET POST DELETE
`/indexes/:index/settings/identifier` > GET
`/indexes/:index/settings/searchable-attributes` > GET POST DELETE
`/indexes/:index/settings/displayed-attribute` > GET POST DELETE
`/indexes/:index/settings/index-new-field` > GET POST
`/indexes/:index/settings/synonyms` > GET POST DELETE
`/indexes/:index/settings/stop_words` > GET POST DELETE

**Comment by qdequele** [comment]
closed by #441

**Comment by bidoubiwa** [comment]
The `identifier` field is not in the setting anymore.

**Comment by bidoubiwa** [comment]
> `/indexes/:index/settings` > GET POST DELETE
> `/indexes/:index/settings/ranking-rules` > GET POST DELETE
> `/indexes/:index/settings/ranking-distinct` > GET POST DELETE
<s>`/indexes/:index/settings/identifier` > GET</s>
> `/indexes/:index/settings/searchable-attributes` > GET POST DELETE
> `/indexes/:index/settings/displayed-attribute` > GET POST DELETE
> `/indexes/:index/settings/index-new-field` > GET POST
> `/indexes/:index/settings/synonyms` > GET POST DELETE
> `/indexes/:index/settings/stop_words` > GET POST DELETE

The `identifier` field is not in the setting anymore.
