### ISSUE TITLE
Autogenerated ids

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#4190]
Related product team resources: [PRD](https://www.notion.so/meilisearch/Autogenerated-id-c90139b4a97f4eca9eb6558968c42265) (_internal only_)
Related product discussion: https://github.com/orgs/meilisearch/discussions/371
Related spec: TODO

## Motivation

- Ease Meilisearch onboarding
- Ease import of documents for users who don't want to update them later (ex: users scrapping their data and put them directly into Meilisearch)

## Usage

Refer to: https://www.notion.so/meilisearch/Autogenerated-id-usage-c3216c0bb611463bbe026af2a941e518

## TODO

- [ ] Define the scope of implementation
- [ ] Release a prototype
- [ ] If prototype validated, merge changes into `main`
- [ ] Update the spec

## Impacted teams

@meilisearch/docs-team
