### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by juslintek** [meilisearch/meilisearch#4369]
Related product team resources: [PRD]() (_internal only_)
Related product discussion:
Related spec: WIP

## Motivation

Want this to work instant as with any other data
## Usage

I am syncing this table via laravel models to meilisearch:
```MySQL
create table gf_db.wp_companies
(
    company_code                                      bigint                                       not null
        primary key,
    company_name                                      varchar(255) collate utf8mb4_unicode_520_ci  not null,
    vat_code                                          varchar(255) collate utf8mb4_unicode_520_ci  null,
    vat_code_end_date                                 date                                         null,
    vat_code_start_date                               date                                         null,
    address                                           varchar(255) collate utf8mb4_unicode_520_ci  null,
    activity_name                                     varchar(255) collate utf8mb4_unicode_520_ci  null,
    activity_section                                  varchar(255) collate utf8mb4_unicode_520_ci  null,
    employees_count                                   int                                          null,
    turnover_2021                                     decimal(14, 2)                               null,
    turnover_2022                                     decimal(14, 2)                               null,
    phone                                             varchar(255) collate utf8mb4_unicode_520_ci  null,
    web                                               varchar(255) collate utf8mb4_unicode_520_ci  null,
    email                                             varchar(255) collate utf8mb4_unicode_520_ci  null,
    current_manager_name                              varchar(255) collate utf8mb4_unicode_520_ci  null,
    current_manager_last_name                         varchar(255) collate utf8mb4_unicode_520_ci  null,
    sodra_debt                                        decimal(14, 2)                               null,
    sodra_delayed_debt                                decimal(14, 2)                               null,
    company_status                                    varchar(255) collate utf8mb4_unicode_520_ci  null,
    reg_date                                          date                                         null,
    company_form                                      varchar(255) collate utf8mb4_unicode_520_ci  null,
    city                                              varchar(255) collate utf8mb4_unicode_520_ci  null,
    landing_url                                       varchar(600) collate utf8mb4_unicode_520_ci  null,
    total_funding_amount_for_company_activity_section int                                          null,
    total_fundings_in_company_region                  int                                          null,
    matched_announcements_count                       int                                          null,
    matched_announcements                             varchar(1000) collate utf8mb4_unicode_520_ci null,
    biggest_matching_funding_amount                   decimal(14, 2)                               null,
    biggest_matching_funding_intensity                int                                          null,
    biggest_matching_funding_name                     varchar(255) collate utf8mb4_unicode_520_ci  null,
    company_size                                      varchar(255) collate utf8mb4_unicode_520_ci  null,
    created_at                                        timestamp                                    null,
    updated_at                                        timestamp                                    null
);

create index fundings_per_activity_section_index
    on gf_db.wp_companies (total_funding_amount_for_company_activity_section);

create index wp_companies_activity_name_index
    on gf_db.wp_companies (activity_name);

create index wp_companies_activity_section_index
    on gf_db.wp_companies (activity_section);

create index wp_companies_address_index
    on gf_db.wp_companies (address);

create index wp_companies_biggest_matching_funding_amount_index
    on gf_db.wp_companies (biggest_matching_funding_amount);

create index wp_companies_biggest_matching_funding_intensity_index
    on gf_db.wp_companies (biggest_matching_funding_intensity);

create index wp_companies_biggest_matching_funding_name_index
    on gf_db.wp_companies (biggest_matching_funding_name);

create index wp_companies_city_index
    on gf_db.wp_companies (city);

create index wp_companies_company_form_index
    on gf_db.wp_companies (company_form);

create index wp_companies_company_name_index
    on gf_db.wp_companies (company_name);

create index wp_companies_company_size_index
    on gf_db.wp_companies (company_size);

create index wp_companies_company_status_index
    on gf_db.wp_companies (company_status);

create index wp_companies_current_manager_last_name_index
    on gf_db.wp_companies (current_manager_last_name);

create index wp_companies_current_manager_name_index
    on gf_db.wp_companies (current_manager_name);

create index wp_companies_email_index
    on gf_db.wp_companies (email);

create index wp_companies_employees_count_index
    on gf_db.wp_companies (employees_count);

create index wp_companies_matched_announcements_count_index
    on gf_db.wp_companies (matched_announcements_count);

create index wp_companies_matched_announcements_index
    on gf_db.wp_companies (matched_announcements(768));

create index wp_companies_phone_index
    on gf_db.wp_companies (phone);

create index wp_companies_reg_date_index
    on gf_db.wp_companies (reg_date);

create index wp_companies_sodra_debt_index
    on gf_db.wp_companies (sodra_debt);

create index wp_companies_sodra_delayed_debt_index
    on gf_db.wp_companies (sodra_delayed_debt);

create index wp_companies_total_fundings_in_company_region_index
    on gf_db.wp_companies (total_fundings_in_company_region);

create index wp_companies_turnover_2021_index
    on gf_db.wp_companies (turnover_2021);

create index wp_companies_turnover_2022_index
    on gf_db.wp_companies (turnover_2022);

create index wp_companies_vat_code_end_date_index
    on gf_db.wp_companies (vat_code_end_date);

create index wp_companies_vat_code_index
    on gf_db.wp_companies (vat_code);

create index wp_companies_vat_code_start_date_index
    on gf_db.wp_companies (vat_code_start_date);

create index wp_companies_web_index
    on gf_db.wp_companies (web);
````

What happens after making a sync, when I request specifically via meilisearch data, it works at the same pace as make simple select request for specific field via MySQL. What might be wrong?

My meilisearch configs:
```bash
root@getfunded:~# cat /etc/meilisearch.toml
# This file shows the default configuration of Meilisearch.
# All variables are defined here: https://www.meilisearch.com/docs/learn/configuration/instance_options#environment-variables

# Designates the location where database files will be created and retrieved.
# https://www.meilisearch.com/docs/learn/configuration/instance_options#database-path
db_path = "/var/lib/meilisearch/data"

# Configures the instance's environment. Value must be either `production` or `development`.
# https://www.meilisearch.com/docs/learn/configuration/instance_options#environment
env = "production"

# The address on which the HTTP server will listen.
http_addr = "localhost:7700"

# Sets the instance's master key, automatically protecting all routes except GET /health.
# https://www.meilisearch.com/docs/learn/configuration/instance_options#master-key
master_key = "makeyour own lol"

# Deactivates Meilisearch's built-in telemetry when provided.
# Meilisearch automatically collects data from all instances that do not opt out using this flag.
# All gathered data is used solely for the purpose of improving Meilisearch, and can be deleted at any time.
# https://www.meilisearch.com/docs/learn/configuration/instance_options#disable-analytics
# no_analytics = true

# Sets the maximum size of accepted payloads.
# https://www.meilisearch.com/docs/learn/configuration/instance_options#payload-limit-size
http_payload_size_limit = "100 MB"

# Defines how much detail should be present in Meilisearch's logs.
# Meilisearch currently supports six log levels, listed in order of increasing verbosity:  `OFF`, `ERROR`, `WARN`, `INFO`, `DEBUG`, `TRACE`
# https://www.meilisearch.com/docs/learn/configuration/instance_options#log-level
log_level = "INFO"

# Sets the maximum amount of RAM Meilisearch can use when indexing.
# https://www.meilisearch.com/docs/learn/configuration/instance_options#max-indexing-memory
# max_indexing_memory = "2 GiB"

# Sets the maximum number of threads Meilisearch can use during indexing.
# https://www.meilisearch.com/docs/learn/configuration/instance_options#max-indexing-threads
# max_indexing_threads = 4

#############
### DUMPS ###
#############

# Sets the directory where Meilisearch will create dump files.
# https://www.meilisearch.com/docs/learn/configuration/instance_options#dump-directory
dump_dir = "/var/lib/meilisearch/dumps/"

# Imports the dump file located at the specified path. Path must point to a .dump file.
# https://www.meilisearch.com/docs/learn/configuration/instance_options#import-dump
# import_dump = "./path/to/my/file.dump"

# Prevents Meilisearch from throwing an error when `import_dump` does not point to a valid dump file.
# https://www.meilisearch.com/docs/learn/configuration/instance_options#ignore-missing-dump
ignore_missing_dump = false

# Prevents a Meilisearch instance with an existing database from throwing an error when using `import_dump`.
# https://www.meilisearch.com/docs/learn/configuration/instance_options#ignore-dump-if-db-exists
ignore_dump_if_db_exists = false


#################
### SNAPSHOTS ###
#################

# Enables scheduled snapshots when true, disable when false (the default).
# If the value is given as an integer, then enables the scheduled snapshot with the passed value as the interval
# between each snapshot, in seconds.
# https://www.meilisearch.com/docs/learn/configuration/instance_options#schedule-snapshot-creation
schedule_snapshot = true

# Sets the directory where Meilisearch will store snapshots.
# https://www.meilisearch.com/docs/learn/configuration/instance_options#snapshot-destination
snapshot_dir = "/var/lib/meilisearch/snapshots/"

# Launches Meilisearch after importing a previously-generated snapshot at the given filepath.
# https://www.meilisearch.com/docs/learn/configuration/instance_options#import-snapshot
# import_snapshot = "./path/to/my/snapshot"

# Prevents a Meilisearch instance from throwing an error when `import_snapshot` does not point to a valid snapshot file.
# https://www.meilisearch.com/docs/learn/configuration/instance_options#ignore-missing-snapshot
ignore_missing_snapshot = false

# Prevents a Meilisearch instance with an existing database from throwing an error when using `import_snapshot`.
# https://www.meilisearch.com/docs/learn/configuration/instance_options#ignore-snapshot-if-db-exists
ignore_snapshot_if_db_exists = false


###########
### SSL ###
###########

# Enables client authentication in the specified path.
# https://www.meilisearch.com/docs/learn/configuration/instance_options#ssl-authentication-path
# ssl_auth_path = "./path/to/root"

# Sets the server's SSL certificates.
# https://www.meilisearch.com/docs/learn/configuration/instance_options#ssl-certificates-path
# ssl_cert_path = "./path/to/certfile"

# Sets the server's SSL key files.
# https://www.meilisearch.com/docs/learn/configuration/instance_options#ssl-key-path
# ssl_key_path = "./path/to/private-key"

# Sets the server's OCSP file.
# https://www.meilisearch.com/docs/learn/configuration/instance_options#ssl-ocsp-path
# ssl_ocsp_path = "./path/to/ocsp-file"

# Makes SSL authentication mandatory.
# https://www.meilisearch.com/docs/learn/configuration/instance_options#ssl-require-auth
ssl_require_auth = false

# Activates SSL session resumption.
# https://www.meilisearch.com/docs/learn/configuration/instance_options#ssl-resumption
ssl_resumption = false

# Activates SSL tickets.
# https://www.meilisearch.com/docs/learn/configuration/instance_options#ssl-tickets
ssl_tickets = false

#############################
### Experimental features ###
#############################

# Experimental metrics feature. For more information, see: <https://github.com/meilisearch/meilisearch/discussions/3518>
# Enables the Prometheus metrics on the `GET /metrics` endpoint.
experimental_enable_metrics = false

# Experimental RAM reduction during indexing, do not use in production, see: <https://github.com/meilisearch/product/discussions/652>
experimental_reduce_indexing_memory_usage = false
```
Tested fetching of very same synced data via laravel Scount, while using in model Searchable trait

```php
namespace App\Models;
 
use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;
 
class Company extends Model
{
    use Searchable;
 
    /**
     * Get the name of the index associated with the model.
     */
    public function searchableAs(): string
    {
        return 'company_name_index';
    }
}
```

There are like 500k rows, 205k rows are actually usuable, keeping the rest for metrics and stuff relations, might be usefull in future.

The problem I am facing traced via xdebug, is that there are some request response delays from mailisearch, I make a query with name of "Fin", it stops and waits for around 10 mins, then returns result of 30k subobject json and then it takes another 2 mins for the browser to pick that list up. How can I solve this properly. Any ideas? Also I see that it does not fallback to mysql. Even mysql makes this query faster, it happens wihtin 5s max, the problem it response payload upload to browser and browser lags. I could optimize it by loading without render into localStorage then pick up from there in chuncks for rendering.

render is happening via alpinejs. So very lightweight, just regular table, tr, td loading. From network time i can see this that it start and wait for a long time, same happens withing the php. it just waits:
![image](https://github.com/meilisearch/meilisearch/assets/5687423/ffa58447-dc58-42fd-ae76-02d4b5154948)

And finally I get this:
![image](https://github.com/meilisearch/meilisearch/assets/5687423/de69b044-0756-4bcc-8325-7496031fbe23)

This is ultra annoying, haven't had issues in pats with large payloads, but when I switched to meilisearch for some reason they cause these issues..

And network timing tab:
![image](https://github.com/meilisearch/meilisearch/assets/5687423/2b042461-a474-4d63-9667-5ecd249ed479)

nginx config:
```nginx
upstream prod {
     server unix:/var/run/php/production.sock       max_fails=3 fail_timeout=300s;
}

log_format postdata escape=json '$remote_addr - $remote_user [$time_local] '
                       '"$request" $status $bytes_sent '
                       '"$http_referer" "$http_user_agent" "$request_body"';

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    http2 on;

    server_name dmomai.com www.domain.com;
    root /home/gfweb/website/domain.com/deploy/current/web;
    ssl_certificate /etc/letsencrypt/live/postfixadmin.domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/postfixadmin.domain.com/privkey.pem; # managed by Certbot

    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions
    ssl_session_tickets off;
    ssl_dhparam /etc/nginx/ssl/domain.com/dhparams.pem;

    # old configuration
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA;
    ssl_prefer_server_ciphers on;

    # HSTS (ngx_http_headers_module is required) (63072000 seconds)
    add_header Strict-Transport-Security "max-age=63072000" always;

    # OCSP stapling
    ssl_stapling on;
    ssl_stapling_verify on;

    # verify chain of trust of OCSP response using Root CA and Intermediate certs
    ssl_trusted_certificate /etc/nginx/ssl/domain.com/fullchain.pem;

    # replace with the IP address of your resolver
    resolver 1.1.1.1 1.0.0.1 [2606:4700:4700::1111] [2606:4700:4700::1001] valid=300s;
    resolver_timeout 5s;

    error_log /var/log/nginx/error.log warn;
    access_log /var/log/nginx/access.log main;

    index index.php;

    # Prevent PHP scripts from being executed inside the uploads folder.
    location ~* /app/uploads/.*.php$ {
       deny all;
    }

    location /assets {
      try_files $uri $uri/ =404;
    }

    location = /favicon.ico {
            log_not_found off;
            access_log off;
    }

    location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
    }

    location / {
            access_log /var/log/nginx/production-postdata.log postdata;

            # This is cool because no php is touched for static content.
            # include the "?$args" part so non-default permalinks doesn't break when using query string
            try_files $uri $uri/ /index.php?$args;
    }

    rewrite ^/(wp-.*.php)$ /wp/$1 last;
    rewrite ^/(wp-(content|admin|includes).*) /wp/$1 last;

    location ~ \.php$ {
#             proxy_buffer_size          128k;
#             proxy_buffers              4 256k;
#             proxy_busy_buffers_size    256k;

            fastcgi_request_buffering on;
            fastcgi_pass_request_headers on;
            fastcgi_pass_request_body on;
            fastcgi_socket_keepalive on;
            fastcgi_buffer_size 128k;
            fastcgi_buffers 16 128k;
            fastcgi_busy_buffers_size 256k;
            fastcgi_connect_timeout 300s;
            fastcgi_read_timeout 300s;
            fastcgi_send_timeout 300s;
            fastcgi_next_upstream_timeout 0;

            #NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
            fastcgi_param  QUERY_STRING       $query_string;
            fastcgi_param  REQUEST_METHOD     $request_method;
            fastcgi_param  CONTENT_TYPE       $content_type;
            fastcgi_param  CONTENT_LENGTH     $content_length;

            fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
            fastcgi_param  REQUEST_URI        $request_uri;
            fastcgi_param  DOCUMENT_URI       $document_uri;
            fastcgi_param  DOCUMENT_ROOT      $document_root;
            fastcgi_param  SERVER_PROTOCOL    $server_protocol;
            fastcgi_param  REQUEST_SCHEME     $scheme;
            fastcgi_param  HTTPS              $https if_not_empty;

            fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
            fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;

            fastcgi_param  REMOTE_ADDR        $remote_addr;
            fastcgi_param  REMOTE_PORT        $remote_port;
            fastcgi_param  REMOTE_USER        $remote_user;
            fastcgi_param  SERVER_ADDR        $server_addr;
            fastcgi_param  SERVER_PORT        $server_port;
            fastcgi_param  SERVER_NAME        $server_name;

            # PHP only, required if PHP was built with --enable-force-cgi-redirect
            fastcgi_param  REDIRECT_STATUS    200;
            fastcgi_intercept_errors on;
            fastcgi_pass prod;
            fastcgi_index index.php;
            #The following parameter can be also included in fastcgi_params file
            fastcgi_param  SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
            expires max;
            log_not_found off;
    }

}

server {
    if ($host = www.domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;

    server_name domain.com wwwdomain.com;
#    server_name staging.getfunded.lt;
    return 301 https://$host$request_uri;




}
```

Project is a hybrid of laravel and wordpress :-) fromtend alpinejs, tailwind, bootstrap :-) 

## TODO

Try using seed that would populate mysql table with 205k values of same table no values is larger than 1150 chars. Sync it to meilisearch, make query to meilisearch. And try to retrieve it via browser.

### Reminders when modifying the Setting API

- [ ] Ensure the new setting route is at least tested by the [`test_setting_routes` macro](https://github.com/meilisearch/meilisearch/blob/5204c0b60b384cbc79621b6b2176fca086069e8e/meilisearch/tests/settings/get_settings.rs#L276)
- [ ] Ensure Analytics are fully implemented
  - [ ] `/settings/my-new-setting` configurated in the [`make_setting_routes` macro](https://github.com/meilisearch/meilisearch/blob/5204c0b60b384cbc79621b6b2176fca086069e8e/meilisearch/src/routes/indexes/settings.rs#L141-L165)
  - [ ] global `/settings` route configurated in the [`update_all` function](https://github.com/meilisearch/meilisearch/blob/5204c0b60b384cbc79621b6b2176fca086069e8e/meilisearch/src/routes/indexes/settings.rs#L655-L751)
- [ ] Ensure the dump serializing is consistent with the `/settings` route serializing, e.g., enums case can be different (`camelCase` in route and `PascalCase` in the dump)

#### Special cases when adding a setting for an experimental feature

- [ ] ⚠️ API stability: The setting does not appear on the main settings route when the feature has never been enabled (e.g. mark it `Unset` when returned from the index in this situation. See [an example](https://github.com/meilisearch/meilisearch/blob/7a89abd2a025606a42f8b219e539117eb2eb029f/meilisearch-types/src/settings.rs#L608))
- [ ] The setting cannot be set when the feature is disabled, either by the main settings route or the subroute (see [`validate_settings` function](https://github.com/meilisearch/meilisearch/blob/7a89abd2a025606a42f8b219e539117eb2eb029f/meilisearch/src/routes/indexes/settings.rs#L811))
- [ ] If possible, the setting is reset when the feature is disabled (hard if it requires reindexing)

Is the above nescessary? ☝️ Cofusedm not sure how to do it, was not coding much with rust and meilisearch api itserlf.

## Impacted teams

What teams are available lol? :) No clue ;-)

**Comment by curquiza** [comment]
Hello @juslintek 

Thank you for sharing this information, and sorry for the trouble.

10s to get your query is not expected at all, but it's hard to debug with our current information

- Which version of Meilisearch do you use? We recommend testing with the latest one (currently v1.6.0)
- In which kind of machine does Meilisearch run?
- Most important to isolate the problem: do you have the same latency when calling directly meilisearch with curl command? (without using laravel and without using the browser)
- It's not possible to debug without testing with real data. Could you send us [a dump of your instance](https://www.meilisearch.com/docs/reference/api/dump#create-a-dump) so that we can try and debug?

---

> ## Impacted teams
> 
> What teams are available lol? :) No clue ;-)

You might have noticed this issue template should not be used by external persons. Please use Bug report instead next time 👍

<img width="1338" alt="Capture d’écran 2024-01-29 à 10 14 22" src="https://github.com/meilisearch/meilisearch/assets/20380692/524e5425-cde5-4da7-be37-1b77c9c37041">

**Comment by curquiza** [comment]
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊
