### ISSUE TITLE
Modify facet-search sort at query time

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#4424]
Related product team resources: [PRD](https://www.notion.so/meilisearch/Faceted-search-improvements-7c4387305e4540a29d2f31ef6720dc7d) (_internal only_)
Related spec: WIP

## Motivation

Required by users

## Usage

https://meilisearch.notion.site/API-usage-sort-facet-search-at-query-time-2c920089bbcc43c5a94185b6cf0f6a6f?pvs=25

## TODO

- [ ] Merge changes into `main`
- [ ] Update the spec

### Reminders when modifying the Setting API

- [ ] Ensure the new setting route is at least tested by the [`test_setting_routes` macro](https://github.com/meilisearch/meilisearch/blob/5204c0b60b384cbc79621b6b2176fca086069e8e/meilisearch/tests/settings/get_settings.rs#L276)
- [ ] Ensure Analytics are fully implemented
  - [ ] `/settings/my-new-setting` configurated in the [`make_setting_routes` macro](https://github.com/meilisearch/meilisearch/blob/5204c0b60b384cbc79621b6b2176fca086069e8e/meilisearch/src/routes/indexes/settings.rs#L141-L165)
  - [ ] global `/settings` route configurated in the [`update_all` function](https://github.com/meilisearch/meilisearch/blob/5204c0b60b384cbc79621b6b2176fca086069e8e/meilisearch/src/routes/indexes/settings.rs#L655-L751)
- [ ] Ensure the dump serializing is consistent with the `/settings` route serializing, e.g., enums case can be different (`camelCase` in route and `PascalCase` in the dump)

#### Special cases when adding a setting for an experimental feature

- [ ] ⚠️ API stability: The setting does not appear on the main settings route when the feature has never been enabled (e.g. mark it `Unset` when returned from the index in this situation. See [an example](https://github.com/meilisearch/meilisearch/blob/7a89abd2a025606a42f8b219e539117eb2eb029f/meilisearch-types/src/settings.rs#L608))
- [ ] The setting cannot be set when the feature is disabled, either by the main settings route or the subroute (see [`validate_settings` function](https://github.com/meilisearch/meilisearch/blob/7a89abd2a025606a42f8b219e539117eb2eb029f/meilisearch/src/routes/indexes/settings.rs#L811))
- [ ] If possible, the setting is reset when the feature is disabled (hard if it requires reindexing)

## Impacted teams

@meilisearch/docs-team

**Comment by curquiza** [comment]
For security reasons, will not be done in v1.8.0, we need more exploration on this
