### ISSUE TITLE
Avoid search crashes 

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#4467]
## Motivation

This issue is close to what was said in https://github.com/meilisearch/meilisearch/issues/3126 but only focuses on what we’ll implement for the v1.8 release

-----

In order to stop crashing when there are too many search requests, we need to consume less RAM and limit the maximum number of search requests happening simultaneously (having more search requests than cores running simultaneously won’t make anything faster).
But if we only limit the number of search requests running concurrently, there is a risk that multiple search requests taking a long time will make the instance completely unavailable.
To avoid being DoS by a single user who found a slow search request, we also need to ensure that no search requests run in an unbounded amount of time.

The plan for the v1.8 release is to:
- [x] [Add a search cutoff to early exit slow search requests](https://github.com/meilisearch/meilisearch/issues/4488)
- [x] [Limit the number of search requests running concurrently](https://github.com/meilisearch/meilisearch/issues/4489)

EDIT:
- [ ] [Limit to the maximum RAM allocated per search request](https://github.com/meilisearch/meilisearch/issues/4383)

This point has been delayed.
It’s still useful but not as much since streaming a search request still consumes a lot of RAM.

**Comment by curquiza** [comment]
Closing this issue since both points have been done for v1.8.0.
Third point has been delayed

Let me know @irevoire if I was wrong about closing this issue, you can reopen it
