### ISSUE TITLE
Avoid a full index deletion in `Transform` when changing settings

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/meilisearch#4478]
Related product team resources: [PRD](https://www.notion.so/meilisearch/Settings-diff-indexing-work-5d77d81761934a5aab32bebd163197af?pvs=4) (_internal only_)

## Summary

This issue is a subset of the work implementing the settings diff-indexing enhancement.

The current approach of [`Transform::prepare_for_documents_reindexing`](https://github.com/meilisearch/meilisearch/blob/main/milli/src/update/index_documents/transform.rs#L811-L954) is to dump all the documents in the index into a `Grenad::File` and delete the whole index to reindex all the documents, taking into account the `Settings` changes.

This function should instead create document deltas without clearing the index.

## TODO

- [x] Ensure Meilisearch has tests triggering the [`Transform::prepare_for_documents_reindexing`](https://github.com/meilisearch/meilisearch/blob/main/milli/src/update/index_documents/transform.rs#L811-L954) methods
- [x] Make both [`into_del_add_obkv` calls](https://github.com/meilisearch/meilisearch/blob/main/milli/src/update/index_documents/transform.rs#L811-L954) use `DelAddOperation::DeletionAndAddition`
- [x] Remove [`ClearDocuments` calls
](https://github.com/meilisearch/meilisearch/blob/d44e20aa8952e7bfb04fdcfcbfc5cce94f93d1f7/milli/src/update/index_documents/transform.rs#L950)

**Comment by ManyTheFish** [comment]
fixed by #4504
