### ISSUE TITLE
Create `SettingsDiff` structure and run extractions based on it

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/meilisearch#4480]
Related product team resources: [PRD](https://www.notion.so/meilisearch/Settings-diff-indexing-work-5d77d81761934a5aab32bebd163197af?pvs=4) (_internal only_)

> ⚠️ this issue depends on #4478 to be implemented

## Summary

This issue is a subset of the work implementing the settings diff-indexing enhancement.

The current approach of [`Settings::execute`](https://github.com/meilisearch/meilisearch/blob/d44e20aa8952e7bfb04fdcfcbfc5cce94f93d1f7/milli/src/update/settings.rs#L1073-L1085) is to trigger a full reindexing if at least one setting-change impacts the database.

Instead, we should create a structure `SettingsDiff` computing the differences between the old and the new version of the `Settings`, then send the `SettingsDiff` everywhere in the indexing process, allowing each part to react depending on the changes.

Additionally, [the `Documents` shouldn't be sent to the database writer](https://github.com/meilisearch/meilisearch/blob/d44e20aa8952e7bfb04fdcfcbfc5cce94f93d1f7/milli/src/update/index_documents/extract/mod.rs#L282) if there is no document addition/modification/deletion.

## Structure example

```rust
struct SettingsDiff {
  before: &Settings { ... }
  after:  &Settings { ... }
}

impl SettingsDiff {
  fn process_searchable_pipeline(&self) -> bool {
    before.searchable_attributes != after.searchable_attributes
    || before.stop_words != after.stop_words
    || before.non_separator_tokens != after.non_separator_tokens // ⚠️ This can be a big vector of strings
    || before.separator_tokens != after.separator_tokens // ⚠️ This can be a big vector of strings
    || before.dictionary != after.dictionary // ⚠️ This can be a big vector of strings
    || before.disable_on_words != after.disable_on_words
    || before.disable_on_attributes != after.disable_on_attributes
  }
}
```

## TODO

- [x] Ensure Meilisearch has tests triggering the `Settings::execute` methods
- [x] Create the `SettingsDiff` structure
- [x] Make the indexer react to the `SettingsDiff`
  - [x] Process the `searchable` pipeline only if needed
  - [x] Process the `facet` pipeline only if needed
  - [x] Process the `vector` pipeline only if needed
  - [ ] Skip `documents` database writing if only the settings have been changed

**Comment by ManyTheFish** [comment]
fixed by https://github.com/meilisearch/meilisearch/pull/4504
