### ISSUE TITLE
Improve hybrid search for v1.8

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#4481]
Related product team resources: [PRD](https://www.notion.so/meilisearch/AI-Search-cd5b8d6ce94944618914ab8d958aceb0) (_internal only_)
Related product discussion: https://github.com/orgs/meilisearch/discussions/677

## Motivation

Bring more capabilities around AI with changes requested by users.

## Usage

https://meilisearch.notion.site/v1-8-AI-search-API-usage-135552d6e85a4a52bc7109be82aeca42?pvs=74

## TODO

- [x] https://github.com/meilisearch/meilisearch/pull/4456
- [x] https://github.com/meilisearch/meilisearch/issues/4531 
- [x] https://github.com/meilisearch/meilisearch/pull/4532 (skip changelog)
- [x] https://github.com/meilisearch/meilisearch/pull/4533
- [x] https://github.com/meilisearch/meilisearch/pull/4537
- [x] https://github.com/meilisearch/meilisearch/pull/4548
- [x] https://github.com/meilisearch/meilisearch/pull/4549 (internal improvements)

## Impacted teams

@meilisearch/docs-team @meilisearch/integration-team

**Comment by dureuill** [comment]
#4456 is part of this issue.

**Comment by dureuill** [comment]
Added latest branch.

Usage in PRD is currently up-to-date
