### ISSUE TITLE
Swapping `searchableAttributes` shouldn't trigger a reindexing

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/meilisearch#4484]
Related product team resources: [PRD](https://www.notion.so/meilisearch/Settings-diff-indexing-work-5d77d81761934a5aab32bebd163197af?pvs=4) (_internal only_)

> ⚠️ this issue depends on #4480 to be implemented

## Summary

This issue is a subset of the work implementing the settings diff-indexing enhancement.

The `searchableAttributes` order is essential in Meilisearch to rank documents matching in different attributes. For instance, a document matching in the title is ranked better than a document matching in the description.
In the current implementation, the ranks are hardcoded in the searchable databases as `fieldid-word-docids`, where the `fieldid` is both the ID and the rank of the field. This forces Meilisearch to reindex, or at least swap, the data in all the fieldid-based databases.

The ID and the rank should be de-correlated, and a structure mapping the fieldid to its rank should be created.
This way, swapping two searchable attributes will only swap ranks in the `fieldid-rank` mapping table and no more reindexing will be needed.
> Moreover, this new structure eases the implementation of a new feature: "allows the user to put the same rank to several attributes" like:
> ```javascript
> {
>   "searchableAttributes": {
>     // title is the most important
>     "title": 1,
>     // description and footer are considered equal
>     "description": 2,
>     "footer": 2
>    }
> }
> ```
> poke @macraig on this.

## TODO

- [x] Ensure `searchableAttributes` swapping is tested in Meilisearch
- [x] Create and index the `fieldid-rank` mapping table
- [x] Make sure that `Attributes` criterion takes into account the `fieldid-rank` mapping table
- [x] Don't trigger a reindexing when the `searchableAttributes` are only swapped
- [x] Do not reindex obkv documents in `documents` database

#### Related Benchmarks:
- `settings-remove-add-swap-searchable.json`

#### Additional note from @ManyTheFish 
I raised the priority of this issue because fixing it will ease several implementations. Today, the field mapping with the fields is unstable, which means that changing the searchable attributes settings can change this mapping, forcing reindexing data that don't need to just because their related field changed.
For instance indexing a document like:
```json
{"id": 1, "name": "Many", "age": 28, "realName": "Maxime"}
```
with the settings:
```json
{"searchableAttributes": ["name"], "filterableAttributes": ["age"]}
```
Should assign the field ids like `"name": 0, "id": 1, "age": 2, "realName": 3`.
And then, changing the settings to:
```json
{"searchableAttributes": ["name", "realName"], "filterableAttributes": ["age"]}
```
Should assign the field ids like `"name": 0, "realName": 1, "id": 2, "age": 3`.
forcing the reindexing of 3 fields just by adding a searchable attribute.
