### ISSUE TITLE
Implement a search cutoff

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#4488]
Related product team resources: [PRD](https://www.notion.so/meilisearch/Adds-a-search-cutoff-fb972393d0b645ea8aa6deff4ec69e14) (_internal only_)
Related product discussion:
Related spec: WIP

## Motivation

We want to ensure that no search requests run for too long.
The most complex part of the code that can take an unrestricted amount of time right now is the sorting of the results.
Thus, a new mechanism is being introduced in the engine that stops the search requests from sorting more results and returns straight away what has already been sorted.
Then, it must still be highlighted, made into a valid object, and returned to the end user.

## Usage

By default, the sorting process of all search requests is stopped after 150ms.
This can be configured through the `PUT /indexes/:index_uid/settings/search-cutoff` route by sending the number of milliseconds that meilisearch is allowed to spend sorting the results.

The only way to know if a search request was stopped early is to request the score details.

Detailed usage available [here](https://meilisearch.notion.site/Search-cutoff-usage-fb5e9a07a7624965a541d0a6f8eb37bc?pvs=4)

## TODO

- [ ] merge changes into `main`
- [ ] Update the spec
- [x] Add an example of the search details

### Reminders when modifying the Setting API

- [x] Ensure the new setting route is at least tested by the [`test_setting_routes` macro](https://github.com/meilisearch/meilisearch/blob/5204c0b60b384cbc79621b6b2176fca086069e8e/meilisearch/tests/settings/get_settings.rs#L276)
- [x] Ensure Analytics are fully implemented
  - [x] `/settings/my-new-setting` configurated in the [`make_setting_routes` macro](https://github.com/meilisearch/meilisearch/blob/5204c0b60b384cbc79621b6b2176fca086069e8e/meilisearch/src/routes/indexes/settings.rs#L141-L165)
  - [x] global `/settings` route configurated in the [`update_all` function](https://github.com/meilisearch/meilisearch/blob/5204c0b60b384cbc79621b6b2176fca086069e8e/meilisearch/src/routes/indexes/settings.rs#L655-L751)
- [x] Ensure the dump serializing is consistent with the `/settings` route serializing, e.g., enums case can be different (`camelCase` in route and `PascalCase` in the dump)

## Impacted teams

@meilisearch/docs-team

**Comment by curquiza** [comment]
A new parameter probably coming so pinging @meilisearch/integration-team here
