### ISSUE TITLE
Limit the number of search requests running concurrently

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#4489]
Related product team resources: [PRD](https://www.notion.so/meilisearch/Limit-the-number-of-concurrent-search-b2b94b36356449e38b41ef675e79b99f) (_internal only_)
Related product discussion: https://github.com/orgs/meilisearch/discussions/729
Related spec: WIP

## Motivation

The search requests in meilisearch are intensive, which means it’s useless to run multiple searches **at the same time**.
The most efficient way to treat search requests is to run one search request **per core**.

But we don't want to refuse search requests straight away when all cores are being used; thus, we're going to keep track of the search requests to process in a queue of fixed-size and then randomly pick the next search request to be processed.

If the queue is full, then Meilisearch will return an error (TBD) with the error code [503 service unavailable](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503) and a `retry-after` header.

Since the size of the queue may vary between use cases, we'll also need to introduce a new global setting for the whole instance, specifying the size of the queue.

## TODO

- [ ] merge changes into `main`
- [ ] Update the spec

### Reminders when modifying the Setting API

- [ ] Ensure the new setting route is at least tested by the [`test_setting_routes` macro](https://github.com/meilisearch/meilisearch/blob/5204c0b60b384cbc79621b6b2176fca086069e8e/meilisearch/tests/settings/get_settings.rs#L276)
- [ ] Ensure Analytics are fully implemented
  - [ ] `/settings/my-new-setting` configurated in the [`make_setting_routes` macro](https://github.com/meilisearch/meilisearch/blob/5204c0b60b384cbc79621b6b2176fca086069e8e/meilisearch/src/routes/indexes/settings.rs#L141-L165)
  - [ ] global `/settings` route configurated in the [`update_all` function](https://github.com/meilisearch/meilisearch/blob/5204c0b60b384cbc79621b6b2176fca086069e8e/meilisearch/src/routes/indexes/settings.rs#L655-L751)
- [ ] Ensure the dump serializing is consistent with the `/settings` route serializing, e.g., enums case can be different (`camelCase` in route and `PascalCase` in the dump)

#### Special cases when adding a setting for an experimental feature

- [ ] ⚠️ API stability: The setting does not appear on the main settings route when the feature has never been enabled (e.g. mark it `Unset` when returned from the index in this situation. See [an example](https://github.com/meilisearch/meilisearch/blob/7a89abd2a025606a42f8b219e539117eb2eb029f/meilisearch-types/src/settings.rs#L608))
- [ ] The setting cannot be set when the feature is disabled, either by the main settings route or the subroute (see [`validate_settings` function](https://github.com/meilisearch/meilisearch/blob/7a89abd2a025606a42f8b219e539117eb2eb029f/meilisearch/src/routes/indexes/settings.rs#L811))
- [ ] If possible, the setting is reset when the feature is disabled (hard if it requires reindexing)

## Impacted teams

@meilisearch/docs-team
