### ISSUE TITLE
Tracking issue: Vector store stabilization

### ISSUE THREAD

**Issue by dureuill** [meilisearch/meilisearch#4733]
Related product discussion: https://github.com/orgs/meilisearch/discussions/677
[Public usage page](https://meilisearch.notion.site/v1-10-AI-search-changes-737c9d7d010d4dd685582bf5dab579e2) centralizing all changes to AI search for v1.10

## Motivation

The `vectorStore` feature has been experimental since Meilisearch v1.3.0.
It is now a very important set of features for the engine, and this issue lays the preliminary work before its eventual stabilization.

🗣️ As part of this stabilization work, your feedback is more than ever welcome in the [product discussion](https://github.com/orgs/meilisearch/discussions/677) :heart:
At this point, feedback should preferably focus on changes that are breaking rather than feature requests, as this is the last opportunity to make breaking changes before the next Meilisearch version, but we can add most new features back-compatibly.

Breaking changes cover:
- changing the name/methods of routes/endpoints,
- changing the name of parameters, 
- adding mandatory parameters,
- removing parameters, 
- removing fields in responses, 
- adding errors
- modifying error codes
- for more information about what constitutes a breaking change, please refer to our [versioning policy](https://github.com/meilisearch/engine-team/blob/main/resources/versioning-policy.md)

We do appreciate all kinds of feedback though, including some to tell us that the feature is already good, as it is today 😊 

## TODO

This is a tracking issue. Sub-issues will be opened and listed here as needed

- [ ] #5002
- [ ] https://github.com/meilisearch/meilisearch/issues/4737
- [x] #5031
- [x] #5032
- [x] #4739
- [x] https://github.com/meilisearch/meilisearch/issues/4736
- [x] https://github.com/meilisearch/meilisearch/issues/4738
- [x] https://github.com/meilisearch/meilisearch/issues/4756
- [x] #4856
- [x] #4885
- [x] #4886

## To do at the same time as the stabilization

- [ ] Make it so `embedders` are displayed all the time, and not only when at least one embedder is defined
- [ ] (actually breaking) Make `_vectors` special all the time, and not only when at least one embedder is defined
- [ ] `semanticHits` is returned all the time, and not only in semantic requests?

## Impacted teams

- @meilisearch/cloud-team: naming changes might impact the embedder configurations in the Cloud, also possible change in default embedder behavior. Might participate in default embedder behavior.
- @meilisearch/docs-team: report behavior and naming changes in the documentation. Might participate in naming and REST embedder behavior discussions
- @meilisearch/integration-team: update the SDKs following breaking changes

**Comment by curquiza** [comment]
Continuing work in v1.11

**Comment by dureuill** [comment]
We need to discuss the ollama version policy for stabilization: https://github.com/meilisearch/meilisearch/pull/4983

**Comment by curquiza** [comment]
Stabilization moved to v1.13

**Comment by curquiza** [comment]
Public usage for v1.13: https://meilisearch.notion.site/v1-13-AI-search-changes-17a4b06b651f80538b65d31724545def
