### ISSUE TITLE
[Experimental] Webhook and health route improvements

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#4788]
Related product team resources: [PRD](https://www.notion.so/meilisearch/Engine-visibility-webhook-and-health-route-improvements-0dea0c9f43da4fcf8c0831f38f3338e7) (_internal only_)

## Motivation

- Give visibility on Cloud side about Meilisearch-related state changes
- Simplify Cloud architecture and processes

## Usage

Implement
- `--experimental-heartbeat-webhook-url`
- `--experimental-heartbeat-authorization-header`
- `--experimental-events-webhook-url`
- `--experimental-events-authorization-header`

Might be released as experimental so a product discussion will be opened

## TODO

- [ ] Release a prototype
- [ ] Make it test by cloud team
- [ ] Merge changes if validate
- [ ] Open Product discussion with usage

## Impacted teams

@meilisearch/docs-team in case you think it's important to document it (but I'm not sure, really internal Cloud feature oriented)
@meilisearch/cloud-team

**Comment by curquiza** [comment]
Moved to v1.11

**Comment by curquiza** [comment]
Lack of time to do it in v1.11 😢
