### ISSUE TITLE
Language setting enhancement: support ISO-639-1 languages code

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/meilisearch#4827]
## Summary

The currently supported language code is the ISO-639-3 codes that are 3gram codes:
```
epo, eng, rus, cmn, spa, por, ita, ben, fra, deu, ukr, kat, ara, hin, jpn, heb, yid, pol, amh, jav, kor, nob, dan, swe, fin, tur, nld, hun, ces, ell, bul, bel, mar, kan, ron, slv, hrv, srp, mkd, lit, lav, est, tam, vie, urd, tha, guj, uzb, pan, aze, ind, tel, pes, mal, ori, mya, nep, sin, khm, tuk, aka, zul, sna, afr, lat, slk, cat, tgl, hye
```

However, even if it's the most complete language code version, the ISO-639-1 (based on bigrams like `en` or `fr` instead of `eng` and `fra`) is most commonly used.
We should accept the  ISO-639-1 codes and automatically convert them into  ISO-639-3 in the meilisearch API.

See the related PRD:
https://meilisearch.notion.site/v1-10-Language-settings-usage-26c5d98b553349d9abacbe7aff698e4e?pvs=74

## Technical approach

The [`FromStr` implementation should be complexified](https://github.com/meilisearch/meilisearch/blob/c2c1ba39ee65512009c2d6998b9640bc53628c10/meilisearch-types/src/locales.rs#L123-L131) by trying to parse ISO-639-1 code if no ISO-639-3 code has been recognized.
Moreover, the deserialization of the [POST /settings](https://github.com/meilisearch/meilisearch/blob/c2c1ba39ee65512009c2d6998b9640bc53628c10/meilisearch/src/routes/indexes/settings.rs#L481-L483) and [POST /search](https://github.com/meilisearch/meilisearch/blob/c2c1ba39ee65512009c2d6998b9640bc53628c10/meilisearch/src/search/mod.rs#L104-L105) routes should support ISO-639-1 codes as well.

## TODO

- [ ] make PATCH /settings support ISO-639-1
- [ ] make PUT /settings/localized-attributes support ISO-639-1
- [ ] make POST /search support ISO-639-1
- [ ] make GET /search support ISO-639-1
- [ ] add tests

**Comment by curquiza** [comment]
For @meilisearch/docs-team: it means we support a new format
