### ISSUE TITLE
[Tracking-issue] Indexer 2024 edition

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/meilisearch#4986]
## Motivation

The current indexer architecture relies too much on temporary files written on disk. It is criticized for using too much disk space and not optimally using the machine's available CPU pool.
The goal of this refactor is to reduce the writing to temporary files as much as possible and make more efficient use of the available CPUs.

#### Document addition
- https://github.com/meilisearch/meilisearch/issues/4985

#### Settings update
TBD
#### Step 1 validation

- [ ] All the tests are green
- [ ] All Benchmarks are green
- [ ] The new indexer has been tested on cloud machines
- [ ] The memory usage is maintained under a defined threshold
- [ ] The pressure on the temporary folder must be reduced 

### Step 2 (P2): Reduce database usage growing linearly with the number of documents
TBD
### Step 3 (P3): Others
TBD

**Comment by curquiza** [comment]
Things for v1.12 are done 🎉
