### ISSUE TITLE
Review the internal schema to allow to create schema without identifier

### ISSUE THREAD

**Issue by qdequele** [meilisearch/MeiliSearch#513]
Will close:
- [ ] Default values of synonyms and stop-words breaking meilisearch-http #504
- [ ] Update to infer identifier meilisearch-http #498 
- [ ] Impossible to add settings when there is no identifier bug meilisearch-core meilisearch-schema #501
- [ ] Settings of an index created with an identififer breaking meilisearch-http #505 
- [ ] acceptNewFields of index created with no identifier breaking meilisearch-http #506
