### ISSUE TITLE
Language detection

### ISSUE THREAD

**Issue by qdequele** [meilisearch/MeiliSearch#560]
It could be very interesting to index documents differently depending on the language. 
A language could be defined by index, by document or by fields. This remains to be defined. 
Once we know the language. We can apply the associated tokenizer and Word stops. 
Of course, this option must be by default (zero-config first) but we can remove it if necessary.

## Interesting ressources
https://www.r-pkg.org/pkg/stopwords
https://github.com/greyblake/whatlang-rs
https://github.com/christophertrml/rs-natural
https://docs.rs/unicode-segmentation/1.6.0/unicode_segmentation/

## Sub Issues
- [ ] #535 Search for Chinese?
- [ ] #275 Improve the tokenizer 
- [ ] #240 Use jieba to tokenize CJK languages 
- [ ] #178 Update the tokenizer to not split when another word touch termination
- [ ] #136 Index language configuration
- [ ] #3 Create a tokenizer

**Comment by MarinPostma** [comment]
closed in favor of #624
