### ISSUE TITLE
Tracking issue: Facets

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/MeiliSearch#625]
This is the tracking issue for the implementation of faceting in Meilisearch.

## Context

Filtering  was thought as two part release. Some time ago we released filtering (https://github.com/meilisearch/MeiliSearch/pull/592), which allows users to create filter documents on arbitrary fields. While this is very flexible it has some performance issues, and when possible, it is preferable to use faceting.

Faceting, the subject of this tracking issue, differs from filtering in that instead of filtering results in the outbound set of documents, it restricts the documents to be filtered on *upstream*. In order to do that, we must declare _facets_ at indexing. Facets are document attributes that indicate which category a document belongs to.

Filtering and faceting aim at being complementary.

###  Setting up facets 

Facet that can be used are set up thanks to the `[POST]/indexes/:index_uid/settings` route. We add a new attribute `attributesForFaceting` that accepts a `[String]`. It's default value is `null`.

Any call to settings with a value for the attribute `attributesForFaceting` overwrites the currently set faceting attributes. Passing an empty array resets all faceting attributes.

A re-indexing when the value for this setting is changed.

A call to  `[POST]/indexes/:index_uid/settings` should list the currently set facets.

**TODO:**
- [x] update `POST` route to accept new attribute  `attributesForFaceting`
- [x] update `GET` route to include facet information in its response

### Document addition and deletion 

On document addition and deletion, the facet indexation must be updated:
**TODO:**
- [x] add new document references to the facet index on document addition
- [x] remove document references from the facet index on document deletion

### Search query 

When doing a search query, a user can specify:
- facets to filter on with the facet syntax (explained below), thanks to the optional parameter `facetFilters`.
- the facets for which to retrieve the matching count for, with the `facets` optional parameter.

`facetFilters` accept arguments of the form `["facetName:facetValue"]` or `[["FacetName:FacetValue"]]` specifying the facets to be used, with the following semantic:

```
[["color:red", "color:blue"], "kind:t-shirt"] <=> ("color:red" OR "color:blue") AND "kind:t-shirt"
```
inner arrays elements are `OR`ed together, outer array elements are `AND`ed together.

Array depth must not be greater than 2, and be at least 1:

* `[["color:red"]]` => correct syntax
* `["color:red"]` => correct syntax
* `"color:red"` => incorrect syntax

Errors are sent back to the user if:
* the syntax is invalid
* it is asked to do faceting on an unregistered or not existing facet. (we could send the list of existing facets to the user)

The `facets` accepts a `[String]` containing all the facets for which we want to retrieve count information. It defaults to `null`. If it is set to `["*"]`, counts for all facets set above will be returned. It will return facets based on a best effort to match the user request. If a facet name is not existing it will be ignored.

The result of the search query contains two additional fields if the `facets` parameter has been set:
* `facets`: returning a count of candidates for each requested facets in the `facets` parameter, if set to `[*]` a count for all facets is returned.
* `exhaustiveFacetsCount` telling whether the above count is exhaustive or approximative.
 
**TODO:**
- [x] update route to accept new parameters
- [x] check the correctness of the query
- [x] update response to take new fields into account, error handling

### Documentation

**TODO:**
- [x] Document the new feature, (see #632)

## Further improvement

These are improvements we will add to this feature **eventually** and will not be part of the initial release. They may however be discussed here for a latter release.

-  support for negative faceting
-  "faceting" on number
- allow mixing facets and filters with the filter syntax

## Related issues

#420
#424 

Any developments on this issue will be logged here

**Comment by MarinPostma** [comment]
**update**: when a user specifies a facet filter in a search that either is an empty array, or contains an empty array:
```
facetFitler: []

or

facetFitler: ["foo:42", []]
```

this is unspecified behavior, and an error is thrown.

Our call is that the only reason a user would specify such a query is by mistake, and he should be informed.

**Comment by MarinPostma** [comment]
right now the parser for `"FacetKey:FacetValue"`  in facet filter expressions is very basic, and may not be powerful enough. At some point in time it may be necessary to implement a more powerful parser.
