### ISSUE TITLE
Tracking issue: Improve internal algorithms

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/MeiliSearch#692]
This issue tracks the improvements to the MeiliSearch core engine, this will allows us to dive more easily into the pieces of the engine like the updtae system or the criteria system. There are four steps that I will list:

- [x] Simplify the documents update system by removing the [serde::De/Serializer structs](https://docs.rs/serde/1.0.110/serde/trait.Serializer.html). #691
- [x] Get rid of hashing to compute documents ids by introducing an id generator. #696
- [x] Reduce the [DocumentId](https://github.com/meilisearch/MeiliSearch/blob/1fef6130249a01a713ff91b8a7d3e80e5470d8b3/meilisearch-types/src/lib.rs#L11-L15) memory size from 64bits to 32bits. #696
- [x] Get rid of the `unsafe static_words_fst` function by bumping fst to 0.4. #706
- [ ] Separate and bitpack the postings lists to gain something between a 40% to 60% index size reduction. #723
- [ ] Simplify [the Criterion Trait](https://github.com/meilisearch/MeiliSearch/blob/1fef6130249a01a713ff91b8a7d3e80e5470d8b3/meilisearch-core/src/criterion/mod.rs#L32-L61) to return an universal score.
- [ ] Ignore updates user payloads when writing or retrieving updates.

## About the document id generator

The id generator will allows us to retrieve the latest available u32 in the list of all the documents ids, this list is associated with a map that maps from the user ids.

By reducing the ids size we enable bitpacking the postings lists. Using u32s also have a downside: we will not be able to accept more than 2^32 (≅ 4.3 billions) documents which is not something we want to support and something else will break before anyway.

- The already used documents ids are stored inside a simple [`sdset::Set<u32>`](https://docs.rs/sdset/0.4.0/sdset/set/struct.Set.html).
- When a user refers to a document he use the user id, we store them inside of an [`fst::Map`](https://docs.rs/fst/0.4.3/fst/struct.Map.html), the key is the user id and the value is the internal geenrated u32 id.

## About separating the postings lists

When we want to bitpack we can only do that on lists of u32s, ordered list are much more compressed than non-ordered ones. MeiliSearch currently have postings lists that are composed of [`DocIndex`es](https://github.com/meilisearch/MeiliSearch/blob/master/meilisearch-types/src/lib.rs#L22-L42) which contains too much information and are not prone to bitpacking.

Instead of having one list of `DocIndex`es by word we should split those into three lists:
 - One with all the documents ids, ordered but not deduplicated.
 - One with all of the positions where the words matched, non ordered.
 - One with all of the highlights areas where the words matched, non ordered.

We do not order the documents ids list because when we will need to recreate the connections between those three lists the documents id will be our guide, a document id index will indicate where to find the correspondings words positions and highlights areas.

[The position of the word](https://github.com/meilisearch/MeiliSearch/blob/1fef6130249a01a713ff91b8a7d3e80e5470d8b3/meilisearch-types/src/lib.rs#L29-L33) is composed of two informations: the attribute in which it has been found and the position of it in terms of words. I think we can store it like `n / 1000` is the position and `n % 1000` is the attribute.

[The highlight of the word](https://github.com/meilisearch/MeiliSearch/blob/1fef6130249a01a713ff91b8a7d3e80e5470d8b3/meilisearch-types/src/lib.rs#L35-L41) is currently made of two u16 and we need to make it be an u32. It is composed of the position in terms of bytes and the length of the highlight in bytes. I think we can store it like `n / 1000` is the position and `n % 1000` is the length of the hightlight.

Extracting the documents ids allows us to remove the duplication of documents ids we were maintaining before to keep good performances when diving throught the Optimal Query Tree. We can now retrieve this non-duplicated but ordered list of documents ids and deduplicate it (this is really fast) to gain the properties of an `sdset::Set`.

**Comment by Kerollmops** [comment]
Here is a status of the advancement of this tracking issue.

Marin found out an article of Daniel Lemire et al. about a library called Roaring Bitmaps, this is one of the fastest library to compute set operations, there is an open source default implementation in C and Nemo157 have created its own version in Rust. I started using it in a private project just to see the power unleashed and that was awesome.

I will likely remove sdset from the project or probably keep it for usage that are not set operations.

**Comment by chinnichaitanya** [comment]
Very much waiting for the universal score! 😃

**Comment by curquiza** [comment]
Check with @Kerollmops, this issue is outdated! To see performance improvements, please check out this repo -> https://github.com/meilisearch/milli
And wait for the v0.21.0 release 😁
