### ISSUE TITLE
Change the settings behavior

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#824]
As a daily user of MS, I noticed some weird or unintuitive behaviors when manipulating the settings.
- sometimes, MS knows attributes that the users don't know (see #767)
- the concept of "new field" with the `acceptNewField` settings is not really intuitive since an attribute is not "new" because already declared in the settings (see #761). It leads to unintuitive behavior because the order (adding documents before the settings or the opposite) matters, but it should not.
- the reset of searchable and displayed attributes has a weird behavior. See the feedback of one of our users:
<img width="647" alt="Screenshot 2020-07-01 at 14 54 14" src="https://user-images.githubusercontent.com/20380692/86252829-fd36f980-bbb3-11ea-90c5-d97d29a61629.png">

### How to solve them?

What we suggest to solve these problems:

The default behavior of `searchableAttributes` and `displayedAttributes` is now `["*"]`.
`["*"]` means "all the attributes".
When resetting one of these settings, the default value is `["*"]` again.

What does it imply?
- the users use `searchableAttributes` and `displayedAttributes` **only for restriction**: I mean, if they want to restrict the display (e.g.: they have `title` and `author` in their documents but only want `title` to be displayed) you use the `displayedAttributes` settings. Otherwise, you don't, because by default all the settings are taken into account.
- the `acceptNewFields` is not needed anymore: no more unintuitive notion of "new fields". If you want to stay safe and avoid new unexpected fields to be added to searchable or displayed attributes (that's the role of the current `acceptNewFields` settings), you just have to change directly the `searchableAttributes` and `displayedAttributes`. Indeed, these two settings when no being set as `["*"]` are whitelists.
- No more unintuitive behavior when resetting because the reset will set the value `["*"]` again.

About the issue that "MeiliSearch knows attributes that the users don't", we suggest changing the behavior of the current `GET indexes/:uid/stats` route.
Currently, when calling this route, the `fieldsDistribution` field returns all the attributes found in the documents **according to the `displayedAttributes` you set**. It means that if you only set `['title']` as `displayedAttributes` you will not see the attribute `author` in `fieldsDistribution` despite MeiliSearch knows `author` and has it in its DB.
We suggest that this route now returns all the known attributes no matter the `displayedAttributes` are.

### TODO

- [x] remove `acceptNewFields` routes
- [x] change the default value of `searchableAttributes` and `displayedAttributes`. Now it's `["*"]` that means "all the attribtues found in the document". This value (`["*"]`) should be set when resetting.
- [ ] `fieldsDistribution` in the `GET indexes/:uid/stats` route should now returns all the known attributes no matter the `displayedAttributes` are.
- [ ]  and of course, add/update tests ❤️

**Comment by MarinPostma** [comment]
@curquiza concerning this:
> fieldsDistribution in the GET indexes/:uid/stats route should now returns all the known attributes no matter the `displayedAttributes` are.

This is more complicated than I thought, as it relies completely on the field being indexed, and there is no simple way to do it. Could we instead give the user a list of known fields along with the fields distribution?

On top of that, I am not sure this information is relevant anymore, since accept new field doesn't exist anymore, us knowing or not that a field exists is irrelevant.

Until we make a decision, I am merging a partial PR with the work already accomplished for the release of v0.13.0

**Comment by eskombro** [comment]
> @curquiza concerning this:
> 
> > fieldsDistribution in the GET indexes/:uid/stats route should now returns all the known attributes no matter the `displayedAttributes` are.
> 
> This is more complicated than I thought, as it relies completely on the field being indexed, and there is no simple way to do it. Could we instead give the user a list of known fields along with the fields distribution?
> 
> On top of that, I am not sure this information is relevant anymore, since accept new field doesn't exist anymore, us knowing or not that a field exists is irrelevant.
> 
> Until we make a decision, I am merging a partial PR with the work already accomplished for the release of v0.13.0

IMO having a knownFields field would serve the exact same purpose of what we wanted to achieve, which is basically letting the user know of every field MeiliSearch knows of. I think it was said it would be present in fieldsDistribution just to avoid having one more field. It would be interesting to know the distribution on those fields, but it doeasn't seem to be the important goal here. 👍

**Comment by curquiza** [comment]
> IMO having a knownFields field would serve the exact same purpose of what we wanted to achieve, which is basically letting the user know of every field MeiliSearch knows of. I think it was said it would be present in fieldsDistribution just to avoid having one more field.

Exactly!

Would the `knownFields` add to the stats of the index (`GET /indexes/:uid/stats`)? 🙂 I would rather not have this field in the settings of the index since it's not settable.

FYI: If I'm not wrong, another temporary solution for the user to know the fields (without adding `knownFields`) is to reset the `displayedAttributes`, and then, to check the `fieldsDistribution`.

**Comment by MarinPostma** [comment]
> FYI: If I'm not wrong, another temporary solution for the user to know the fields (without adding knownFields) is to reset the displayedAttributes, and then, to check the fieldsDistribution.

Not exactly, it depends on the `searchableAttributes`, you'd need to reset this fields, and then check the `fieldsDistribution`.

**Comment by eskombro** [comment]
> @curquiza concerning this:
> 
> > fieldsDistribution in the GET indexes/:uid/stats route should now returns all the known attributes no matter the `displayedAttributes` are.
> 
> This is more complicated than I thought, as it relies completely on the field being indexed, and there is no simple way to do it. Could we instead give the user a list of known fields along with the fields distribution?
> 
> On top of that, I am not sure this information is relevant anymore, since accept new field doesn't exist anymore, us knowing or not that a field exists is irrelevant.
> 
> Until we make a decision, I am merging a partial PR with the work already accomplished for the release of v0.13.0

@MarinPostma 

So if I understand, this is not going to be present in the v0.13.0?

**Comment by MarinPostma** [comment]
No this is postponed, sorry I should have made sure everyone had acknowledged

**Comment by MarinPostma** [comment]
the remaining of this issue is now part of #905. closing.
