### ISSUE TITLE
Lazily create an index

### ISSUE THREAD

**Issue by qdequele** [meilisearch/MeiliSearch#918]
# Summary

This feature should able to create an index when: 
- the user pushes its first document (replace or update)on a new index name
- the user pushes settings on a new index name

# Motivations

It can be a bit annoying to have to manually create each index during the process of setting. Currently, the only way to do is to start by creating an index and then push config and documents on it. 

# Explanation

The proposal consist to change the first part of the add_documents handlers. This handler is used by the methods add_or_replace and add_or_update. And also to change the first part on all settings update methods.

**Be careful, once the update has gone into the asynchronous queue it is then no longer possible to automatically delete the index in case of an error**. If it was the case then in the case of an error the user could not know why the update failed.

# Implementation

Previously, if the index name was not found, an error of type `index_not_found` was returned. Instead, the engine could create a new index with the data it already knows. It can find the index name/id in the URL called `/indexes/<index_id>`. 
It's also possible to have the primary key, either with the existing `primaryKey` query parameter or by deduction as it already does in the add document route. Constraints should be the same as for creating a regular index, i.e. it should be composed of alphanumeric characters only, and either '_' or '-'. 

If an error happens after the index creation, in that case, the previously created and empty index will be deleted. 
At the moment it's impossible to delete index if the update (setting or documents) failed. Due to the fact that updates are asynchronous.

## Steps

Add functionality.

# Related

- [ ] Validated by the team (@meilisearch/core-team, @meilisearch/integration-team)
- [x] Test added
- [ ] [Documentation](https://github.com/meilisearch/documentation/issues/#xxx) //Change xxx or remove the line
- [ ] [SDK/Integrations](https://github.com/meilisearch/integration-guides/issues/#xxx) //Change xxx or remove the line

**Comment by curquiza** [comment]
If I understand well, this implementation would be available with the [add or update documents](https://docs.meilisearch.com/references/documents.html#add-or-update-documents) and the [add or replace documents](https://docs.meilisearch.com/references/documents.html#add-or-replace-documents) routes, right?

About the errors, the issue does not mention them.
When adding/updating documents, we can have two kinds of error:
- a "direct" error: when sending the request, we do not receive an `updateId` with a `200` but an error (`4xx`).
Ex: an invalid JSON
- an "asynchronous" error: when sending the request, we do get an `updateId`, but the update fails and we can see we get an error thanks to the `GET /index/:index_uid/updates` route.
Ex: the document id is missing

**In both cases, from my POV, the index should not be created**. Indeed, in both cases, the users get an error and cannot expect something to be done since they do not get any warning "your index has been created anyway".
It could lead to a lot of "dead" indexes in the MeiliSearch instances of the users.
What do you think?

**Comment by curquiza** [comment]
And why are the tests already marked as "done"? (I might missed the PR about them, sorry)

**Comment by bidoubiwa** [comment]
I aggree with @curquiza. 
I don't think anyone would expect the index to be created after recieving an error. This makes any error an "unexpected behavior" as it is not clear what will happen in case of an error.

**Comment by qdequele** [comment]
> If I understand well, this implementation would be available with the add or update documents and the add or replace documents routes, right?

Yes, a possible question, what about the settings routes? Is it cool to create an index by pushing settings on a non existing index?

For the error cases, I am totally agree with you. But, unfortunatly, it's is not possible for now to create an index with a transaction. The transaction are only on index and are not on the entire DB. Perhaps @Kerollmops have an idea for this.

> And why are the tests already marked as "done"? (I might have missed the merged PR about them, sorry)

I added 3 test for that. https://github.com/meilisearch/MeiliSearch/pull/914/commits/397cabfc389a47f0118e8c7d4ae6d03b6597662c

**Comment by curquiza** [comment]
> Yes, a possible question, what about the settings routes? Is it cool to create an index by pushing settings on a non existing index?

Hum, interesting! Algolia does it! I've just checked. That could be nice, but not an emergency feature from my POV, what do you think?

> I added 3 test for that. [397cabf](https://github.com/meilisearch/MeiliSearch/commit/397cabfc389a47f0118e8c7d4ae6d03b6597662c)

(Ok, they are not merged yet)
If I'm not wrong the tests are only done on the `POST` route, not the `PUT` one.
And there is no test to check the behavior of "I have an asynchronous error, my index is (not) created"

**Comment by qdequele** [comment]
**Edited**

**Comment by qdequele** [comment]
EDIT: **Be careful, once the update has gone into the asynchronous queue it is then no longer possible to automatically update the index in case of an error**. If it was the case then in the case of an error the user could not know why the update failed.

**Comment by bidoubiwa** [comment]
A few questions about the implementation user side.

Given the following example:
```javascript
const client = new MeiliSearch({..})
const update = client.getIndex("movies").addDocuments(dataset) // this is equivalent to localhost/indexes/movie/documents --data @dataset
const status = client.getIndex("movies").getUpdate(update.updateId)
console.log(status) // ?
```
In this case, `movies` will be created before adding the documents. 
Does this example looks good to you ?
What will `status` look like? What will the `type` be inside the status ? I've put an example of a status bellow for context

```json
{
  "status": "processed",
  "updateId": 1,
  "type": {
    "name": "?",
    "number": 19653 // ?
  },
  "duration": 12.757581815,
  "enqueuedAt": "2019-12-07T21:10:07.607581330Z",
  "processedAt": "2019-12-07T21:10:20.511525620Z"
}
```

> It's also possible to have the primary key, either with the existing `primaryKey` parameter or by deduction as it already does in the add document route.

What do you mean with "the existing `primaryKey`"? There would be no way to add a specific primary key? Or does should this work?:

```javascript
const update = client.getIndex("movies").addDocuments(dataset, { primaryKey: "movieskud" })
```

**Comment by qdequele** [comment]
Instead of potential errors, create the index will be completely transparent. The type remains the same, `DocumentsAddition` in case of a document addition and `Settings` in case of settings modification. The update queue will still exactly the same as if you had created an index then push documents. 

The example you give seems correct to me. For the `primaryKey`, the behavior still the same as before, you can give it as a query parameter as [documented](https://docs.meilisearch.com/references/documents.html#add-or-replace-documents).

The following implementation seem interesting. I think that is an other debate, but this one is clear to me. 
```js
const update = client.getIndex("movies").addDocuments(dataset, { primaryKey: "movieskud" })
```

**Comment by bidoubiwa** [comment]
With the arrival of the `lazy Index1 we should completely rethink the `get_index` naming. Thanks for your answers, looks good to me :)

**Comment by eskombro** [comment]
This feature seems to work perfectly (we tested it a bit with the integration team)! 🎉 

A simple suggestion: 

If there is an error in the index creation, we have seen that the error sent to the user is the error thrown by the index creation instead of the documents addition response, and that is great! But maybe it misses a little bit of context for the user, who doesn't necessarily know what's going on behind the scenes. 

**Is it possible to add, for example in the `message` that this error is coming from the index creation specifically?**

For example, prefacing the message with "Error while creating index 'XXX': <the error message>"

## example

I do a POST request, I want to add documents to an unexistant index, I give this index a name containing invalid characters: `/indexes/@@@/documents`

the response looks like this:

```json
{
    "message": "Index must have a valid uid; Index uid can be of type integer or string only composed of alphanumeric characters, hyphens (-) and underscores (_).",
    "errorCode": "invalid_index_uid",
    "errorType": "invalid_request_error",
    "errorLink": "https://docs.meilisearch.com/errors#invalid_index_uid"
}
```

it could look like this:

```json
{
    "message": "Error creating index '@@@': Index must have a valid uid; Index uid can be of type integer or string only composed of alphanumeric characters, hyphens (-) and underscores (_).",
    "errorCode": "invalid_index_uid",
    "errorType": "invalid_request_error",
    "errorLink": "https://docs.meilisearch.com/errors#invalid_index_uid"
}
```

**Comment by Kerollmops** [comment]
@eskombro I understand your point but I am sure the `errorCode` and `errorLink` will give enough context to the user to understand the origin of the error, furthermore it will add a lot of code just for this specific behavior (lazy index creation).

**Comment by eskombro** [comment]
I agree with you @Kerollmops, this suggestion is ok only if it is really easy to implement, if it creates a different logic just to handle that, it may not be worth it ;)
