### ISSUE TITLE
Refactor `/health` route

### ISSUE THREAD

**Issue by LegendreM** [meilisearch/MeiliSearch#940]
# Summary

Change `/health` route behaviors to fit more the common use.
Related to this [discussion](https://github.com/meilisearch/MeiliSearch/issues/930).

# Motivations

`health` route in meilisearch was used to inform about service maintainances, which is not the idomatic use of it.
The health route should only inform about the [availability of meilisearch](https://github.com/meilisearch/MeiliSearch/issues/930#issuecomment-680772125).

# Explanation

the `health` route:
- NEEDS to ensure that service is completely up if it returns 201
- DOES NOT block service process (write transaction)
- NEEDS to use the less network bandwidth as possible when it's triggered
- NEEDS to use the less service resources as possible when it's triggered
- DOES NOT NEED any authentication
- MAY be named /health

# Implementation

A trivial approach would be make `/health` route always return `204`

a more complex approach would be to enumerate all checks we need to do to consider meilisearch as available/healthy.

`set_healthy` and `set_unhealthy` should be removed

source code to refactor [here](https://github.com/meilisearch/MeiliSearch/blob/master/meilisearch-http/src/routes/health.rs)
test code to adapt [here](https://github.com/meilisearch/MeiliSearch/blob/master/meilisearch-http/tests/health.rs)

# Related

- [ ] Validated by the team
- [ ] Test added
- [ ] [Documentation](https://github.com/meilisearch/documentation/issues/#xxx) TBD
- [ ] [SDK/Integrations](https://github.com/meilisearch/integration-guides/issues/#xxx) TBD

**Comment by curquiza** [comment]
Hello! Why does this route returns a `201`? `201` is used when a resource is created.

**Comment by eskombro** [comment]
> is used when a resource is created

I agree, I think we should use 200

**Comment by LegendreM** [comment]
sorry for the typo, I wanted `204`

**Comment by AlyHKafoury** [comment]
Hello @LegendreM Can I please work on this ticket as an opensource contribution ?

**Comment by LegendreM** [comment]
Hey @AlyHKafoury, yes don't hesitate!

**Comment by frbimo** [comment]
hi @AlyHKafoury , are you still working on this? if not i may pick this up.

**Comment by curquiza** [comment]
What is the final decision about this issue:

> A trivial approach would be make /health route always return 204

> a more complex approach would be to enumerate all checks we need to do to consider meilisearch as available/healthy.

I guess the trivial approach is chosen, can you confirm?

## Summary

If I understand well:
- [update health route](https://docs.meilisearch.com/references/health.html#update-health) is removed
- [get health route](https://docs.meilisearch.com/references/health.html#get-health) will always return a `204` if we success to reach the MeiliSearch.

Do I forget something?

**Comment by LegendreM** [comment]
Yep @curquiza  the `trivial approach` is chosen because we don't have any sanity check to do during run time. If meilisearch as an hard failure the server doesn't run and health route doesn't respond.

**Comment by curquiza** [comment]
Thanks for the confirmation! Good to me then 🚀

**Comment by bidoubiwa** [comment]
What are possible error responses from health route in case it is not a '204' ( responses with a Meilisearch error body )? If some exists of course. 

Can we receive the maintenance 'errorCode'?
