### ISSUE TITLE
Allow user to limit the max number of words in a query

### ISSUE THREAD

**Issue by LegendreM** [meilisearch/MeiliSearch#941]
# Summary

Be able to limit the number of word accepted in a query.

# Motivations

meilisearch is getting slower the longer the query is (#925), which induce several issues:
- a common user may not be interested by a request which the response time is long
- a malicious user could flood long request to make meilisearch hang

# Explanation

add a `max_query_word` settings to choose it

# Related

- [ ] Validated by the team
- [ ] Test added
- [ ] [Documentation](https://github.com/meilisearch/documentation/issues/#xxx) TBD
- [ ] [SDK/Integrations](https://github.com/meilisearch/integration-guides/issues/#xxx) TBD

**Comment by nubpro** [comment]
Hope this gets look into and expedited as server crashes are getting more rampant.

**Comment by MarinPostma** [comment]
Yep this is prioritized for the next release.

We need to limit the number of tokens taken in the when tokenizing the query string here:  https://github.com/meilisearch/MeiliSearch/blob/master/meilisearch-core/src/query_tree.rs#L177-L186

**Comment by Nick-Mazuk** [comment]
So I was doing a quick test, and I don't think that setting this limit will solve the underlying issue, just a symptom. It's better than nothing, it's just not the cause.

I spun up a new MeiliSearch instance (v0.18) without any documents, only one index, and tried searching through it. Here's how long each search took.

| # of words  | Processing time (ms) |
| ----------- | --------------------- |
|          1          |          0          |
|          2          |          2          |
|          3          |          4          |
|          4          |          9          |
|          5          |          18          |
|          6          |          64          |
|          7          |          120          |
|          8          |          209          |
|          9          |          193          |
|          10          |          382          |
|          11          |          710          |
|          12          |          1358          |

Query: "this query is really and tests meilisearch's limits by measuring processing time"

If I were to take a guess, the root cause does not seem to be the actual search operations since this delay exists even when there is no data. The root cause seems to be with how the query term is parsed.

With that said, I'm all for adding a setting that limits the number of parsed words, but it would be nice to eliminate (or at least greatly reduce) the issue in the base case.

**Comment by MarinPostma** [comment]
thank you! this is very interesting! @Kerollmops could this be linked to the building of the query fst? @LegendreM thi smay interest you too

**Comment by Kerollmops** [comment]
Hey thank you @Nick-Mazuk for this in depth analysis,

I am currently looking into this, and have already found some ways to reduce the cost of interating through [the words dictionnary](https://docs.rs/fst/0.4.5/fst/struct.Set.html). It is indeed not [the DFA creation](https://docs.rs/levenshtein_automata) that takes time but the fact that we visit that datastructure and we do a lot of operation we the words associated documents before even searching.
