### ISSUE TITLE
Update of the dump status body

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#998]
# Summary

The body of the dump status should be improved.

# Motivations

For the moment the body has two informations:
- the `dumps_uid` written as `uid`
- the status of the given `dumps_uid`

The status can have 3 values `processing`, `dump_process_failed` and `done`. There is a lack of consistency between the status itself, and between these 3 status and the status we use in the `indexes/:index/updates` route. 
Because we want generic status that we will use in any other futur sub `status` route, these are the suggested status: `in_process`, `failed`, `done`.

`failed` is also the one used in the `/indexes/:index/updates` route. Which makes it possible to make a check on the `failed` status in every asynchronous update in MeiliSearch.

In case the status returns `failed`, we should provide the full error body present in every other failing-case in MeiliSearch. Which contains the following keys: `message`, `errorCode`, `errorType`, `errorLink`

Why are we doing this? What use cases does it support? What is the expected outcome?

# Explanation

Explain the proposal like it was the final documentation of this proposal.

- What is changing for end-users.
The status key in the status body in the dump route used to have 3 possible outcomes: `processing`, `dump_process_failed` and `done`. With this change they will have these possible outcomes: `in_progress`, `failed`, `done`.

Also, in case it fails, the error_code was previously given as a `status`. With these changes, the error information will be added in the body of the status, this way: 
```json
{
    "uid": "20201008-105011897",
    "status": "failed",
    "message": "Another dump is already in progress",
    "errorCode": "dump_already_in_progress",
    "errorType": "invalid_request_error",
    "errorLink": "https://docs.meilisearch.com/errors#dump_already_in_progress"
}
```
- How it works.
`GET /dumps/:dumps_uid/status`

- What is breaking?
The status codes of the dumps status route.

- Examples.

```bash
$ curl -X GET 'http://localhost:7700/dumps/123456-456/status'
```

```json
{
    "uid": "20201008-105011897",
    "status": "failed",
    "message": "Dump process failed",
    "errorCode": "dump_process_failed",
    "errorType": "invalid_request_error",
    "errorLink": "https://docs.meilisearch.com/errors#dump_process_failed"
}
```

# Implementation

// @LegendreM 

# Related

#991 and #995 

## Todo

- [x] Change status name to `done`, `in_progress` and `failed`
- [x] Add error body in case of failure
- [x] Test added
- [ ] [Documentation](https://github.com/meilisearch/documentation/issues/#xxx) //Change xxx or remove the line

**Comment by LegendreM** [comment]
here is the new status when an error occurs:
```json
{
  "uid": "20201012-063113929",
  "status": "failed",
  "message": "Dump process failed: generating settings for index test; No such file or directory (os error 2)",
  "errorCode": "dump_process_failed",
  "errorType": "internal_error",
  "errorLink": "https://docs.meilisearch.com/errors#dump_process_failed"
}
```
